repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=no]
      - id: trailing-whitespace
        types: [file, text]

  - repo: https://github.com/eschulte/lisp-format
    rev: 088c8f78ca41204b44f2636275517ac09a2de6a9
    hooks:
      - id: lisp-format
        name: formatter of lisp code
        description: Run lisp-format against lisp files
        language: script
        files: \.(lisp|cl|asd|scm|el)$
        entry: lisp-format -i

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
