;;; Org-capture
;;; https://orgmode.org/manual/Capture.html#Capture)
(setq org-default-notes-file (concat org-directory "/notes.org"))
(setq org-capture-templates
      '(	;; Agenda
	("a" "Agenda")
	("an" "New Event" entry (file+olp "~/org/agenda.org" "Upcoming")
         "** TODO %t %?\n" :prepend t)
	;; Bibliography
	("b" "Bibliography" item (file+olp "~/org/references.bib")
         "%?\n" :prepend t)
	;; Computing
	("c" "Computing")
	("ce" "Emacs" entry (file+olp "~/org/computing.org" "Emacs")
         "* TODO %?\n" :prepend t)
	("cl" "Laptop" entry (file+olp "~/org/computing.org" "Laptop")
         "* TODO %?\n" :prepend t)
	("cd" "Desktop" entry (file+olp "~/org/computing.org" "Desktop")
         "* TODO %?\n" :prepend t)
	("cn" "Networking/Routers" entry (file+olp "~/org/computing.org" "Networking/Routers")
         "* TODO %?\n" :prepend t)
	("cq" "Printers" entry (file+olp "~/org/computing.org" "Printers")
         "* TODO %?\n" :prepend t)
	("cr" "RaspberryPi" entry (file+olp "~/org/computing.org" "Raspberry Pi")
         "* TODO %?\n" :prepend t)
	("cm" "AirQuality Monitor" entry (file+olp "~/org/computing.org" "AirQuality Monitor")
         "* TODO %?\n" :prepend t)
	("ca" "Android" entry (file+olp "~/org/computing.org" "Android")
         "* TODO %?\n" :prepend t)
	("cp" "Programming") ;; Programming
	("cpb" "" entry (file+olp "~/org/computing.org" "Programming" "Bash")
         "* TODO %?\n" :prepend t)
	("cpe" "MongoDB" entry (file+olp "~/org/computing.org" "Programming" "MongoDB")
         "* TODO %?\n" :prepend t)
	("cpp" "Python" entry (file+olp "~/org/computing.org" "Programming" "Python")
         "* TODO %?\n" :prepend t)
	("cpg" "Git" entry (file+olp "~/org/computing.org" "Programming" "Git")
         "* TODO %?\n" :prepend t)
	("cpl" "LaTeX" entry (file+olp "~/org/computing.org" "Programming" "LaTeX")
         "* TODO %?\n" :prepend t)
	("cpr" "R" entry (file+olp "~/org/computing.org" "Programming" "R")
         "* TODO %?\n" :prepend t)
	("cv" "VPS" entry (file+olp "~/org/computing.org" "VPS")
         "* TODO %?\n" :prepend t)
	;; Drugs
	("d" "Psychedeleics")
	("dd" "DMT" (file+olp "~/org/psychedelics.org" "DMT")
	 "+ %?\n" :prepend t)
	("ddp" "DMT" (file+olp "~/org/psychedelics.org" "DMT" "Popular Science")
	 "+ %?\n" :prepend t)
	("ddr" "DMT" (file+olp "~/org/psychedelics.org" "DMT" "Peer Reviewed")
	 "+ %?\n" :prepend t)
	("dl" "LSD" (file+olp "~/org/psychedelics.org" "LSD")
	 "+ %?\n" :prepend t)
	("dlp" "Popular Science" (file+olp "~/org/psychedelics.org" "LSD" "Popular Science")
	 "+ %?\n" :prepend t)
	("dlr" "Peer Reviewed" (file+olp "~/org/psychedelics.org" "LSD" "Peer Reviewed")
	 "+ %?\n" :prepend t)
	("dl" "Psilocybin" (file+olp "~/org/psychedelics.org" "Psilocybin")
	 "+ %?\n" :prepend t)
	("dpp" "Popular Science" (file+olp "~/org/psychedelics.org" "Psilocybin" "Popular Science")
	 "+ %?\n" :prepend t)
	("dpr" "Peer Reviewed" (file+olp "~/org/psychedelics.org" "Psilocybin" "Peer Reviewed")
	 "+ %?\n" :prepend t)
	("do" "Books" (file+olp "~/org/psychedelics.org" "Books")
	 "+ %?\n" :prepend t)
	("di" "Interviews" (file+olp "~/org/psychedelics.org" "Interviews")
	 "+ %?\n" :prepend t)
	("db" "Blogs" (file+olp "~/org/psychedelics.org" "Blogs")
	 "+ %?\n" :prepend t)
	("dr" "Terrence McKenna" (file+olp "~/org/psychedelics.org" "Terrence McKenna")
	 "+ %?\n" :prepend t)
	;; Workouts
	("e" "Exercise")
        ("er" "Logging a run" table-line (file+olp "~/org/training/training.org" "Running" "Log")
	 "| %t | %? | km | min + s | | |" :prepend t)
	("ec" "Logging a cycle" table-line (file+olp "~/org/training/training.org" "Cycling" "Log")
	 "| %t | %? | km | min + s | | |" :prepend t)
	("eh" "Logging a hike" table-line (file+olp "~/org/training/training.org" "Hiking" "Log")
	 "| %t | %? | km | min + s | | |" :prepend t)
	("em" "Weight & Waist/Hip" table-line (file+olp "~/org/training/training.org" "Metrics" "Weight/Waist Hip Ratio" "Log")
	 "| %U | %? | | | |" :prepend t)
	("ep" "Blood Pressure" table-line (file+olp "~/org/training/training.org" "Metrics" "Blood Pressure" "Log")
	 "| %U | %? | | | |" :prepend t)
	("es" "Training Resources") ;; Training Resources
	("esr" "Running" entry (file+olp "~/org/training/training.org" "Resources" "Running")
         "* TODO %?\n" :prepend t)
	("ess" "Calisthenics" entry (file+olp "~/org/training/training.org" "Resources" "Calisthenics")
         "* TODO %?\n" :prepend t)
	("esc" "Training Resources (Climbing)")
	("escm" "Miscellaneous" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Miscellaneous")
          "+  %?\n" :prepend t)
	("escf" "Fingerboarding" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Fingerboarding")
         "+  %?\n" :prepend t)
	("escs" "Shauna Coxy" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Shauna Coxy")
         "+  %?\n" :prepend t)
	;; Cooking
	("f" "Food & Drink")
	("fv" "Vegetarian" item (file+olp "~/org/food_drink.org" "Vegetarian")
         "+ %?\n" :prepend t)
	("fw" "Web sites" item (file+olp "~/org/food_drink.org" "Web Sites")
         "+ %?\n" :prepend t)
	("fu" "Indian")
	("fus" "Starters" item (file+olp "~/org/food_drink.org" "Indian" "Starters")
         "+ %?\n" :prepend t)
	("fuc" "Curries" item (file+olp "~/org/food_drink.org" "Indian" "Curries")
         "+ %?\n" :prepend t)
	("fub" "Breads" item (file+olp "~/org/food_drink.org" "Indian" "Breads")
         "+ %?\n" :prepend t)
	("fh" "Chinese")
	("fhs" "Starters" item (file+olp "~/org/food_drink.org" "Chinese" "Starters")
         "+ %?\n" :prepend t)
	("fhr" "Rice" item (file+olp "~/org/food_drink.org" "Chinese" "Rice")
         "+ %?\n" :prepend t)
	("fhn" "Noodles" item (file+olp "~/org/food_drink.org" "Chinese" "Noodles")
         "+ %?\n" :prepend t)
	("fi" "Italian")
	("fip" "Pasta" item (file+olp "~/org/food_drink.org" "Italian" "Pasta")
         "+ %?\n" :prepend t)
	("fiz" "Pizza" item (file+olp "~/org/food_drink.org" "Italian" "Pizza")
         "+ %?\n" :prepend t)
	("fs" "Spanish" item (file+olp "~/org/food_drink.org" "Italian" "Pasta")
         "+ %?\n" :prepend t)
	("fb" "Books" item (file+olp "~/org/food_drink.org" "Books")
         "+ %?\n" :prepend t)
	;; Isla
	("i" "Activities for Isla")
	("ie" "Educational" item (file+olp "~/org/isla.org" "Educational")
         "+ %t %?\n" :prepend t)
	("ix" "Exercise" item (file+olp "~/org/isla.org" "Exercise")
         "+ %t %?\n" :prepend t)
	("if" "Fun" item (file+olp "~/org/isla.org" "Fun")
         "+ %t %?\n" :prepend t)
	("ig" "Gardening" item (file+olp "~/org/isla.org" "Gardening")
         "+ %t %?\n" :prepend t)
	;; Paula
	("p" "Paula")
	("pa" "Anger" item (file+olp "~/org/paula.org" "Anger")
         "+ %U %?\n" :prepend t)
	("pf" "Food" item (file+olp "~/org/paula.org" "Food")
         "+ %U %?\n" :prepend t)
	("ph" "Help" item (file+olp "~/org/paula.org" "Help")
         "+ %U %?\n" :prepend t)
	("pl" "Listening" item (file+olp "~/org/paula.org" "Not Listening")
         "+ %U %?\n" :prepend t)
	("pt" "Tidying" item (file+olp "~/org/paula.org" "Tidying")
         "+ %U %?\n" :prepend t)
	;; TODO
	("t" "Stuff ToDo in my Life")
	("th" "House Tasks" entry (file+olp "~/org/todo.org" "House")
         "* TODO %?\n" :prepend t)
	("tg" "Gardening" entry (file+olp "~/org/todo.org" "Garden")
         "* TODO %?\n" :prepend t)
	("tv" "Campervan" entry (file+olp "~/org/todo.org" "Campervan")
         "* TODO %?\n" :prepend t)
	("tc" "Car" entry (file+olp "~/org/todo.org" "Car")
         "* TODO %?\n" :prepend t)
	("tg" "Bike" entry (file+olp "~/org/todo.org" "Bike")
         "* TODO %?\n" :prepend t)
	("ts" "Stuff to Sell" entry (file+olp "~/org/todo.org" "Stuff To Sell")
         "* TODO %?\n" :prepend t)
	;; Coronavirus
	("v" "Coronavirus")
	("vc" "Collections/Streams")
	("vca" "The Atlantic" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Atlantic")
         "+ %t %?\n" :prepend t)
	("vcb" "BMJ" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "BMJ")
         "+ %t %?\n" :prepend t)
	("vcb" "BioRxiv" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "BioRxiv")
         "+ %t %?\n" :prepend t)
	("vcd" "David Spiegelhalter" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "David Spiegelhalter")
         "+ %t %?\n" :prepend t)
	("vcg" "The Guardian" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Guardian")
         "+ %t %?\n" :prepend t)
	("vcl" "The Lancet" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Lancet")
         "+ %t %?\n" :prepend t)
	("vcn" "New Scientist" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "New Scientist")
         "+ %t %?\n" :prepend t)
	("vco" "ONS" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "ONS")
         "+ %t %?\n" :prepend t)
	("vcs" "Significance" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "Significance magazine")
         "+ %t %?\n" :prepend t)
	("vcw" "Wired" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "Wired")
         "+ %t %?\n" :prepend t)
	("vd" "Data" item (file+olp "~/org/coronavirus.org" "Data")
         "+ %t %?\n")
	("ve" "Evolutionary Genetics" item (file+olp "~/org/coronavirus.org" "Evolutionary Genetics"))
	("ve" "Herd Immunity" item (file+olp "~/org/coronavirus.org" "Herd Immunity"))
	("vi" "Immunity / Testing / Vaccine" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine")
         "+ %t %?\n" :prepend t)
	("vg" "Independant SAGE" item (file+olp "~/org/coronavirus.org" "Independant SAGE")
         "+ %t %?\n" :prepend t)
	("vh" "Mechanism" item (file+olp "~/org/coronavirus.org" "Mechanism")
         "+ %t %?\n" :prepend t)
	("vm" "Miscellaneous" item (file+olp "~/org/coronavirus.org" "Miscellaneous")
         "+ %t %?\n" :prepend t)
	("vo" "Mortality Rates" item (file+olp "~/org/coronavirus.org" "Mortality Rates")
         "+ %t %?\n" :prepend t)
	("vp" "Physical Distancing / Face Masks" item (file+olp "~/org/coronavirus.org" "Physical Distancing / Face Masks")
         "+ %t %?\n" :prepend t)
	("vr" "Risk" item (file+olp "~/org/coronavirus.org" "Risk Assessment")
         "+ %t %?\n" :prepend t)
	("vt" "Track and Trace" item (file+olp "~/org/coronavirus.org" "Track and Trace")
         "+ %t %?\n" :prepend t)
	("vu" "Transmission" item (file+olp "~/org/coronavirus.org" "Transmission")
         "+ %t %?\n" :prepend t)
	("vt" "Traffic")
	("vtc" "Cycling" item (file+olp "~/org/coronavirus.org" "Traffic" "Cycling")
         "+ %t %?\n")
	("vtr" "Roads" item (file+olp "~/org/coronavirus.org" "Traffic" "Roads")
         "+ %t %?\n")
	("vw" "Work" item (file+olp "~/org/coronavirus.org" "Work")
         "+ %t %?\n")
	("vh" "Humour") ;; Humour
	("vhg" "Graphics" item (file+olp "~/org/coronavirus.org" "Humour" "Graphics")
         "+ %t %?\n" :prepend t)
	("vhx" "XKCD" item (file+olp "~/org/coronavirus.org" "Humour" "XKCD")
         "+ %t %?\n" :prepend t)
	("vz" "Non-Science")
	("vzs" "Sheffield" item (file+olp "~/org/coronavirus.org" "Non-Science" "Sheffield")
         "+ %t %?\n" :prepend t)
	;; Work
	("w" "Work")
	("wp" "Work Projects" entry (file+olp "~/org/thefloow.org" "Project")
	 "** TODO %t %?\n" :prepend t)
	("ww" "ToDo Tasks" entry (file+olp "~/org/thefloow.org" "ToDo Tasks")
	 "** TODO %t %?\n" :prepend t)
	))
