;;; Org-capture
;;; https://orgmode.org/manual/Capture.html#Capture)
(setq org-default-notes-file (concat org-directory "/notes.org"))
(setq org-capture-templates
      '(("t" "Stuff ToDo in my Life") ;; TODO
	("th" "House Tasks" entry (file+olp "~/org/todo.org" "House")
         "* TODO %?\n" :prepend t)
	("tg" "Gardening" entry (file+olp "~/org/todo.org" "Garden")
         "* TODO %?\n" :prepend t)
	("tv" "Campervan" entry (file+olp "~/org/todo.org" "Campervan")
         "* TODO %?\n" :prepend t)
	("tc" "Car" entry (file+olp "~/org/todo.org" "Car")
         "* TODO %?\n" :prepend t)
	("tg" "Bike" entry (file+olp "~/org/todo.org" "Bike")
         "* TODO %?\n" :prepend t)
	("ts" "Stuff to Sell" entry (file+olp "~/org/todo.org" "Stuff To Sell")
         "* TODO %?\n" :prepend t)
	("c" "Computing") ;; Computing
	("ce" "Emacs" entry (file+olp "~/org/computing.org" "Emacs")
         "* TODO %?\n" :prepend t)
	("cl" "Laptop" entry (file+olp "~/org/computing.org" "Laptop")
         "* TODO %?\n" :prepend t)
	("cd" "Desktop" entry (file+olp "~/org/computing.org" "Desktop")
         "* TODO %?\n" :prepend t)
	("cn" "Networking/Routers" entry (file+olp "~/org/computing.org" "Networking/Routers")
         "* TODO %?\n" :prepend t)
	("cq" "Printers" entry (file+olp "~/org/computing.org" "Printers")
         "* TODO %?\n" :prepend t)
	("cr" "RaspberryPi" entry (file+olp "~/org/computing.org" "Raspberry Pi")
         "* TODO %?\n" :prepend t)
	("cm" "AirQuality Monitor" entry (file+olp "~/org/computing.org" "AirQuality Monitor")
         "* TODO %?\n" :prepend t)
	("ca" "Android" entry (file+olp "~/org/computing.org" "Android")
         "* TODO %?\n" :prepend t)
	("cp" "Programming") ;; Programming
	("cpb" "" entry (file+olp "~/org/computing.org" "Programming" "Bash")
         "* TODO %?\n" :prepend t)
	("cpe" "MongoDB" entry (file+olp "~/org/computing.org" "Programming" "MongoDB")
         "* TODO %?\n" :prepend t)
	("cpp" "Python" entry (file+olp "~/org/computing.org" "Programming" "Python")
         "* TODO %?\n" :prepend t)
	("cpg" "Git" entry (file+olp "~/org/computing.org" "Programming" "Git")
         "* TODO %?\n" :prepend t)
	("cpl" "LaTeX" entry (file+olp "~/org/computing.org" "Programming" "LaTeX")
         "* TODO %?\n" :prepend t)
	("cpr" "R" entry (file+olp "~/org/computing.org" "Programming" "R")
         "* TODO %?\n" :prepend t)
	("cv" "VPS" entry (file+olp "~/org/computing.org" "VPS")
         "* TODO %?\n" :prepend t)
	("e" "Exercise Workouts") ;; Workouts
        ("er" "Logging a run" table-line (file+olp "~/org/training/training.org" "Workouts" "Running" "Log")
	 "| %t | %? | km | min + s | | |" :prepend t)
	("ec" "Logging a cycle" table-line (file+olp "~/org/training/training.org" "Workouts" "Cycling" "Log")
	 "| %t | %? | km | min + s | | |" :prepend t)
	("eh" "Logging a hike" table-line (file+olp "~/org/training/training.org" "Workouts" "Hiking" "Log")
	 "| %t | %? | km | min + s | | |" :prepend t)
	("em" "Logging metrics" table-line (file+olp "~/org/training/training.org" "Workouts" "Metrics" "Log")
	 "| %t | %? | | | |" :prepend t)
	("es" "Training Resources") ;; Training Resources
	("esr" "Running" entry (file+olp "~/org/training/training.org" "Resources" "Running")
         "* TODO %?\n" :prepend t)
	("ess" "Calisthenics" entry (file+olp "~/org/training/training.org" "Resources" "Calisthenics")
         "* TODO %?\n" :prepend t)
	("esc" "Training Resources (Climbing)")
	("escm" "Miscellaneous" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Miscellaneous")
          "+  %?\n" :prepend t)
	("escf" "Fingerboarding" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Fingerboarding")
         "+  %?\n" :prepend t)
	("escs" "Shauna Coxy" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Shauna Coxy")
         "+  %?\n" :prepend t)
	("w" "Work") ;; Work
	("wp" "Work Projects" entry (file+olp "~/org/thefloow.org" "Project")
	 "** TODO %t %?\n" :prepend t)
	("ww" "ToDo Tasks" entry (file+olp "~/org/thefloow.org" "ToDo Tasks")
	 "** TODO %t %?\n" :prepend t)
	("o" "Cooking") ;; Cooking
	("ov" "Vegetarian" item (file+olp "~/org/cooking.org" "Vegetarian")
         "+ %?\n" :prepend t)
	("ow" "Web sites" item (file+olp "~/org/cooking.org" "Web Sites")
         "+ %?\n" :prepend t)
	("ou" "Indian")
	("ous" "Starters" item (file+olp "~/org/cooking.org" "Indian" "Starters")
         "+ %?\n" :prepend t)
	("ouc" "Curries" item (file+olp "~/org/cooking.org" "Indian" "Curries")
         "+ %?\n" :prepend t)
	("oub" "Breads" item (file+olp "~/org/cooking.org" "Indian" "Breads")
         "+ %?\n" :prepend t)
	("oh" "Chinese")
	("ohs" "Starters" item (file+olp "~/org/cooking.org" "Chinese" "Starters")
         "+ %?\n" :prepend t)
	("ohr" "Rice" item (file+olp "~/org/cooking.org" "Chinese" "Rice")
         "+ %?\n" :prepend t)
	("ohn" "Noodles" item (file+olp "~/org/cooking.org" "Chinese" "Noodles")
         "+ %?\n" :prepend t)
	("oi" "Italian")
	("oip" "Pasta" item (file+olp "~/org/cooking.org" "Italian" "Pasta")
         "+ %?\n" :prepend t)
	("oiz" "Pizza" item (file+olp "~/org/cooking.org" "Italian" "Pizza")
         "+ %?\n" :prepend t)
	("os" "Spanish" item (file+olp "~/org/cooking.org" "Italian" "Pasta")
         "+ %?\n" :prepend t)
	("ob" "Books" item (file+olp "~/org/cooking.org" "Books")
         "+ %?\n" :prepend t)
	("v" "Coronavirus") ;; Coronavirus
	("vi" "Information")
	("viu" "Useful Resources" item (file+olp "~/org/coronavirus.org" "Information" "Useful Resources")
         "+ %t %?\n" :prepend t)
	("viuc" "Collections/Streams")
	("viucn" "New Scientist" item (file+olp "~/org/coronavirus.org" "Information" "Useful Resources" "Collections/Streams" "New Scientist")
         "+ %t %?\n" :prepend t)
	("viuca" "The Atlantic" item (file+olp "~/org/coronavirus.org" "Information" "Useful Resources" "Collections/Streams" "The Atlantic")
         "+ %t %?\n" :prepend t)
	("viuco" "ONS" item (file+olp "~/org/coronavirus.org" "Information" "Useful Resources" "Collections/Streams" "ONS")
         "+ %t %?\n" :prepend t)
	("viucg" "The Guardian" item (file+olp "~/org/coronavirus.org" "Information" "Useful Resources" "Collections/Streams" "The Guardian")
         "+ %t %?\n" :prepend t)
	("viucd" "David Spiegelhalter" item (file+olp "~/org/coronavirus.org" "Information" "Useful Resources" "Collections/Streams" "David Spiegelhalter")
         "+ %t %?\n" :prepend t)
	("vis" "Science") ;; Science
	("visc" "Miscellaneous" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Miscellaneous")
         "+ %t %?\n" :prepend t)
	("visg" "Independant SAGE" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Independant SAGE")
         "+ %t %?\n" :prepend t)
	("visi" "Immunity / Testing / Vaccine" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Immunity / Testing / Vaccine")
         "+ %t %?\n" :prepend t)
	("vism" "Mechanism" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Mechanism")
         "+ %t %?\n" :prepend t)
	("visn" "Transmission" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Transmission")
         "+ %t %?\n" :prepend t)
	("visp" "Physical Distancing / Face Masks" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Physical Distancing / Face Masks")
         "+ %t %?\n" :prepend t)
	("visr" "Risk" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Risk Assessment")
         "+ %t %?\n" :prepend t)
	("vist" "Track and Trace" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Track and Trace")
         "+ %t %?\n" :prepend t)
	("visv" "Evolutionary Genetics" item (file+olp "~/org/coronavirus.org" "Information" "Science" "Evolutionary Genetics"))
	("vid" "Data" item (file+olp "~/org/coronavirus.org" "Information" "Data")
         "+ %t %?\n")
	("vitc" "Cycling" item (file+olp "~/org/coronavirus.org" "Information" "Traffic" "Cycling")
         "+ %t %?\n")
	("vitr" "Roads" item (file+olp "~/org/coronavirus.org" "Information" "Traffic" "Roads")
         "+ %t %?\n")
	("viw" "Work" item (file+olp "~/org/coronavirus.org" "Information" "Work")
         "+ %t %?\n")
	("va" "Activities for Isla") ;; Isla
	("vae" "Educational" item (file+olp "~/org/coronavirus.org" "Activities for Isla" "Educational")
         "+ %t %?\n" :prepend t)
	("vax" "Exercise" item (file+olp "~/org/coronavirus.org" "Activities for Isla" "Exercise")
         "+ %t %?\n" :prepend t)
	("vaf" "Fun" item (file+olp "~/org/coronavirus.org" "Activities for Isla" "Fun")
         "+ %t %?\n" :prepend t)
	("vh" "Humour") ;; Humour
	("vhg" "Graphics" item (file+olp "~/org/coronavirus.org" "Humour" "Graphics")
         "+ %t %?\n" :prepend t)
	("vhx" "XKCD" item (file+olp "~/org/coronavirus.org" "Humour" "XKCD")
         "+ %t %?\n" :prepend t)))
