;;; Org-capture
;;; https://orgmode.org/manual/Capture.html#Capture)
;;;
;;; Also configured to use org-webcapture Firefox add-on (https://gitlab.com/Titan-C/org-webcapture)
;; (require 'org-protocol)
(use-package org-capture
  :ensure nil
  :after org-gtd
  :config
  (setq org-default-notes-file (concat org-directory "/notes.org"))
  (setq org-capture-templates
	'(
	  ;; Email
	  ("E" "Email"
	   entry(file+headline ,(concat org-gtd-directory "emails.org") "Emails")
	   "* TODO [#A] Reply: %a" :immediate-finish t)
	  ;; Agenda
	  ("a" "Agenda")
	  ("au" "Things to get Done" entry (file+olp "~/org/agenda.org" "Things to get Done")
	   "** TODO %U %?\n" :prepend t)
	  ("an" "Not so Urgent" entry (file+olp "~/org/agenda.org" "Not so Urgent")
	   "** TODO %U %?\n" :prepend t)
	  ("ac" "Computing" entry (file+olp "~/org/agenda.org" "Computing")
	   "** TODO %U %?\n" :prepend t)
	  ("aw" "Weekly" entry (file+olp "~/org/agenda.org" "Weekly")
	   "** TODO %U %?\n" :prepend t)
	  ("af" "Fortnightly" entry (file+olp "~/org/agenda.org" "Fortnightly")
	   "** TODO %U %?\n" :prepend t)
	  ("am" "Monthly" entry (file+olp "~/org/agenda.org" "Monthly")
	   "** TODO %U %?\n" :prepend t)
	  ("ac" "Annually" entry (file+olp "~/org/agenda.org" "Annually")
	   "** TODO %U %?\n" :prepend t)
	  ;; Bibliography
	  ;; ("b" "Bibliography" item (file+olp "~/org/references.bib")
	  ;;  "%?\n" :prepend t)
	  ;; Computing
	  ("c" "Computing")
	  ("ce" "Emacs" entry (file+olp "~/org/computing.org" "Emacs")
	   "* TODO %t %?\n" :prepend t)
	  ("cl" "Laptop" entry (file+olp "~/org/computing.org" "Laptop")
	   "* TODO %t %?\n" :prepend t)
	  ("cd" "Desktop" entry (file+olp "~/org/computing.org" "Desktop")
	   "* TODO %t %?\n" :prepend t)
	  ("cn" "Networking/Routers" entry (file+olp "~/org/computing.org" "Networking/Routers")
	   "* TODO %t %?\n" :prepend t)
	  ("cq" "Printers" entry (file+olp "~/org/computing.org" "Printers")
	   "* TODO %t %?\n" :prepend t)
	  ("cr" "RaspberryPi" entry (file+olp "~/org/computing.org" "Raspberry Pi")
	   "* TODO %t %?\n" :prepend t)
	  ("cm" "AirQuality Monitor" entry (file+olp "~/org/computing.org" "AirQuality Monitor")
	   "* TODO %t %?\n" :prepend t)
	  ("ca" "Android" entry (file+olp "~/org/computing.org" "Android")
	   "* TODO %t %?\n" :prepend t)
	  ("cp" "Programming") ;; Programming
	  ("cpb" "" entry (file+olp "~/org/computing.org" "Programming" "Bash")
	   "* TODO %t %?\n" :prepend t)
	  ("cpe" "MongoDB" entry (file+olp "~/org/computing.org" "Programming" "MongoDB")
	   "* TODO %t %?\n" :prepend t)
	  ("cpp" "Python" entry (file+olp "~/org/computing.org" "Programming" "Python")
	   "* TODO %t %?\n" :prepend t)
	  ("cpg" "Git" entry (file+olp "~/org/computing.org" "Programming" "Git")
	   "* TODO %t %?\n" :prepend t)
	  ("cpl" "LaTeX" entry (file+olp "~/org/computing.org" "Programming" "LaTeX")
	   "* TODO %t %?\n" :prepend t)
	  ("cpr" "R" entry (file+olp "~/org/computing.org" "Programming" "R")
	   "* TODO %t %?\n" :prepend t)
	  ("cv" "VPS" entry (file+olp "~/org/computing.org" "VPS")
	   "* TODO %t %?\n" :prepend t)
	  ;; Jobs
	  ("j" "Jobs")
	  ("jp" "Domestication" entry (file+olp "~/org/jobs.org" "Places to Look")
	   "+ %t %?\n" :prepend t)
	  ("jps" "Sheffield" entry (file+olp "~/org/jobs.org" "Places to Look" "Sheffield")
	   "+ %t %?\n" :prepend t)
	  ("js" "Specifics" entry (file+olp "~/org/jobs.org" "Specifics")
	   "* %t %?\n" :prepend t)
	  ;; Cats
	  ("z" "Cats")
	  ("zd" "Domestication" entry (file+olp "~/org/cats.org" "Domestication")
	   "+ %t %?\n" :prepend t)
	  ("zg" "Genetics" entry (file+olp "~/org/cats.org" "Genetics")
	   "+ %t %?\n" :prepend t)
	  ;; Drugs
	  ("d" "Drugs")
	  ("dr" "Research")
	  ("drc" "Cannabis" item (file+olp "~/org/drugs.org" "Research" "Cannabis")
	   "+ %?\n" :prepend t)
	  ("drd" "DMT" item (file+olp "~/org/drugs.org" "Research" "DMT")
	   "+ %?\n" :prepend t)
	  ("drl" "LSD" item (file+olp "~/org/drugs.org" "Research" "LSD")
	   "+ %?\n" :prepend t)
	  ("drm" "MDMA" item (file+olp "~/org/drugs.org" "Research" "MDMA")
	   "+ %?\n" :prepend t)
	  ("drp" "Psilocybin" item (file+olp "~/org/drugs.org" "Research" "Psilocybin")
	   "+ %?\n" :prepend t)
	  ("db" "Books" item (file+olp "~/org/drugs.org" "Books")
	   "+ %?\n" :prepend t)
	  ("da" "Articles")
	  ("dam" "Mushrooms" item (file+olp "~/org/drugs.org" "Articles" "Mushrooms")
	   "+ %?\n" :prepend t)
	  ("dac" "Culture" item (file+olp "~/org/drugs.org" "Articles" "Culture")
	   "+ %?\n" :prepend t)
	  ("dag" "General" item (file+olp "~/org/drugs.org" "Articles" "General")
	   "+ %?\n" :prepend t)
	  ("di" "Interviews" item (file+olp "~/org/drugs.org" "Interviews")
	   "+ %?\n" :prepend t)
	  ("dg" "Blogs / Podcasts /Videos")
	  ("dgd" "DMT" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "DMT")
	   "+ %?\n" :prepend t)
	  ("dgm" "Mushrooms" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "Mushrooms")
	   "+ %?\n" :prepend t)
	  ("dgp" "Mushrooms" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "Psychedelics")
	   "+ %?\n" :prepend t)
	  ("dgz" "Misc" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "Misc")
	   "+ %?\n" :prepend t)
	  ("dt" "Terrence McKenna" item (file+olp "~/org/drugs.org" "Terrence McKenna")
	   "+ %?\n" :prepend t)
	  ;; Exercise
	  ("e" "Exercise")
	  ("er" "Logging a run" table-line (file "~/org/training/log/running_2024.org")
	   "| %U | %? | km | min + s | | |" :prepend t)
	  ("ec" "Logging a cycle" table-line (file "~/org/training/log/cycling.org")
	   "| %U | %? | km | min + s | | |" :prepend t)
	  ("eh" "Logging a hike" table-line (file "~/org/training/log/hiking.org")
	   "| %U | %? | km | m | min + s| |" :prepend t)
	  ("ep" "Logging Pilates" table-line (file "~/org/training/log/pilates_2024.org")
	   "| %U | %? | |" :prepend t)
	  ("em" "Weight & Waist/Hip" table-line (file "~/org/training/log/metrics_weight.org")
	   "| %U | %? | | | |" :prepend t)
	  ("es" "Steps" table-line (file "~/org/training/log/metrics_steps.org")
	   "| %t | %? |" :prepend t)
	  ("eb" "Blood" table-line (file "~/org/training/log/metrics_blood.org")
	   "| %U | %? | | | | | |" :prepend t)
	  ("et" "Training Resources") ;; Training Resources
	  ("etc" "Training Resources (Climbing)")
	  ("etcf" "Fingerboarding" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Fingerboarding")
	   "+ %?\n" :prepend t)
	  ("etcl" "Lattice" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Lattice")
	   "+ %?\n" :prepend t)
	  ("etcd" "Dave MacLeod" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Dave Macleod")
	   "+ %?\n" :prepend t)
	  ("etch" "Hoopers Beta" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Hoopers Beta")
	   "+ %?\n" :prepend t)
	  ("etcm" "Miscellaneous" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Miscellaneous")
	   "+ %?\n" :prepend t)
	  ("etcs" "Shauna Coxy" item (file+olp "~/org/training/training.org" "Resources" "Climbing" "Shauna Coxy")
	   "+ %?\n" :prepend t)
	  ("etr" "Running" entry (file+olp "~/org/training/training.org" "Resources" "Running")
	   "+ %t %?\n" :prepend t)
	  ("etl" "Calisthenics")
	  ("etlg" "General" entry (file+olp "~/org/training/training.org" "Resources" "Calisthenics" "General")
	   "+ %t %?\n" :prepend t)
	  ("etlr" "Recommended Routine" entry (file+olp "~/org/training/training.org" "Resources" "Calisthenics" "Recommended
Routine")
	   "+ %t %?\n" :prepend t)
	  ("etls" "Stretching" entry (file+olp "~/org/training/training.org" "Resources" "Calisthenics" "Stretching")
	   "+ %t %?\n" :prepend t)
	  ("ets" "Swimming" entry (file+olp "~/org/training/training.org" "Resources" "Swimming")
	   "+ %t %?\n" :prepend t)
	  ("etx" "Research" entry (file+olp "~/org/training/training.org" "Resources" "Research")
	   "+ %t %?\n" :prepend t)
	  ("eta" "Apps" entry (file+olp "~/org/training/training.org" "Resources" "Apps")
	   "+ %t %?\n" :prepend t)
	  ("etd" "Apps" entry (file+olp "~/org/training/training.org" "Resources" "Summarising Data")
	   "+ %t %?\n" :prepend t)
	  ;; Cooking
	  ("f" "Food & Drink")
	  ("fc" "Chinese")
	  ("fcs" "Starters" item (file+olp "~/org/food_drink.org" "Chinese" "Starters")
	   "+ %?\n" :prepend t)
	  ("fcr" "Rice" item (file+olp "~/org/food_drink.org" "Chinese" "Rice")
	   "+ %?\n" :prepend t)
	  ("fcm" "Main" item (file+olp "~/org/food_drink.org" "Chinese" "Main")
	   "+ %?\n" :prepend t)
	  ("fcn" "Noodles" item (file+olp "~/org/food_drink.org" "Chinese" "Noodles")
	   "+ %?\n" :prepend t)
	  ("fu" "Indian")
	  ("fus" "Starters" item (file+olp "~/org/food_drink.org" "Indian" "Starters")
	   "+ %?\n" :prepend t)
	  ("fuc" "Curries" item (file+olp "~/org/food_drink.org" "Indian" "Curries")
	   "+ %?\n" :prepend t)
	  ("fub" "Breads" item (file+olp "~/org/food_drink.org" "Indian" "Breads")
	   "+ %?\n" :prepend t)
	  ("fi" "Italian")
	  ("fip" "Pasta" item (file+olp "~/org/food_drink.org" "Italian" "Pasta Dishes")
	   "+ %?\n" :prepend t)
	  ("fiz" "Pizza" item (file+olp "~/org/food_drink.org" "Italian" "Pizza")
	   "+ %?\n" :prepend t)
	  ("fs" "Spanish" item (file+olp "~/org/food_drink.org" "Italian" "Pasta")
	   "+ %?\n" :prepend t)
	  ("fv" "Vegetarian" item (file+olp "~/org/food_drink.org" "Vegetarian")
	   "+ %?\n" :prepend t)
	  ("fw" "Web sites" item (file+olp "~/org/food_drink.org" "Web Sites")
	   "+ %?\n" :prepend t)
	  ("fb" "Books" item (file+olp "~/org/food_drink.org" "Books")
	   "+ %?\n" :prepend t)
	  ;; Isla
	  ("I" "Activities for Isla")
	  ("Ie" "Educational" item (file+olp "~/org/isla.org" "Educational")
	   "+ %t %?\n" :prepend t)
	  ("Ix" "Exercise" item (file+olp "~/org/isla.org" "Exercise")
	   "+ %t %?\n" :prepend t)
	  ("If" "Fun" item (file+olp "~/org/isla.org" "Fun")
	   "+ %t %?\n" :prepend t)
	  ("Ig" "Gardening" item (file+olp "~/org/isla.org" "Gardening")
	   "+ %t %?\n" :prepend t)
	  ;; Paula
	  ("p" "Paula")
	  ("pa" "Anger" item (file+olp "~/org/paula.org" "Anger")
	   "+ %U %?\n" :prepend t)
	  ("pf" "Food" item (file+olp "~/org/paula.org" "Food")
	   "+ %U %?\n" :prepend t)
	  ("ph" "Help" item (file+olp "~/org/paula.org" "Help")
	   "+ %U %?\n" :prepend t)
	  ("pl" "Listening" item (file+olp "~/org/paula.org" "Not Listening")
	   "+ %U %?\n" :prepend t)
	  ("pt" "Tidying" item (file+olp "~/org/paula.org" "Tidying")
	   "+ %U %?\n" :prepend t)
	  ;; Reading
	  ("r" "Reading")
	  ("rb" "Books" entry (file+olp "~/org/reading.org" "Books")
	   "* TODO %?\n" :prepend t)
	  ("re" "Economics" entry (file+olp "~/org/reading.org" "Economics")
	   "* TODO %?\n" :prepend t)
	  ("rg" "Genetics" entry (file+olp "~/org/reading.org" "Genetics")
	   "* TODO %?\n" :prepend t)
	  ("rs" "Statistics")
	  ("rsd" "Data/Machine Learning/AI" entry (file+olp "~/org/reading.org" "Statistics" "Data/Machine Learning/AI")
	   "* TODO %?\n" :prepend t)
	  ("ri" "Internet")
	  ("rid" "Data/Machine Learning/AI" entry (file+olp "~/org/reading.org" "Internet" "Social Media")
	   "* TODO %?\n" :prepend t)
	  ("rm" "Miscellany" entry (file+olp "~/org/reading.org" "Miscellany")
	   "* TODO %?\n" :prepend t)
	  ;; ("s" "Org-Roam Notes" entry (file "~/work/org-roam/20220206201656-notes.org")
	  ;;  "* %U %?\n" :prepend t)
	  ;; TODO
	  ("t" "Stuff ToDo in my Life")
	  ("th" "House Tasks" entry (file+olp "~/org/todo.org" "House")
	   "* TODO %t %?\n" :prepend t)
	  ("tg" "Gardening" entry (file+olp "~/org/todo.org" "Garden")
	   "* TODO %t %?\n" :prepend t)
	  ("tv" "Campervan" entry (file+olp "~/org/todo.org" "Campervan")
	   "* TODO %t %?\n" :prepend t)
	  ("tc" "Car" entry (file+olp "~/org/todo.org" "Car")
	   "* TODO %t %?\n" :prepend t)
	  ("tg" "Bike" entry (file+olp "~/org/todo.org" "Bike")
	   "* TODO %t %?\n" :prepend t)
	  ("ts" "Stuff to Sell" entry (file+olp "~/org/todo.org" "Stuff To Sell")
	   "* TODO %t %?\n" :prepend t)
	  ;; Coronavirus
	  ("v" "Coronavirus")
	  ("va" "Air Quality" item (file+olp "~/org/coronavirus.org" "Air Quality")
	   "+ %t %?\n" :prepend t)
	  ("vc" "Collections/Streams")
	  ("vca" "The Atlantic" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Atlantic")
	   "+ %t %?\n" :prepend t)
	  ("vcb" "BMJ" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "BMJ")
	   "+ %t %?\n" :prepend t)
	  ("vcd" "David Spiegelhalter" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "David Spiegelhalter")
	   "+ %t %?\n" :prepend t)
	  ("vcg" "The Guardian" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Guardian")
	   "+ %t %?\n" :prepend t)
	  ("vcl" "The Lancet" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Lancet")
	   "+ %t %?\n" :prepend t)
	  ("vcn" "New Scientist" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "New Scientist")
	   "+ %t %?\n" :prepend t)
	  ("vco" "ONS" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "ONS")
	   "+ %t %?\n" :prepend t)
	  ("vcs" "Significance" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "Significance magazine")
	   "+ %t %?\n" :prepend t)
	  ("vcw" "Wired" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "Wired")
	   "+ %t %?\n" :prepend t)
	  ("vcx" "BioRxiv/MedRxiv" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "BioRxiv/MedRxiv")
	   "+ %t %?\n" :prepend t)
	  ("vd" "Data" item (file+olp "~/org/coronavirus.org" "Data")
	   "+ %t %?\n")
	  ("ve" "Evolutionary Genetics" item (file+olp "~/org/coronavirus.org" "Evolutionary Genetics"))
	  ("vg" "Genetics" item (file+olp "~/org/coronavirus.org" "Genetics"))
	  ("vh" "Herd Immunity" item (file+olp "~/org/coronavirus.org" "Herd Immunity")
	   "+ %t %?\n")
	  ("vi" "Immunity / Testing / Vaccine / Treatment")
	  ("vie" "ENSEMBLE2" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "ENSEMBLE 2")
	   "+ %t %?\n" :prepend t)
	  ("vii" "Immunity" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "Immunity")
	   "+ %t %?\n" :prepend t)
	  ("vis" "Testing" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "Testing")
	   "+ %t %?\n" :prepend t)
	  ("viv" "Vaccine" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "Vaccine")
	   "+ %t %?\n" :prepend t)
	  ("vit" "Treatment" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Treatment" "Treatment")
	   "+ %t %?\n" :prepend t)
	  ("ve" "Independent SAGE" item (file+olp "~/org/coronavirus.org" "Independent SAGE")
	   "+ %t %?\n" :prepend t)
	  ("vl" "Long Term Outcomes" item (file+olp "~/org/coronavirus.org" "Long Term Outcomes")
	   "+ %t %?\n" :prepend t)
	  ("vh" "Mechanism" item (file+olp "~/org/coronavirus.org" "Mechanism")
	   "+ %t %?\n" :prepend t)
	  ("vhs" "Susceptibility" item (file+olp "~/org/coronavirus.org" "Mechanism" "Susceptibility")
	   "+ %t %?\n" :prepend t)
	  ("vm" "Miscellaneous" item (file+olp "~/org/coronavirus.org" "Miscellaneous")
	   "+ %t %?\n" :prepend t)
	  ("vn" "Non-Pharmaceutical Interventions")
	  ("vo" "Mortality Rates" item (file+olp "~/org/coronavirus.org" "Mortality Rates")
	   "+ %t %?\n" :prepend t)
	  ("vp" "Molecular Biology" item (file+olp "~/org/coronavirus.org" "Molecular Biology")
	   "+ %t %?\n" :prepend t)
	  ("vr" "Risk" item (file+olp "~/org/coronavirus.org" "Risk Assessment")
	   "+ %t %?\n" :prepend t)
	  ("vs" "SAGE" item (file+olp "~/org/coronavirus.org" "SAGE")
	   "+ %t %?\n" :prepend t)
	  ("vt" "Track and Trace" item (file+olp "~/org/coronavirus.org" "Track and Trace")
	   "+ %t %?\n" :prepend t)
	  ("vu" "Transmission" item (file+olp "~/org/coronavirus.org" "Transmission")
	   "+ %t %?\n" :prepend t)
	  ("vnd" "Physical Distancing" item (file+olp "~/org/coronavirus.org" "Transmission" "Physical Distancing")
	   "+ %t %?\n" :prepend t)
	  ("vnm" "Face Masks" item (file+olp "~/org/coronavirus.org" "Transmission" "Face Masks")
	   "+ %t %?\n" :prepend t)
	  ("vup" "Prevalence" item (file+olp "~/org/coronavirus.org" "Transmission" "Prevalence")
	   "+ %t %?\n" :prepend t)
	  ("vx" "Traffic")
	  ("vxc" "Cycling" item (file+olp "~/org/coronavirus.org" "Traffic" "Cycling")
	   "+ %t %?\n")
	  ("vxr" "Roads" item (file+olp "~/org/coronavirus.org" "Traffic" "Roads")
	   "+ %t %?\n")
	  ("vw" "Work" item (file+olp "~/org/coronavirus.org" "Work")
	   "+ %t %?\n")
	  ("vy" "Humour") ;; Humour
	  ("vyg" "Graphics" item (file+olp "~/org/coronavirus.org" "Humour" "Graphics")
	   "+ %t %?\n" :prepend t)
	  ("vyx" "XKCD" item (file+olp "~/org/coronavirus.org" "Humour" "XKCD")
	   "+ %t %?\n" :prepend t)
	  ("vz" "Non-Science")
	  ("vzs" "Sheffield" item (file+olp "~/org/coronavirus.org" "Non-Science" "Sheffield")
	   "+ %t %?\n" :prepend t)
	  ;; Work
	  ("w" "Work")
	  ("wj" "Reproducibilitea" entry (file+olp "~/org/gtd/reproducibilitea.org" "Reproducibilitea")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wo" "OSC" entry (file+olp "~/org/gtd/osc.org" "Open Scholarship Sheffield")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wR" "Sheffield R" entry (file+olp "~/org/gtd/sheffieldr.org" "SheffieldR")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wr" "RSE" entry (file+olp "~/org/gtd/rse.org" "RSE")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wt" "TopoStats" entry (file+olp "~/org/gtd/topostats.org" "TopoStats")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wc" "Clarity" entry (file+olp "~/org/gtd/clarity.org" "Clarity")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wC" "Carpentries Courses" entry (file+olp "~/org/gtd/carpentries.org" "Courses")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wp" "PGFinder" entry (file+olp "~/org/gtd/pgfinder.org" "PGFinder")
	   "** TODO %U %?\n %a" :prepend t)
	  )))
