#+TITLE: Literate Emacs Configuration
#+PROPERTY: header-args :tangle ./init.el
#+OPTIONS: toc:2 num:nil
#+SETUPFILE: ./theme-readtheorg.setup

#+NAME: code-search-options
#+BEGIN_SRC org :tangle no
{{{enable-search}}}
{{{set-search-limit(30)}}}
#+END_SRC

* What

This is my Emacs config, there are many like it but this one is mine.

I've used Emacs for getting on 25 years and am slightly ashamed to say that I still haven't sat down and properly "learnt"
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html][Emacs Lisp]] (one day I'll make time!). I have however learnt enough to cobble together my own custom configuration which
is based, in no small part, on countless others who have gracefully shared examples of their configuration and patiently
answered questions.

* Why?

I found my configuration was growing as I have a habit of throwing all sorts into it then one day, after updating
packages, I found that [[sec:lsp-mode][LSP-mode]] was no longer working as it had been. At the same time I had some issues using [[sec:magit][Magit]] and
[[sec:transient][Transient]]. Whilst I fixed these it prompted me to pull my thumb out and re-write my configuration [[https://leanpub.com/lit-config/read][literately]] and have
used it as an opportunity to actually start learning Emacs Lisp a little (I find tutorials and walk-throughs quite
abstract and like to have a use-case of my own to help me learn aspects of computing).

I keep extensive [[https://org-roam.nshephard.dev][Org-roam]] notes and have separate sections on [[https://org-roam.nshephard.dev/#754f25a5-3429-4504-8a17-4efea1568eba][Emacs]], [[https://org-roam.nshephard.dev/#220d7ba9-d30e-4149-a25b-03796e098b0d][Magit]] and [[https://org-roam.nshephard.dev/#169b9c5f-df34-46ab-b64f-8ee98946ee69][Org-mode]], but have taken the opportunity
to augment this configuration not just with explanations of the configuration options themselves but a little more on
each package and how it works (this will grow over time as I return to each package and configure it properly.).

There are a lot of excellent resources to help guide Emacs users through configuring their browser to their own needs.

| Resource                                     | Access in Emacs with...                     |
|----------------------------------------------+---------------------------------------------|
| [[https://www.gnu.org/software/emacs/tour/][Emacs Tutorial]]                               | ~C-h t~                                     |
| [[https://www.gnu.org/software/emacs/manual/][Emacs Manual]]                                 | ~C-h r~                                     |
| Info pages for installed packages            | ~C-h i~                                     |
| Manuals for packages                         | ~C-h R~ and search for package              |
| [[https://www.gnu.org/software/emacs/manual/html_node/eintr/index.html][An Introduction to Programming in Emacs Lisp]] |                                             |
| [[https://www.gnu.org/software/emacs/documentation.html][Emacs Lisp Reference]]
| [[https://www.masteringemacs.org/][Mastering Emacs]]                              | N/A -website and book from Mickey Peterson. |

Feedback is welcome, please create an [[https://codeberg.org/slackline/emacs/issues][issue]] on the Codeberg repository and I'll pick it up.

* ToDo

Tasks I'm yet to complete in re-writing...

- [ ] Switch to using ~:custom~ over ~:config~ as described [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][here]].
- [ ] Test the ~compilation-finish-function~ hook will kill compilation buffers.
- [ ] Ensure ~(desc . command)~ is used for all custom key-bindings so that they are all shown by ~which-key~




* On Configuration with use-package
<<sec:conf-use-package>>

Currently I use the built-in [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][use-package]] and in re-writing this document have sought to adhere to the advice on [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using
use-package the right way]]. The following table is constructed from the archived [[https://github.com/jwiegley/use-package][use-package README.md]] and the [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][Emacs
docs : use-package]] page since it is now a core component of Emacs. use-package provides the [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html#Basic-Concepts][~use-package~ macro]] which
simplifies configuration.

Packages are either loaded immediately, when the package is first used (via autoloading) or can be deferred using the
~:defer~ keyword. Some autoloading can be done in response to /triggers/ of certain events (i.e. ~:hook~).

| Option         | Description                                                                                                                                        | Example                                                                                                                                                                                |
|----------------+----------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [[https://github.com/jwiegley/use-package#getting-started][~:init~]]        | Execute code /before/ a package is loaded                                                                                                          | ~:init (setq foo-variable t)~                                                                                                                                                          |
| ~:defer~       | Delay loading of package. Can be ~t~ but is rarely used, typically an integer /n/ is specified to load the package after that period of idle time. | ~:defer t~ / ~:defer 30~                                                                                                                                                               |
| ~:after~       | Load after another package has been loaded.                                                                                                        | ~:after org~                                                                                                                                                                           |
| [[https://github.com/jwiegley/use-package#key-binding][~:bind~]]        | Key-bindings, plain or with a cons (~(desc . command)~)                                                                                            | ~:bind (("C-c k" . keychain-refresh-environment) ("C-c o h" . osm-home))~                                                                                                              |
| [[https://github.com/jwiegley/use-package#key-binding][~:bind~]]        | With a cons the description will be shown why ~which-key~                                                                                          | ~:bind ("C-c k" ("Refresh keychain" . keychain-refresh-environment) "C-c o h" ("Open OSM at home" . osm-home))~                                                                        |
| [[https://github.com/jwiegley/use-package#binding-to-keymaps][~:bind-keymap~]] | Binds a keymap to the given key chord.                                                                                                             | ~:bind ("s-p" . projectile-command-map))~ / ~:bind ("s-p" ("Projectile" . projectile-command-map))~ (untested)                                                                         |
| ~:map~         | Within a ~:bind~ you can provide the mapping and modify key maps.                                                                                  | ~:bind (:map projectile-command-map ("s-p p" . projectile-switch-project))~ / ~:bind (:map projectile-command-map ("s-p p" ("Switch project" . projectile-switch-project))~ (untested) |
| [[https://github.com/jwiegley/use-package#getting-started][~:config~]]      | Executes code /after/ a package is loaded. Note that using this forces loading of the package.                                                     |                                                                                                                                                                                        |
| ~:commands~    | Creates autoloads for commands, deferring loading modules until they are used.                                                                     |                                                                                                                                                                                        |
| ~:custom~      | Alternative option for customising package, preferable over ~:config~.                                                                             |                                                                                                                                                                                        |
| [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html#Conditional-loading][~:if~]]          | Conditionally load packages.                                                                                                                       |                                                                                                                                                                                        |
| ~:hook~        | Define hooks associated with the package.                                                                                                          |                                                                                                                                                                                        |
| ~:ensure~      | Makes sure a package is loaded (eventually). Should be avoided with built-in packages as it may force downloading of newer version.                |                                                                                                                                                                                        |


Using either ~:config~ or ~:init~ will force a package to be loaded, regardless of whether you use ~:defer~ to delay
loading. Instead the alternative ~:custom~ and ~:hook~ commands should be used.

** ~:custom~

Avoids the need to ~setq~ within ~:config~ / ~:init~ sections

* Initial Setup

Library headers have specific [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][conventions]] which we setup for the ~init.el~ and all child documents. There is a header
and [[sec:footer][footer]].

#+NAME: code-init-header
#+BEGIN_SRC emacs-lisp :tangle init.el
  ;;; init.el --- slackline's Emacs configuration -*- lexical-binding: t -*-
  ;; Author: N Shephard <nshephard@protonmail.com>
  ;; Keywords: configuration
  ;; URL: https://www.codeberg.org/slackline/emacs
  ;;; Commentary:
  ;; A literate and reproducible Emacs configuration

  ;;; Code:

#+END_SRC


** Package Manager Setup

Enable packages ~package-enable-at-startup~ via an ~early-init.el~ because "/If non-nil, packages are
made available before reading the init file (but after reading the early init file)./" and we want to load
packages. Need to check how this behaves with ~:defer~ and ~:after~ options which are set on a per-package basis. I
found setting this to ~nil~ caused errors on trying to load and configure packages.

#+NAME: code-early-init
#+BEGIN_SRC emacs-lisp :tangle early-init.el
;;; early-init.el --- Emacs early init file -*- lexical-binding: t; -*-
;;; Commentary:
;; Runs before init.el is loaded.

;;; Code:

;; If using straight.el then disable package.el to prevent all packages being loaded on startup
(setq package-enable-at-startup t)

(provide 'early-init)
;;; early-init.el ends here

#+END_SRC


The ~exec-path~ is important as it defines where programs are searched for when executing them, it is used by
~gnu-elpa-keyring-update~ to update certain things (what those are I'm not currently sure but without this first
~use-package gnu-elpa-keyring-update~ fails with ~Cannot open find file: No such file or directory,
exec-path-from-shell~).

#+NAME: code-exec-path
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package exec-path-from-shell
  :ensure t
  :custom
  (when (daemonp) (exec-path-from-shell-initialize))
  (exec-path-from-shell-copy-env "SSH_AGENT_PID")
  (exec-path-from-shell-copy-env "SSH_AGENT_SOCK")
  (exec-path (append '("~/bin"
                          "~/.local/bin"
                          "~/.cargo/bin/"
                          "~/.node/bin/"
                          )
			exec-path)))
#+END_SRC

** use-package

We now configure [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][use-package]].

Initially I used to use the example [[https://ianyepan.github.io/posts/setting-up-use-package/][here]] which made sure ~use-package~ was always installed, but since the ~use-package~
is now part of core this is no longer required. The configuration options remain though on the off-chance I have to use
a system with outdated versions of Emacs

*NB* the following code block is /not/ tangled to configuration.

#+NAME: code-use-package-install
#+BEGIN_SRC emacs-lisp :tangle no
  (require 'package)
  (add-to-list 'package-archives '("gnu"   . "https://elpa.gnu.org/packages/"))
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+END_SRC

We configure ~use-package~ below, not all of the values that are set (via ~setq~) are ~use-package~ variables but since
they pertain to downloading and installing packages I keep them here. Because there can be issues with GPG keys when
they are updated we first update the ~gnu-elpa-keyring~ using [[https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html][gnu-elpa-keyring-update]], although this itself requires

Whilst I tend to explicitly state ~:ensure t~ for almost all packages here I also set ~use-package-always-ensure t~ so
that if I forget it should still be installed.

#+NAME: code-use-package-config
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package gnu-elpa-keyring-update
  :ensure t)

(use-package use-package
  :config
  (setq use-package-always-ensure t)
  (setq use-package-expand-minimally t)
  ;; On some systems we have problems communicating with ELPA (https://emacs.stackexchange.com/a/62210)
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
  ;; Adding repositories along with priority https://emacs.stackexchange.com/a/2989/10100
  (setq package-archives
      '(("GNU ELPA"	. "https://elpa.gnu.org/packages/")
        ("NonGNU ELPA"  . "https://elpa.nongnu.org/nongnu/")
        ("MELPA Stable" . "https://stable.melpa.org/packages/")
        ("MELPA"	. "https://melpa.org/packages/")
        ("jcs elpa" . "https://jcs-emacs.github.io/jcs-elpa/packages/"))
      package-archive-priorities
      '(("MELPA" . 10)
        ("GNU ELPA"	. 5)
        ("NonGNU ELPA"	. 5)
        ("MELPA Stable"	. 3)
        ("jcs elpa" . 0)
        )))

#+END_SRC

*** Emacs Package Archives

There are multiple sources of Emacs packages, including those who self-host serves such as ~jcs elpa~ listed below.

+ [[https://melpa.org/][MELPA]] for the latest versions of packages and [[https://stable.melpa.org/packages/][MELPA Stable]] when you don't want bleeding edge.
+ [[https://elpa.gnu.org/packages/][GNU ELPA]] for pure Free Open Source Software
+ [[https://elpa.nongnu.org/nongnu/][NonGNU ELPA Packages]] for not quite Free Open Source Software
+ [[https://jcs-emacs.github.io/jcs-elpa/packages/][jcs elpa]]

Because the same package can be hosted across these repositories, sometimes the same version, sometimes newer, it is
useful to be able to set the ~package-archive-priorities~ where each is assigned a priority value.

** Byte Compiling
<<sec:byte-compiling>>

Byte-compilation takes your ASCII plain-text configuration files saved in ~.el~ and turns them into computer code
(~.elc~) which can be loaded quicker. There are a couple of options available ~auto-compile~ and ~compile-angel~ being
two that I have explored before. I have a hook to [[https://emacs.stackexchange.com/a/110][hide the compilation buffer]] on completion of compiling as I got fed up
of these being thrust into the foreground. I don't currently use either of these but keep them hanging around in case I
change my mind so I don't have to dig through my Git history to find the configuration.

*** ~auto-compile~
<<sec:auto-compile>>

Not currently tangled.

#+NAME: code-auto-compile
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package auto-compile
    :custom
    (auto-compile-on-load-mode t)
    (auto-compile-on-save-mode t)
    (load-prefer-newer t)
    (native-comp-jit-compilation t)
    :hook
    (compilation-finish-functions (lambda (buf strg) (kill-buffer buf))))
#+END_SRC

*** ~compile-angle~

The [[https://github.com/jamescherti/compile-angel.el][~compile-angel~]] package seeks to improve on ~auto-compile~.

Not currently tangled.

#+NAME: code-compile-angel
#+BEGIN_SRC emacs-lisp :tangle no
(use-package compile-angel
  :ensure t
  :demand t
  :custom
  (compile-angel-verbose nil)
  :config
  (compile-angel-on-load-mode)
  (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode))
#+END_SRC

* Emacs Global Configuration

Before loading any packages we configure Emacs itself. This uses ~:config~ as we /always/ want to load and use this
configuration and we don't need to ~:defer~.

I typically use Emacs in its own GUI window but disable a lot of the graphical components such as scroll and tool
bars.

** Emacs
<<sec:emacs>>

+ [[http://yummymelon.com/devnull/til-imenu.html][imenu]]
+ [[https://github.com/rexim/org-cliplink][org-cliplink]]
+ [[https://emacs.stackexchange.com/a/110][compilation-finish-functions]]
+ [[https://emacs.stackexchange.com/a/40773/10100][delete-trailing-whitespace]]

#+NAME: code-emacs-config
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package emacs
    :custom
    ;; Add local lisp for miscellaneous things
    (add-to-list 'load-path "~/.config/emacs/elpa/") ; Local LISP
    (confirm-kill-processes nil) ; Stop confirming the killing of processes
    (custom-file "~/.config/emacs/custom.el")
    (dired-dwim-target t) ; move file to other pane as default destination
    (enable-recursive-minibuffers t) ; Vertico - open new minibuffers from inside a minibuffer
    (global-auto-revert-non-file-buffers t) ; Update non-file buffers (Dired) when disk changes
    (global-goto-address-mode t)
    (global-visual-line-mode t) ; Visual line wrap
    (history-length 1000) ; Mini-buffer history
    (inhibit-startup-message t) ; Hide the startup message
    (inhibit-startup-screen t) ; Disable startup screen
    (initial-scratch-message "") ; Make *scratch* buffer blank
    (initial-scratch-message nil)
    (lisp-indent-offset 2)
    (mode-line-compact t)
    (package-install-upgrade-built-in t) ; Upgrade built-in packages
    (pixel-scroll-precision-mode t)
    (ring-bell-function 'ignore)  ; Disable bell sound
    (undo-limit 320000) ; Increase the undo history limits
    (undo-strong-limit 640000)
    (use-dialog-box nil) ; No dialog pop-ups
    (vc-handled-backends '(Git))
    (vc-follow-symlinks t) ; open source of symlink maintain vc (https://stackoverflow.com/a/30900018/1444043)
    (winner-mode t) ; toggling window configuration
    (set-cursor-color "#0AFF00") ; Bright Green (stands out better)
    ;; (set-cursor-color "#62088A") ; Dark purple (not very visible)
    ;; (browse-url-browser-function 'eww-browse-url) ; Set eww as the default browser
    ;; https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
    (add-to-list 'display-buffer-alist
      '("\\`\\*\\(Warnings\\|Compile-Log\\)\\*\\'"
	 (display-buffer-no-window)
	 (allow-no-window . t)))
    ;; Turn off package install warnings https://codeberg.org/jcastp/emacs.d/src/branch/main/emacs-config.org#headline-16
    ;; (when (and (fboundp 'native-comp-available-p)
    ;;         (native-comp-available-p))
    ;;   (setq native-comp-async-report-warnings-errors nil
    ;;     native-comp-deferred-compilation t))
    (set-frame-parameter nil 'alpha-background 85) ; Transparency
    (add-to-list 'default-frame-alist '(alpha-background . 85))
    (add-to-list 'default-frame-alist '(vertical-scroll-bars . right))
    :config
    (setq-default fill-column 120) ; Reset line-length
    (setq-default indent-tabs-mode nil)
    (setq-default tab-width 4)
    (setq-default sh-basic-offset 2)
    (setq-default sh-indentation 2)
    (setq-default cursor-type 'bar)     ; Line-style cursor similar to other text editors
    (setq-default frame-title-format '("%f"))     ; Make window title the buffer name
    (setopt dictionary-server "dict.org")
    :bind (("C-c U" . revert-buffer)
	    ("C-c D" . toggle-debug-on-error)
	    ;; Org
	    ("C-c l" . org-store-link)
	    ("C-c c" . org-capture)
	    ("C-c a" . org-agenda)
	    ("C-c b" . org-iswitchb)
	    ("C-x p i" . org-org-cliplink)
	    ;; Magit /code review
	    ("C-x g" . magit-status)
	    ("C-c R" . code-review-forge-pr-at-point)
	    ("s-SPC" . cycle-spacing))
    :hook
    ((latex-mode
       markdown-mode
       org-mode
       prog-mode
       text-mode) . auto-fill-mode)
    ((latex-mode
       prog-mode) . hs-minor-mode)
    (compilation-finish-functions . (lambda (buf strg) (kill-buffer buf)))
    (auto-fill-function . do-auto-fill)
    (before-save . delete-trailing-whitespace)
    (before-save . do-auto-fill)
    (dired-mode-hook . auto-revert-mode) ; auto refresh dired when files change
    ;; imenu
    ((markdown-mode
       makefile-mode
       prog-mode) . imenu-add-menubar-index)
    ((markdown-mode
       makefile-mode
       prog-mode) . (lambda () (setq imenu-auto-rescan t)))
    :init
    (epa-file-enable)
    (tool-bar-mode 0)
    (scroll-bar-mode 0)
    (menu-bar-mode t)
    (global-display-line-numbers-mode t)
    (global-hl-line-mode t)
    (savehist-mode t)
    (recentf-mode t)
    (global-auto-revert-mode t))

#+END_SRC

** SSH Agency
<<sec:ssh-agency>>

[[https://github.com/magit/ssh-agency][ssh-agency]] takes care of handling SSH keys for us so its useful to ensure it is loaded early.

#+NAME: code-ssh-agency
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ssh-agency
  :ensure t
  :custom (ssh-agency-keys '("~/.ssh/id_ed25519" "~/.ssh/haldane_ed25519")))
  ;; :bind ("C-c C-g" . (ssh-agency-keys '("~/.ssh/id_ed25519" "~/.ssh/haldane_ed25519"))))

#+END_SRC

** Keychain
<<sec:keychain-environment>>

[[https://github.com/emacsorphanage/keychain-environment][keychain-environment]] is an orphaned package that looks for files created by [[https://github.com/danielrobbins/keychain][keychain]] that are used to manage SSH and GPG
agents. I used this before [[sec:ssh-agency][ssh-agency]] until it [[https://github.com/emacsorphanage/keychain-environment/issues/9][broke]] but haven't had 100% success with [[sec:ssh-agency][ssh-agency]] so keep it hanging
around.

#+NAME: code-keychain-environment
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package keychain-environment
  :ensure t
  :init (keychain-refresh-environment)
  :bind (("C-c C-k" . 'keychain-refresh-environment)))

#+END_SRC

** Emojify
<<sec:emojify>>


#+NAME: code-emojify
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package emojify
  :hook (after-init . global-emojify-mode))

#+END_SRC

Read more about [[https://www.rahuljuliato.com/posts/unicode-emojis][Composing Text in Emacs: Unicode, Emojis, and the Power of C-x 8]].

** Custom Functions
<<sec:custom_functions>>

I've come across a bunch of functions that others generously share and include them here. There are a few others
littered about the configuration rather than being aggregated here.

+ [[nameref:code-org-agenda][Org Agenda]]
+ [[nameref:code-quarto-mode-custom][Quarto Mode]]
+ [[nameref:code-sqlite][SQLite]]

*** Reinstall Package
<<sec:reinstall-package>>

A handy way to [[https://emacsredux.com/blog/2020/09/12/reinstalling-emacs-packages/][reinstall a package]].

#+NAME: code-reinstall-package
#+BEGIN_SRC emacs-lisp :tangle init.el
  (defun ns/reinstall-package (pkg)
    "Reinstall a package taken from prompt."
    (interactive (list (intern (completing-read "Reinstall package: " (mapcar #'car package-alist)))))
    (unload-feature pkg)
    (package-reinstall pkg)
    (require pkg))

#+END_SRC

*** On Save
<<sec:on-save>>

[[https://systemcrafters.net/emacs-from-scratch/configure-everything-with-org-babel/][org-babel-tangle-on-save]] define two functions, one to tangle, the other to export this buffer on saving. Hooks are
configured for [[sec:org-mode][org-mode]] so that this file is both tangled and exported on saving.

*TODO* Make this function take an argument so it can be reused.


#+NAME: code-on-save
#+BEGIN_SRC emacs-lisp :tangle init.el
(defun ns/org-babel-tangle-on-save ()
      (when (string-equal (buffer-file-name) (substitute-in-file-name "$HOME/.config/emacs/config/config.org"))
        (org-babel-tangle :append :local)))

(defun ns/org-babel-export-on-save ()
      (when (string-equal (buffer-file-name) (substitute-in-file-name "$HOME/.config/emacs/config/config.org"))
        (org-html-export-to-html)))

#+END_SRC

*** Markdown to Org mode
<<sec:markdown-to-org>>

Charles Choi [[https://sfba.social/@kickingvegas/115663448568105955][shared]] this excellent snippet for converting [[http://yummymelon.com/devnull/import-markdown-to-org-with-the-clipboard-in-emacs.html][Markdown to Org-mode on the fly]]. It requires having ~pandoc~
installed to do the work but that isn't a problem for me as I have it on most systems.

#+NAME: code-markdown-to-org
#+BEGIN_SRC emacs-lisp :tangle init.el
(defun ns/yank-markdown-as-org ()
  "Yank Markdown text as Org.

This command will convert Markdown text in the top of the `kill-ring'
and convert it to Org using the pandoc utility."
  (interactive)
  (save-excursion
    (with-temp-buffer
      (yank)
      (shell-command-on-region
       (point-min) (point-max)
       "pandoc -f markdown -t org --wrap=preserve" t t)
      (kill-region (point-min) (point-max)))
    (yank)))

#+END_SRC

*** Org mode to Markdown
<<sec:org-to-markdown>>

Subsequently Charles Choi found an old [[https://mbork.pl/2021-05-02_Org-mode_to_Markdown_via_the_clipboard][post from Marcin Borkowski]] which does the opposite and converts an Org-mode
region to Markdown in the system clipboard.

#+NAME: code-org-to-markdown
#+BEGIN_SRC emacs-lisp :tangle init.el
(defun ns/org-copy-region-as-markdown ()
  "Copy the region (in Org) to the system clipboard as Markdown."
  (interactive)
  (if (use-region-p)
      (let* ((region
	      (buffer-substring-no-properties
		      (region-beginning)
		      (region-end)))
	     (markdown
	      (org-export-string-as region 'md t '(:with-toc nil))))
	(gui-set-selection 'CLIPBOARD markdown))))

#+END_SRC

*** Load SSH keys
<<sec::ssh-agency-load>>

I found for some reason that the [[sec:ssh-agency][ssh-agency]] loaded SSH keys weren't available and I was prompted for my SSH keys when
pushing to Git forges. It is bound to ~C-c C-s~ to make it simple to load.

#+NAME: code-ssh-agency-load
#+BEGIN_SRC emacs-lisp :tangle init.el
(defun ns/ssh-agency-load ()
  "Set SSH keys for ssh-agency.

This command sets the SSH keys for ssh-agency."
(ssh-agency-keys '("~/.ssh/id_ed25519" "~/.ssh/haldane_ed25519")))
#+END_SRC

* Completion and Navigation
<<sec:completion-navigation>>

There are various frameworks and packages available to aid with (auto-)completion such [[https://company-mode.github.io/manual/][Company]], [[https://emacs-helm.github.io/helm/][Helm]] or [[https://github.com/abo-abo/swiper][Ivy]]. I've
explicitly gone with Company but in revising my configuration to write this literate version it looks like I may have
pulled the others in as dependencies of other packages but have opted to purge those from now on.

** Company Mode

[[https://company-mode.github.io/manual/][Company mode]] is a modular text completion framework.

#+NAME: code-company
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package company
  :ensure t
  :defer 0.5
  :hook
  (text-mode . company-mode)
  (prog-mode . company-mode)
  (org-src-mode . company-mode)
  ;; https://themagitian.github.io/posts/emacsconfig/
  :custom
  (company-minimum-prefix-length 3)
  (company-idle-delay 0.3)
  (company-selection-wrap-around t)
  (company-dabbrev-other-buffers t)
  (company-dabbrev-code-other-buffers t)
  (custom-set-faces
   '(company-tooltip ((t (:background "#3e4452"))))
   '(company-tooltip-selection ((t (:background "#454c59"))))
   '(company-tooltip-common ((t (:background "#3e4452"))))
   '(company-scrollbar-bg ((t (:background "#282c34"))))))

#+END_SRC

** Consult
<<sec:consult>>

[[https://github.com/minad/consult][Consult]] "/provides search and navigation commands/" it is compatible with [[sec:vertico][vertico]] and can be combined with [[sec:marginalia][marginalia]],
[[sec:embark][embark]] and [[sec:orderless][orderless]].

#+NAME: code-consult
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package consult
  ;; Replace bindings. Lazily loaded by `use-package'.
  :bind (;; C-c bindings in `mode-specific-map'
         ("C-c M-x" . consult-mode-command)
         ("C-c h" . consult-history)
         ("C-c k" . consult-kmacro)
         ("C-c m" . consult-man)
         ("C-c i" . consult-info)
         ([remap Info-search] . consult-info)
         ;; C-x bindings in `ctl-x-map'
         ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
         ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
         ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
         ;; Custom M-# bindings for fast register access
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
         ("C-M-#" . consult-register)
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ;; M-g bindings in `goto-map'
         ("M-g e" . consult-compile-error)
         ("M-g r" . consult-grep-match)
         ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ;; M-s bindings in `search-map'
         ("M-s d" . consult-find)                  ;; Alternative: consult-fd
         ("M-s c" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ;; Isearch integration
         ("M-s e" . consult-isearch-history)
         :map isearch-mode-map
         ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
         ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
         ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
         ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
         ;; Minibuffer history
         :map minibuffer-local-map
         ("M-s" . consult-history)                 ;; orig. next-matching-history-element
         ("M-r" . consult-history))                ;; orig. previous-matching-history-element

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :custom
  ;; Tweak the register preview for `consult-register-load',
  ;; `consult-register-store' and the built-in commands.  This improves the
  ;; register formatting, adds thin separator lines, register sorting and hides
  ;; the window mode line.
  (advice-add #'register-preview :override #'consult-register-window)
  (register-preview-delay 0.5)

  ;; Use Consult to select xref locations with preview
  (xref-show-xrefs-function #'consult-xref
   xref-show-definitions-function #'consult-xref))
#+END_SRC

** Embark
<<sec:embark>>

[[https://github.com/oantolin/embark/][Embark]] "/makes it easy to choose a command to run based on what is near point, both during a minibuffer completion
session (in a way familiar to Helm or Counsel users) and in normal buffers/". I've not yet setup [[https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt][which-key like menu
prompt]] but may do one day.

#+NAME: code-embark
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package embark
  :ensure t
  :defer 0.5
  :bind
  (("C-." . embark-act)         ;; pick some comfortable binding
   ("C-;" . embark-dwim)        ;; good alternative: M-.
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'
  :custom
  ;; Optionally replace the key help with a completing-read interface
  (prefix-help-command #'embark-prefix-help-command)
  ;; (add-to-list 'vertico-multiform-categories '(embark-keybinding grid))
  (embark-indicators
	'(embark-minimal-indicator  ; default is embark-mixed-indicator
	  embark-highlight-indicator
	  embark-isearch-highlight-indicator))
  ;; Show the Embark target at point via Eldoc. You may adjust the
  ;; Eldoc strategy, if you want to see the documentation from
  ;; multiple providers. Beware that using this can be a little
  ;; jarring since the message shown in the minibuffer can be more
  ;; than one line, causing the modeline to move up and down:
  ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
  ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)
  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))
;; Consider

#+END_SRC

** embark-consult
<<sec:embark-consult>>

[[https://github.com/oantolin/embark][embark-consult]] is recommended if using both [[sec:consult][consult]] and [[sec:embark][embark]].

#+NAME: code-embark-consult
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package embark-consult
    :ensure t
    :defer 0.5
    :after (consult embark))

#+END_SRC

** Marginalia
<<sec:marginalia>>

[[https://github.com/minad/marginalia/][Marginalia]] enables rich annotations. The ~marginalia-cycle~ command is mapped to ~M-A~ in both the
~minibuffer-local-map~ and the ~completion-list-mode-map~. As we always want to have Marginalia available we ~:init~ it
with the ~marginalia-mode~ rather than deferring.

#+NAME: code-marginalia
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package marginalia
  :ensure t
  ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
  ;; available in the *Completions* buffer, add it to the
  ;; `completion-list-mode-map'.
  :bind
  (:map minibuffer-local-map
	("M-A" . marginalia-cycle))
  (:map completion-list-mode-map
	("M-A" . marginalia-cycle))
  ;; The :init section is always executed.
  :init
  ;; Marginalia must be activated in the :init section of use-package such that
  ;; the mode gets enabled right away. Note that this forces loading the
  ;; package.
  (marginalia-mode))

#+END_SRC

** Movetext
<<sec:movetext>>

[[https://github.com/emacsfodder/move-text][move-text]] is a simple package makes it easy to move the current line or region up (~M-up~) or down (~M-down~).

#+NAME: code-movetext
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package move-text
  :ensure t
  :defer 0.5
  :config
  (move-text-default-bindings))

#+END_SRC

** Orderless
<<sec:orderless>>

[[https://github.com/oantolin/orderless][Orderless]]

#+NAME: code-orderless
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic)
	completion-category-defaults nil
	completion-category-overrides '((file (styles basic partial-completion)))))

#+END_SRC

** Savehist

Savehist (can't find package homepage) persists history over Emacs restarts and helps with [[sec:vertico][Vertico]].

#+NAME: code-savehist
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package savehist
  :ensure t
  :init
  (savehist-mode))

#+END_SRC

** Vertico
<<sec:vertico>>

[[https://github.com/minad/vertico][Vertico]]

#+NAME: code-vertico
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package vertico
  :ensure t
  :init
  (vertico-mode)
  :config
  ;; Different scroll margin
  ;; (setq vertico-scroll-margin 0)

  ;; Show more candidates
  ;; (setq vertico-count 20)

  ;; Grow and shrink the Vertico minibuffer
  ;; (setq vertico-resize t)

  ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
  ;; (setq vertico-cycle t)

  ;; TAB completion - completes path selection rather than selecting current point
  ;; (keymap-set vertico-map "TAB" #'minibuffer-complete)
  )

#+END_SRC

** Vundo
<<sec:vundo>>

[[https://github.com/casouri/vundo][Vundo]] provides a Visual insight into the Undo history of a buffer, I find it really useful and the [[https://archive.casouri.cc/note/2021/visual-undo-tree/index.html][authors overview of
undo buffer history]] was insightful too.

#+NAME: code-vundo
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package vundo
  :ensure t
  :defer 0.5
  :bind (("C-c v" . vundo))
  :hook
  (prog-mode . vundo-popup-mode)
  (text-mode . vundo-popup-mode))

#+END_SRC

** Which-key
<<sec:which-key>>

*TODO* Sort this section out!

[[https://github.com/justbur/emacs-which-key][which-key]] (now part of Emacs core) is a minor mode which pops up a buffer to show what "which key", if pressed next,
will do. Its incredibly useful and should be enabled by default on all systems. However, as noted above on [[sec:conf-use-package][configuring
use-package]] keys should be bound with ~(desc . command)~ to include a description as to what they do, otherwise you end
up with a lot of ~prefix~ and its value disappears.

#+NAME: code-which-key
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package which-key
  :ensure t
  :defer 0.5
  :config (which-key-mode)
  (global-set-key (kbd "<f8>") 'which-key-show-major-mode)
  ;; +prefix isn't helpful, lets sort that out via...
  ;; https://gist.github.com/mmarshall540/a12f95ab25b1941244c759b1da24296d)
  (which-key-add-key-based-replacements
    "<f1> 4"        "help-other-win"
    "<f1>"          "help"
    "<f2>"          "2-column"
    "C-c"           "mode-and-user"
    "C-h 4"         "help-other-win"
    "C-h"           "help"
    "C-x 4"         "other-window"
    "C-x 5"         "other-frame"
    "C-x 6"         "2-column"
    "C-x 8"         "insert-special"
    "C-x C-k C-q"   "kmacro-counters"
    "C-x C-k C-r a" "kmacro-add"
    "C-x C-k C-r"   "kmacro-register"
    "C-x C-k"       "keyboard-macros"
    "C-x RET"       "encoding/input"
    "C-x a i"       "abbrevs-inverse-add"
    "C-x a"         "abbrevs"
    "C-x n"         "narrowing"
    "C-x p"         "projects"
    "C-x r"         "reg/rect/bkmks"
    "C-x t ^"       "tab-bar-detach"
    "C-x t"         "tab-bar"
    "C-x v M"       "vc-mergebase"
    "C-x v b"       "vc-branch"
    "C-x v"         "version-control"
    "C-x w ^"       "window-detach"
    "C-x w"         "window-extras"
    "C-x x"         "buffer-extras"
    "C-x"           "extra-commands"
    "C-c m"         "Magit"
    "C-c m d"       "Diff"
    "C-c m g"       "Link"
    "C-c m l"       "Log"
    "M-g"           "goto-map"
    "M-s h"         "search-highlight"
    "M-s"           "search-map")
  (with-eval-after-load 'lsp
    (which-key-add-key-based-replacements
      "s-l"           "LSP"
      "s-l ="         "LSP Format"
      "s-l F"         "LSP Workspace"
      "s-l G"         "LSP Peek"
      "s-l T"         "LSP Treemacs/UI"
      "s-l a"         "LSP Execute/highlight"
      "s-l g"         "LSP Find"
      "s-l h"         "LSP Doc/Describe"
      "s-l r"         "LSP Refactor"
      "s-l w"         "LSP Session"))
  (with-eval-after-load 'page-ext
    (which-key-add-key-based-replacements
     "C-x C-p" "page-extras"))
  ;; Org-mode provides some additional prefix-keys in `org-mode-map'.
  (with-eval-after-load 'org
    (which-key-add-keymap-based-replacements org-mode-map
      "C-c \""      "org-plot"
      "C-c C-v"     "org-babel"
      "C-c C-x"     "org-extra-commands")))

#+END_SRC

** helpful
<<sec:helpful>>

[[https://github.com/Wilfred/helpful][helpful]] makes it simple to find out what keys, functions, modes etc. do.

*TODO* Improve key-bindings here.

+ ~C-h F~ - is bound to ~info-goto-emacs-command-node~. Helpful already links to the manual, if a function is referenced
  there.
+ ~C-h C~ - is bound to describe ~describe-coding-system~. I don't find this very useful, but it's frequently useful to
  only look at interactive functions.
+ Note that the built-in ~describe-function~ includes both functions and macros. ~helpful-function~ is functions only,
  so we provide ~helpful-callable~ as a drop-in replacement.

#+NAME: code-helpful
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package helpful
  :ensure t
  :defer 0.5
  :bind (("C-h C" . helpful-command)
          ("C-h f" . helpful-callable)
          ("C-h F" . helpful-function)
          ("C-h v" . helpful-variable)
          ("C-h k" . helpful-key)
          ("C-c C-d" . helpful-at-point)))

#+END_SRC

** goto-addr
<<sec:goto-addr>>

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Goto-Address-mode.html][goto-address-mode]] makes URLs and email-addresses clickable across all buffers. Found at a [[https://xenodium.com/actionable-urls-in-emacs-buffers][blog-post by Xenodium]].

#+NAME: code-goto-addr
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package goto-addr
  :hook ((compilation-mode . goto-address-mode)
         (prog-mode . goto-address-prog-mode)
         (eshell-mode . goto-address-mode)
         (shell-mode . goto-address-mode))
  :bind (:map goto-address-highlight-keymap
              ("<RET>" . goto-address-at-point)
              ("M-<RET>" . newline))
  :commands (goto-address-prog-mode
             goto-address-mode))
#+END_SRC

* Version Control
<<sec:version-control>>

** Magit
<<sec:magit>>

[[https://magit.vc/][Magit]] is amazing! Hands down the package I use the most in Emacs for my daily work, note taking and more as I have
literally everything under Git version control.

+ [[https://www.reddit.com/r/emacs/comments/17af1q5/opening_magit_fullframe_then_restoring_windows_on/][Opening Magit full-frame then restoring windows]]
+ [[https://mbork.pl/2025-05-12_Coloring_Git_output_in_Magit][Coloring Git output in Magit]]
+ [[https://huonw.github.io/blog/2025/12/magit-insert-worktrees/][magit-insert-worktrees improves status buffers | Huon on the internet]]

#+NAME: magit
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package magit
    :ensure t
    :custom
    (magit-repository-directories
  	`(("~/dotfiles" . 1)
  	  ("~/.config/emacs/" . 1)
  	  ("~/org/" . 1)
  	  ("~/work/git/" . 2)
  	  ("~/work/python/tcx2gpx/" . 1)
  	  ("~/work/python/wpweather/" . 1)
  	  ))
    (auth-sources '("~/.authinfo.gpg"))
    (magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)
    (magit-bury-buffer-function 'magit-restore-window-configuration)
    (magit-pull-or-fetch t)
    (magit-log-margin '(t "%F %R" magit-log-margin-width t 18))
    (magit-process-finish-apply-ansi-colors t)
    ;; Don't want auto-fill-mode enabled for the following modes, probably a smarter way of doing this under :hooks
    ;; perhaps?
    (remove-hook 'git-commit-mode #'turn-on-auto-fill)
    (remove-hook 'forge-post-mode #'turn-on-auto-fill)
    (add-hook 'after-save-hook 'magit-after-save-refresh-status)
    (add-hook 'magit-status-sections-hook #'magit-insert-worktrees t)
    ;; :hook
    :bind (:map magit-mode-map (("C-c m C" . magit-clone)
                                 ("C-c m F" . magit-pull-from-upstream)
                                 ("C-c m P" . magit-push-current-to-upstream)
                                 ("C-c m R" . magit-file-rename)
                                 ("C-c m f" . forge-pull)
                                 ("C-c m d d" . nds:magit-show-with-difftastic)
                                 ("C-c m d r" . magit-diff-range)
                                 ("C-c m d s" . magit-diff-staged)
                                 ("C-c m l l" . magit-log)
                                 ("C-c m l f" . magit-log-buffer-file)
                                 ("C-c m l o" . magit-log-other))))

#+END_SRC

** code-review
<<sec:code-review>>

[[https://github.com/wandersoncferreira/code-review/][code-review]]

#+NAME: code-code-review
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package code-review
  :ensure t
  :custom
  (code-review-fill-column 120)
  (code-review-new-buffer-window-strategy #'switch-to-buffer)
  :hook
  (code-review-mode . emojify-mode))

#+END_SRC

** consult-gh
<<sec:consult-gh>>


[[https://github.com/armindarvish/consult-gh][consult-gh]] is a [[https://cli.github.com/][GitHub CLI]] client inside Emacs that uses [[sec:consult][Consult]].

Not currently tangled.

#+NAME: code-consult-gh
#+BEGIN_SRC emacs-lisp :tangle no

(use-package consult-gh
  :ensure t
  :after consult
  :custom
  (consult-gh-default-clone-directory "~/projects")
  (consult-gh-show-preview t)
  (consult-gh-preview-key "C-o")
  (consult-gh-repo-action #'consult-gh--repo-browse-files-action)
  (consult-gh-issue-action #'consult-gh--issue-view-action)
  (consult-gh-pr-action #'consult-gh--pr-view-action)
  (consult-gh-code-action #'consult-gh--code-view-action)
  (consult-gh-file-action #'consult-gh--files-view-action)
  (consult-gh-notifications-action #'consult-gh--notifications-action)
  (consult-gh-dashboard-action #'consult-gh--dashboard-action)
  (consult-gh-large-file-warning-threshold 2500000)
  (consult-gh-prioritize-local-folder 'suggest)
  (consult-gh-default-orgs-list (consult-gh--get-current-orgs t))
  :hook
  ;; Add a hook to change default organizations when the account is switched
  (add-hook 'consult-gh-auth-post-switch-hook (lambda (&rest args) (setq consult-gh-default-orgs-list (consult-gh--get-current-orgs t))))

  ;; Remember visited orgs and repos across sessions
  (add-to-list 'savehist-additional-variables 'consult-gh--known-orgs-list)
  (add-to-list 'savehist-additional-variables 'consult-gh--known-repos-list))

#+END_SRC

** consult-gh-forge
<<sec:consult-gh-forge>>

Works in conjunction with [[sec:consult-gh][consult-gh]].

Not currently tangled.

#+NAME: code-consult-gh-forge
#+BEGIN_SRC emacs-lisp :tangle no
;; ;; Install `consult-gh-forge' for forge actions
(use-package consult-gh-forge
  :ensure t
  :defer 3
  :after (consult-gh)
  :custom
  (consult-gh-forge-mode +1)
  (consult-gh-forge-timeout-seconds 20))
#+END_SRC

** difftastic
<<sec:difftastic>>

[[https://github.com/pkryger/difftastic.el][difftastic.el]] brings the brilliant code aware [[https://difftastic.wilfred.me.uk/][difftastic]] ([[https://github.com/Wilfred/difftastic][GitHub]]) to Emacs. This package replaces an earlier [[https://tsdh.org/posts/2022-08-01-difftastic-diffing-with-magit.html][custom configuration]]
that I found and had happily used for a while.

#+NAME: code-difftastic
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package difftastic
  :ensure t
  :demand t
  :bind (:map magit-blame-read-only-mode-map
              ("D" . difftastic-magit-show)
              ("S" . difftastic-magit-show))
  :custom
  (eval-after-load 'magit-diff
    '(transient-append-suffix 'magit-diff '(-1 -1)
       [("D" "Difftastic diff (dwim)" difftastic-magit-diff)
        ("S" "Difftastic show" difftastic-magit-show)])))

#+END_SRC

** Forge
<<sec:forge>>

[[https://github.com/forge][Forge]] allows you to interact and work with Git Forges
(e.g. [[https://github.com/][GitHub]] or [[https://gitlab.com][GitLab]] and hopefully soon [[https://codeberg.org][Codeberg]]) to read, write,
update issues and pull-requests. It requires careful setup of authentication with GPG encrypted secrets but totally
worth it as it massively improves workflow.

#+NAME: forge
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package forge
  :ensure t
  :defer 0.5
  :after magit
  :config
  (push '("forgejo.nshephard.dev"
          "forgejo.nshephard.dev/api/v1"
          "forgejo.nshephard.dev"
          forge-forgejo-repository)
	forge-alist))

#+END_SRC

** ghub
<<sec:ghub>>

[[https://github.com/magit/ghub][ghub]] is a client library to the APIs of various forges.

#+NAME: code-ghub
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ghub
  :ensure t
  :defer 0.5
  :after (magit))
#+END_SRC

** glab
<<sec:glab>>

[[https://github.com/emacsattic/glab][glab]] extends [[sec:ghub][ghub]] for [[https://gitlab.com][GitLab]].

#+NAME: code-glab
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package glab
  :ensure t
  :defer 0.5
  :after (magit))
#+END_SRC

** git-gutter
<<sec:git-gutter>>

#+NAME: code-git-gutter
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package git-gutter
    :ensure t
    :defer 0.5
    :after magit
    :custom
    (global-git-gutter-mode +1))

#+END_SRC

[[https://github.com/emacsorphanage/git-gutter][git-gutter]]
** git-cliff
<<sec:git-cliff>>

[[https://github.com/liuyinz/git-cliff.el][git-cliff]]

#+NAME: code-git-cliff
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package git-cliff
  :ensure t  :defer 2
  :after (magit))

#+END_SRC

** gitlab-ci-mode
<<sec:gitlab-ci-mode>>

[[https://gitlab.com/joewreschnig/gitlab-ci-mode/][gitlab-ci-mode]]

Currently not tangled.

#+NAME: code-gitlab-ci-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package gitlab-ci-mode
  :ensure t
  :defer 2
  :after (glab))

#+END_SRC

** gitlab-ci-mode-flycheck
<<sec:gitlab-ci-mode-flycheck>>

[[https://gitlab.com/joewreschnig/gitlab-ci-mode-flycheck/][gitlab-ci-mode-flycheck]]

Currently not tangled.

#+NAME: code-gitlab-ci-mode-flycheck
#+BEGIN_SRC emacs-lisp :tangle no
(use-package gitlab-ci-mode-flycheck
  :ensure t
  :defer 3
  :after (gitlab-ci-mode))

#+END_SRC

** git-link
<<sec:git-link>>

[[https://github.com/sshaw/git-link][git-link]]

#+NAME: code-git-link
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package git-link
    :ensure t
    :after (magit)
    :bind (:map magit-mode-map (("C-c m g c" . git-link-commit)
                                 ("C-c m g g" . git-link-dispatch)
                                 ("C-c m g h" . git-link-homepage)
                                 ("C-c m g l" . git-link)))
    :config
    (require 'git-link-transient))

#+END_SRC

** git-modes
<<sec:git-modes>>

[[https://github.com/magit/git-modes][git-modes]] provides major modes for Git configuration files.

#+NAME: code-git-modes
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package git-modes
  :ensure t
  :defer 3
  :after (magit))

#+END_SRC

** gh-notify
<<sec:gh-notify>>

[[https://github.com/anticomputer/gh-notify][gh-notify]] a "/thin UI veneer on top of Magit/Forge porcelain for juggling large amounts of GitHub notifications at
speed.".

#+NAME: code-gh-notify
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package gh-notify
  :ensure t
  :after (magit))

#+END_SRC

** git-timemachine
<<sec:git-timemachine>>

[[https://codeberg.org/pidu/git-timemachine][git-timemachine]]

#+NAME: code-git-timemachine
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package git-timemachine
  :ensure t
  :defer 3
  :after (magit)
)

#+END_SRC

** gtea
<<sec:gtea>>

[[https://github.com/emacsattic/gtea][gtea]] extends [[sec:ghub][ghub]] for [[https://about.gitea.com/][Gitea]] (which has forked to [[https://forgejo.org/][ForgeJo]]) and is used to power [[https://codeberg.org][Codeberg]])

#+NAME: code-gtea
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package gtea
  :ensure t
  :defer 0.5
  :after (magit))
#+END_SRC

** JuJutsu

[[https://www.jj-vcs.dev/latest/][Jujutsu (~jj~)]] is a version control (VC) system built on top of Git (it typically uses it  as a backend although its possible to use
other VC software). There are a few packages seeking to provide support for ~jj~ in Emacs.

*** vc-jj
<<sec:jc-jj>>

[[https://github.com/bolivier/jj-mode.el][jj-mode.el]] aims to "/add ~jj~ support to the Emacs built-in ~vc~ and ~project~ libraries/".

#+NAME: code-jc-jj
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package vc-jj
  :ensure t
  :defer 3)
#+END_SRC

*** jujutsu.el
<<sec:jujutsu.el>>

[[https://github.com/bennyandresen/jujutsu.el][jujutsu.el]] is "/inspired by [[sec:magit][magit]] and humbly not attempting to match it in scope./". Its not been updated in a while so
no attempt to install and configure but noted for future reference.

*** jj-mode-el
<<sec:jj-mode.el>>

[[https://github.com/bolivier/jj-mode.el][jj-mode.el]] "/provides a [[sec:magit][magit]]-inspired interface for Jujutsu/". It seems to see more active development than [[sec:jujutsu.el][jujutsu.el]].

#+NAME: code-jj-mode.el
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package jj-mode
  :vc (:url "https://github.com/bolivier/jj-mode.el"))
#+END_SRC

*** jujutsushi
<<sec:jujutsushi>>

[[https://git.sr.ht/~puercopop/jujutsushi][jujutsushi]] is another package for adding ~jj~ support.

Not currently tangled.

#+NAME: code-jujutsushi
#+BEGIN_SRC emacs-lisp :tangle no
(use-package jujutsushi
  :vc (:url "https://git.sr.ht/~puercopop/jujutsushi"
       :branch "default"
       :rev :newest
       :main-file "jujutsushi.el"))

#+END_SRC
** magit-delta
<<sec:magit-delta>>

[[https://github.com/dandavison/magit-delta][magit-delta]] use [[https://github.com/dandavison/delta][delta]] but I currently prefer [[sec:difftastic][difftastic]].

Not currently tangled.

#+NAME: code-magit-delta
#+BEGIN_SRC emacs-lisp :tangle no

(use-package magit-delta
  :ensure t
  :after magit
  :hook (magit-mode . magit-delta-mode))

#+END_SRC
** magit-gitlab
<<sec:magit-gitlab>>

[[https://gitlab.com/arvidnl/magit-gitlab][magit-gitlab]]

#+NAME: code-magit-gitlab
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package magit-gitlab
  :ensure t
  :defer 3
  :after (magit))

#+END_SRC

** magit-imerge
<<sec:magit-imerge>>

[[https://github.com/magit/magit-imerge][magit-imerge]] is a Magit interface to [[https://github.com/mhagger/git-imerge][git-imerge]]

#+NAME: code-magit-imerge
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package magit-imerge
  :ensure t
  :after (magit))

#+END_SRC

** magit-stats
<<sec:magit-stats>>

[[https://github.com/LionyxML/magit-stats][magit-stats]]

#+NAME: code-magit-stats
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package magit-stats
  :ensure t
  :defer 0.5
  :after (magit))

#+END_SRC

** orgit
<<sec:orgit>>

[[https://github.com/magit/orgit][orgit]]

#+NAME: code-orgit
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package orgit
  :ensure t
  :defer 0.5
  :after (magit))

#+END_SRC

** orgit-forge
<<sec:orgit-forge>>

[[https://github.com/magit/orgit-forge][orgit-forge]]

#+NAME: code-orgit-forge
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package orgit-forge
  :ensure t
  :defer 0.5
  :after magit
  :bind (:map magit-mode-map
	      ("C-c m c" . orgit-store-link))
  (:map org-mode-map
	("C-c m v" . org-insert-last-stored-link)))

#+END_SRC

** pr-review
<<sec:pr-review>>

[[https://github.com/blahgeek/emacs-pr-review][pr-review]] aids with reviewing pull-requests on GitHub. I don't use it much, in fact I can't recall ever using it so its
currently not included.

Not currently tangled.

#+NAME: code-pr-review
#+BEGIN_SRC emacs-lisp :tangle no
(use-package pr-review
  :ensure t
  :defer 0.5
  :after (ghub))

#+END_SRC

** treemacs-magit
<<sec:treemacs-magit>>

[[https://github.com/Alexander-Miller/treemacs][treemacs-magit]] treemacs integratio for [[sec:magit][Magit]].

#+NAME: code-treemacs-magit
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package treemacs-magit
  :ensure t
  :defer 0.5
  :after (magit))

#+END_SRC

** Git Blame

There are a few packages for showing/viewing Git Blame.

[[https://github.com/LuciusChen/blame-reveal][blame-reveal]] which I've not tried yet as its not yet on [[https://melpa.org][MELPA]] or other repositories.


*** blamer
<<sec:blamer>>

[[https://github.com/artawower/blamer.el][blamer.el]] shows pop-ups for the current line when ~blamer-idle-time~ is exceeded. Not necessarily something I wanted
popping up all the time but potentially useful.

Not currently tangled.

#+NAME: code-blamer
#+BEGIN_SRC emacs-lisp :tangle no
(use-package blamer
  :ensure t
  :bind (("s-i" . blamer-show-commit-info)
         ("C-c i" . blamer-show-posframe-commit-info))
  :defer 20
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 70)
  :custom-face
  (blamer-face ((t :foreground "#7a88cf"
                    :background nil
                    :height 140
                    :italic t)))
  :config
  (global-blamer-mode 1))

#+END_SRC

*** why-this
<<sec:why-this>>

[[https://codeberg.org/akib/emacs-why-this][why-this]] is a mode for showing Git blame annotations, you can find the blame for a current position with ~why-this~ and
it will show up in the mini-buffer or you can ~why-this-annotate~ on the current buffer and a new buffer appears showing
the blame for each line of code.

#+NAME: code-why-this
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package why-this
  :ensure t
  :defer 1
  :after magit
  :custom
  (set-face-background 'why-this-annotate-heat-map-cold "#203448")
  (set-face-background 'why-this-annotate-heat-map-warm "#382f27")
  :bind (:map magit-mode-map (("C-c m w" . 'why-this)
                               ("C-c m W" . 'why-this-annotate))))
#+END_SRC

* Transient
<<sec:transient>>

[[https://github.com/magit/transient][Transient]] is what makes [[sec:magit][Magit]] so powerful a helping hand of key-board driven menus to navigate all the commands as you
build muscle memory.

** Casual Suite
<<sec:casual-suite>>

[[https://github.com/kickingvegas/casual-suite][casual-suite]] is an opinionated set of transients for common buffers such as [[sec:dired][Dired]] or iBuffer. Its from [[http://yummymelon.com/devnull/announcing-casual-suite.html][Charles Choi]].

#+NAME: code-casual-suite
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package casual-suite
  :ensure t
  :bind (:map
         reb-mode-map ("s-c" . casual-re-builder-tmenu)
         :map
         reb-lisp-mode-map ("s-c" . casual-re-builder-tmenu)
         :map
          ibuffer-mode-map))

#+END_SRC



** Magit Auxiliary Commands
<<sec:magit-aux-commands>>

Found a useful article on [[https://mike.hostetlerhome.com/emacs-obscure-package-transient][making your own transient]]

Not currently tangled.

#+NAME: code-magit-aux-commands
#+BEGIN_SRC emacs-lisp :tangle no
(transient-define-prefix nds:magit-aux-commands ()
			 "My personal auxiliary magit commands."
			 ["Auxiliary commands"
			  ("o" "Orgit Link" orgit-store-link)
			  ])

#+END_SRC


** Python Transient
<<sec:transient-python>>

Not currently tangled.

#+NAME: code-transient-python
#+BEGIN_SRC emacs-lisp :tangle no
  (transient-define-prefix ns/python-transient ()
  			 "Python"
  			 [["Common Commands"
  			   ("v" "Select virtual environment" pyvenv-workon)
  			   ("n" "Create Numpy docstring" numpydoc-generate)
  			   ]])
  (global-set-key (kbd "C-h C-k") 'ns/python-transient)

#+END_SRC

* Org mode
<<sec:org-mode>>

[[https://orgmode.org/][Orgmode]] is "/A GNU Emacs major mode for keeping notes, authoring documents, computational notebooks, literate
programming, maintaining to-do lists, planning projects, and more - in a fast and effective plain-tests system./"

Sources of some of the options are linked below.

+ [[https://mahmoodsh.com/efficiently_parsing_org_files.html][efficiently parsing org files]] shows how to speed up loading big Org files.
+ [[https://anonimno.codeberg.page/tracking%20worktime.html][org-clock-persist 'history]]
+ [[https://stackoverflow.com/a/38477233/1444043][org-image-actual-width]]
+ [[https://emacs.stackexchange.com/a/21267/10100][org-startup-with-inline-images]]
+ [[https://emacs.stackexchange.com/a/3570/10100][org-confirm-babel-evaluate]]
+ [[https://github.com/erikriverson/org-mode-R-tutorial/blob/master/org-mode-R-tutorial.org#inserting-r-graphical-output][org-format-latex-options]]
+ [[https://hachyderm.io/@al3x/112186172832809202][after-focus-change-function]]
+ [[https://github.com/james-stoup/emacs-org-mode-tutorial#orga87f491=][org-todo-keywords]] set additional keywords (and colours).

#+NAME: code-org-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org
  :ensure t
  :bind
  (("C-x p i" . 'org-cliplink))
  :custom
  (add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
  (global-font-lock-mode 1)
  (org-directory "~/org/")
  (org-agenda-include-diary t)
  (org-agenda-skip-deadline-if-done t)
  (org-agenda-skip-scheduled-if-done t)
  (org-agenda-files '("~/org/agenda.org"
 			   "~/org/gtd/admin.org"
 			   "~/org/gtd/afmslicer.org"
 			   "~/org/gtd/carpentries.org"
 			   "~/org/gtd/clarity.org"
 			   "~/org/gtd/computing.org"
 			   "~/org/gtd/cured.org"
 			   "~/org/gtd/emacs.org"
 			   "~/org/gtd/isoslam.org"
 			   "~/org/gtd/joss.org"
 			   "~/org/gtd/openfest2024.org"
 			   "~/org/gtd/osc.org"
 			   "~/org/gtd/pgfinder.org"
			   "~/org/gtd/reproducibilitea.org"
			   "~/org/gtd/rse.org"
			   "~/org/gtd/rse-competencies.org"
			   "~/org/gtd/sheffieldr.org"
 			   "~/org/gtd/tcx2gpx.org"
			   "~/org/gtd/thyroid.org"
			   "~/org/gtd/topostats.org"))
  (org-babel-do-load-languages 'org-babel-load-languages '((emacs-lisp . t)
                                                            (jq .t)
                                                            (latex .t)
                                                            (org . t)
                                                            (python . t)
							      (shell . t)
							      (R . t)))
  (org-babel-python-command "~/.virtualenvs/default/bin/python")
  (org-format-latex-options '(:foreground default
		                :background "rgb 1 1 1"
		                :scale 1.5
		                :html-foreground "Black"
		                :html-background "Transparent"
		                :html-scale 1.0
		                :matchers ("begin" "$1" "$" "$$" "\\(" "\\[")))
  (org-startup-indented 0)
  (org-startup-with-inline-images t)
  (org-clock-persist 'history)
  (org-log-done 'time)
  (org-image-actual-width nil)
  (org-export-backends '(beamer html latex md odt))
  (org-confirm-babel-evaluate nil)
  (org-startup-within-inline-images t)
  (org-todo-keywords
    '((sequence "TODO(t)" "IN-PROGRESS(i@/!)" "BLOCKED(b@)"  "|" "DONE(d!)" "WONT-DO(w@/!)" )))
  (org-todo-keyword-faces
    '(("TODO" . (:foreground "GoldenRod" :weight bold))
       ("IN-PROGRESS" . (:foreground "Cyan" :weight bold))
       ("BLOCKED" . (:foreground "Red" :weight bold))
       ("DONE" . (:foreground "LimeGreen" :weight bold))
       ("WONT-DO" . (:foreground "DarkViolet" :weight bold))))
  ;; Disable electric-indent-mode in org buffers
  :hook
  (org-mode . (lambda () (electric-indent-local-mode 0)))
  (org-mode . (lambda () (org-rainbow-tags-mode 1)))
  (org-mode . (lambda () (add-hook 'after-save-hook #'ns/org-babel-tangle-on-save))))

#+END_SRC

There are a lot of org-based packages and extensions, those that are minor tweaks are in sub-sections below, major
things such as [[sec:org-roam][org-roam]] and [[sec:org-gtd][org-gtd]] have their own sections which follow.

*** Org Analyzer
<<sec:org-analyzer>>

[[https://github.com/rksm/clj-org-analyzer/][org-analyzer]] provides a set of functions that parse and summarise your [[sec:org-agenda][org-agenda]] and fires up a web-page to visualise
the results. Very neat and powerful...if you stick to the habit of logging your time on tasks!

#+NAME: code-org-analyzer
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package org-analyzer
  :ensure t
  :defer 2)

#+END_SRC

*** Org Links
<<sec:org-links>>

[[https://codeberg.org/Anoncheg/emacs-org-links][org-links]]

#+NAME: code-org-links
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-links
  :ensure t
  :defer 0.5
  :after org-mode)

#+END_SRC

*** Org Modern
<<sec:org-modern>>

[[https://github.com/minad/org-modern][org-modern]] is "/a modern style for Org buffers using font locking and text properties/".

#+NAME: code-org-modern
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-modern
  :ensure t
  :defer 0.5
  :after org-mode
  :config (setq
	   ;; Edit settings
	   org-auto-align-tags nil
	   org-tags-column 0
	   org-catch-invisible-edits 'show-and-error
	   org-special-ctrl-a/e t
	   org-insert-heading-respect-content t
	   ;; Org styling, hide markup etc.
	   org-hide-emphasis-markers t
	   org-pretty-entities t
	   org-ellipsis ""
	   ;; Agenda styling
	   org-agenda-tags-column 0
	   org-agenda-block-separator ?
	   org-agenda-time-grid
	   '((daily today require-timed)
	     (800 1000 1200 1400 1600 1800 2000)
	     "  " "")
	   org-agenda-current-time-string
	   " now " ))

#+END_SRC

*** Org Note
<<sec:org-note>>

[[https://github.com/Artawower/orgnote.el][orgnote]] synchronises [[sec:org-roam][org-roam]] notes with the Android application [[https://org-note.com/][orgnote]]. I'm yet to fully adopt using Org on my mobile
device, mainly as I hate typing on mobile, but also I'm yet to settle on an application for working with org files on
mobile.

Not tangled for now.

#+NAME: code-org-note
#+BEGIN_SRC emacs-lisp :tangle no
(use-package orgnote
  :ensure t)

#+END_SRC

*** Org Rainbow Tags
<<sec:org-rainbow-tags>>

[[https://github.com/KaratasFurkan/org-rainbow-tags][org-rainbow-tags]] adds random colours to Org tags based on the hash of the tag name, which keeps things consistent.

#+NAME: code-org-rainbow-tags
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-rainbow-tags
  :ensure t
  :defer 0.5)

#+END_SRC

*** Org Ref
<<sec:org-ref>>

[[https://github.com/jkitchin/org-ref][org-ref]]

#+NAME: code-org-ref
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-ref
  :ensure t
  :after (org-roam))

#+END_SRC

*** Org Tidy
<<sec:org-tidy>>

[[https://github.com/jxq0/org-tidy][org-tidy]] automatically tidies (hides) [[sec:org-mode][org-mode]] property draws.

Not currently tangled.

#+NAME: code-org-tidy
#+BEGIN_SRC emacs-lisp :tangle no
(use-package org-tidy
  :ensure t
  :after (org-mode)
  :hook
  (org-mode . org-tidy-mode))

#+END_SRC

*** Org Reactive
<<sec:org-reactive>>

[[https://dev.lepisma.xyz/git/ob-rx/][ob-rx]] makes org-babel reactive such that dependent cells are re-run when previous ones on which they depend are
modified. Still under development but included here for when its more stable.

Not currently tangled.

#+NAME: code-org-reactive
#+BEGIN_SRC emacs-lisp :tangle no
(use-package ob-rx
  :after (org all-the-icons)
  :vc (:url "https://git.sr.ht/~lepisma/ob-rx" :rev :newest))
#+END_SRC

** Org Agenda
<<sec:org-agenda>>

[[https://orgmode.org/manual/Agenda-Views.html][Org Agenda]] is a powerful tool for managing ~TODO~ tasks and calendar events. Its a core part of [[sec:org-mode][Orgmode]] and some
settings are configured there. I have picked up a couple of custom commands ([[https://github.com/jethrokuan/.emacs.d/blob/master/init.el][source]]). Which I define here.

#+NAME: code-org-agenda
#+BEGIN_SRC emacs-lisp :tangle yes
(defun ns/org-agenda-process-inbox-item ()
  "Process a single item in the org-agenda."
  (org-with-wide-buffer
   (org-agenda-set-tags)
   (org-agenda-priority)
   (call-interactively 'ns/my-org-agenda-set-effort)
   (org-agenda-refile nil nil t)))

(defvar ns/org-current-effort "1.00"
  "Current effort for agenda item.")

(defun ns/org-agenda-set-effort (effort)
  "Set the effort property for the current headline."
  (setq ns/org-current-effort effort)
  (org-agenda-check-no-diary)
  (let* ((hdmarker (or (org-get-at-bol 'org-hd-marker)
                       (org-agenda-error)))
         (buffer (marker-buffer hdmarker))
         (pos (marker-position hdmarker))
         (inhibit-read-only t)
         newhead)
    (org-with-remote-undo buffer
			  (with-current-buffer buffer
			    (widen)
			    (goto-char pos)
			    (org-show-context 'agenda)
			    (funcall-interactively 'org-set-effort nil jethro/org-current-effort)
			    (end-of-line 1)
			    (setq newhead (org-get-heading)))
			  (org-agenda-change-all-lines newhead hdmarker))))

#+END_SRC

** Org Babel
<<sec:org-babel>>

[[https://orgmode.org/worg/org-contrib/babel/][Org-babel]] started life as Babel but has been integrated into Org core since version 7.0. It provides a literate
programming environment where text and code (from many languages) can be inter-weaved to give reproducible and literate
documents that can be rendered to a range of formats via [[https://orgmode.org/manual/Exporting.html][org-export]].

#+NAME: code-org-babel
#+BEGIN_SRC emacs-lisp :tangle init.el
#+END_SRC

** Org Roam
<<sec:org-roam>>

[[https://www.orgroam.com/manual.html][org-roam]] is a Zettelkasten package for taking notes and building a "second brain" (as no one can remember
everything). It leverages an [[sec:sqlite][sqlite]] database in the background to keep track of nodes and how they link to each other.

#+name: code-org-roam
#+begin_src emacs-lisp :tangle init.el
(use-package org-roam
  :ensure t
  :defer 10
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/org-roam/main"/)
  (org-roam-dailies-directory "daily/")
  (org-roam-db-location "~/org-roam/main/org-roam.db")
  (org-roam-db-autosync-mode)
  (org-roam-completion-everywhere t)
  (org-roam-capture-templates
   '(("d" "default" plain "%?"
      :if-new (file+head "main/${slug}.org" "#+title: ${title}\n#+date: %u\n#+filetags: ${tags}\n")
      :unnarrowed t)))
  (org-roam-dailies-capture-templates
   '(("d" "default" entry "* %?"
      :target (file+head "%<%y-%m-%d>.org" "#+title: %{title}\n#+date: %u\n"))))
  ;; to add : https://www.reddit.com/r/orgroam/comments/tfcwki/org_roam_capture_create_nametitle_of_a_note/
  :hook
  (after-init . org-roam-mode)
  :bind (("C-c n a" . org-roam-alias-add)
	  ("C-c n c" . org-roam-capture)
	  ("C-c n d" . org-roam-dailies-capture-today)
	  ("C-c n f" . org-roam-node-find)
	  ("C-c n i" . org-roam-node-insert)
	  ("C-c n g" . org-roam-graph-show)
	  ("C-c n l" . org-roam-buffer-toggle)
	  ("C-c n o" . org-id-get-create)
	  ("C-c n s" . org-roam-db-sync)
	  ("C-c n t" . org-tag-add)
	  ("C-c n u s" . org-roam-ui-open)))

#+END_SRC

*** Org Roam Timestamps
<<sec:org-roam-timestamps>>

[[https://github.com/tefkah/org-roam-timestamps][org-roam-timestamps]] adds timestamps to the header of Org-roam files for ~ctime~ (creation) and ~mtime~ (modification).

#+NAME: code-org-roam-timestamps
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-roam-timestamps
  :ensure t
  :after org-roam
  :config (org-roam-timestamps-mode))

#+END_SRC

*** Org Roam BibTex
<<sec:org-roam-bibtex>>

[[https://github.com/org-roam/org-roam-bibtex][org-roam-bibtex]] integrates [[sec:org-roam][org-roam]] with [[sec:org-ref][org-ref]] and [[sec:citar][citar]].

#+NAME: code-org-roam-bibtex
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-roam-bibtex
  :ensure t
  :defer 5
  :after (org-roam)
  :config
  (require 'org-ref)) ; optional: if using Org-ref v2 or v3 citation links
#+END_SRC

*** Org Roam UI
<<sec:org-roam-ui>>

[[https://github.com/org-roam/org-roam-ui][org-roam-ui]] generates a static website showing the way in which the nodes within the [[sec:org-roam][Org-roam]] database link to each
other. I use a [[https://github.com/ikoamu/org-roam-ui-hosting][GitHub Workflow]] which emulates this and publishes to [[https://org-roam.nshephard.dev][GitHub pages]] when pushes are mirrored to GitHub Pages.

#+NAME: code-org-roam-ui
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-roam-ui
  :ensure t
  :defer 5
  :after (org-roam-bibtex-mode)
  :init
  (setq org-roam-ui-sync-theme t
	org-roam-ui-follow t
	org-roam-ui-update-on-save t
	org-roam-ui-open-on-start t))

#+END_SRC

*** Org Roam Citar
<<sec:org-roam-citar>>

[[https://github.com/emacs-citar/citar-org-roam][citar-org-roam]] improves integration between [[https://github.com/emacs-citar/citar][citar]] and [[sec:org-roam][Org-roam]].

#+NAME: code-org-roam-citar
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package citar-org-roam
  :ensure t
  :defer 5
  :after (citar org-roam)
  :config (citar-org-roam-mode))

#+END_SRC



** Org Capture
<<sec:org-capture>>

[[https://orgmode.org/manual/Capture.html#Capture][Org-capture]] is a useful method of opening transient like nested menus to capture notes in predefined files. It allows
you to specify sections and tables to which entries should be added with pre-defined templates.

#+NAME: code-org-capture
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-capture
  :ensure nil
  :after org-gtd
  :config
  (setq org-default-notes-file (concat org-directory "/notes.org"))
  (setq org-capture-templates
	'(
	  ;; Email
	  ("E" "Email"
	   entry(file+headline ,(concat org-gtd-directory "emails.org") "Emails")
	   "* TODO [#A] Reply: %a" :immediate-finish t)
	  ;; Agenda
	  ("a" "Agenda")
	  ("au" "Things to get Done" entry (file+olp "~/org/agenda.org" "Things to get Done")
	   "** TODO %U %?\n" :prepend t)
	  ("an" "Not so Urgent" entry (file+olp "~/org/agenda.org" "Not so Urgent")
	   "** TODO %U %?\n" :prepend t)
	  ("ac" "Computing" entry (file+olp "~/org/agenda.org" "Computing")
	   "** TODO %U %?\n" :prepend t)
	  ("aw" "Weekly" entry (file+olp "~/org/agenda.org" "Weekly")
	   "** TODO %U %?\n" :prepend t)
	  ("af" "Fortnightly" entry (file+olp "~/org/agenda.org" "Fortnightly")
	   "** TODO %U %?\n" :prepend t)
	  ("am" "Monthly" entry (file+olp "~/org/agenda.org" "Monthly")
	   "** TODO %U %?\n" :prepend t)
	  ("ac" "Annually" entry (file+olp "~/org/agenda.org" "Annually")
	   "** TODO %U %?\n" :prepend t)
	  ;; Bibliography
	  ;; ("b" "Bibliography" item (file+olp "~/org/references.bib")
	  ;;  "%?\n" :prepend t)
	  ;; Computing
	  ("c" "Computing")
	  ("ce" "Emacs" entry (file+olp "~/org/computing.org" "Emacs")
	   "* TODO %t %?\n" :prepend t)
	  ("cl" "Laptop" entry (file+olp "~/org/computing.org" "Laptop")
	   "* TODO %t %?\n" :prepend t)
	  ("cd" "Desktop" entry (file+olp "~/org/computing.org" "Desktop")
	   "* TODO %t %?\n" :prepend t)
	  ("cn" "Networking/Routers" entry (file+olp "~/org/computing.org" "Networking/Routers")
	   "* TODO %t %?\n" :prepend t)
	  ("cq" "Printers" entry (file+olp "~/org/computing.org" "Printers")
	   "* TODO %t %?\n" :prepend t)
	  ("cr" "RaspberryPi" entry (file+olp "~/org/computing.org" "Raspberry Pi")
	   "* TODO %t %?\n" :prepend t)
	  ("cm" "AirQuality Monitor" entry (file+olp "~/org/computing.org" "AirQuality Monitor")
	   "* TODO %t %?\n" :prepend t)
	  ("ca" "Android" entry (file+olp "~/org/computing.org" "Android")
	   "* TODO %t %?\n" :prepend t)
	  ("cp" "Programming") ;; Programming
	  ("cpb" "" entry (file+olp "~/org/computing.org" "Programming" "Bash")
	   "* TODO %t %?\n" :prepend t)
	  ("cpe" "MongoDB" entry (file+olp "~/org/computing.org" "Programming" "MongoDB")
	   "* TODO %t %?\n" :prepend t)
	  ("cpp" "Python" entry (file+olp "~/org/computing.org" "Programming" "Python")
	   "* TODO %t %?\n" :prepend t)
	  ("cpg" "Git" entry (file+olp "~/org/computing.org" "Programming" "Git")
	   "* TODO %t %?\n" :prepend t)
	  ("cpl" "LaTeX" entry (file+olp "~/org/computing.org" "Programming" "LaTeX")
	   "* TODO %t %?\n" :prepend t)
	  ("cpr" "R" entry (file+olp "~/org/computing.org" "Programming" "R")
	   "* TODO %t %?\n" :prepend t)
	  ("cv" "VPS" entry (file+olp "~/org/computing.org" "VPS")
	   "* TODO %t %?\n" :prepend t)
	  ;; Jobs
	  ("j" "Jobs")
	  ("jp" "Domestication" entry (file+olp "~/org/jobs.org" "Places to Look")
	   "+ %t %?\n" :prepend t)
	  ("jps" "Sheffield" entry (file+olp "~/org/jobs.org" "Places to Look" "Sheffield")
	   "+ %t %?\n" :prepend t)
	  ("js" "Specifics" entry (file+olp "~/org/jobs.org" "Specifics")
	   "* %t %?\n" :prepend t)
	  ;; Cats
	  ("z" "Cats")
	  ("zd" "Domestication" entry (file+olp "~/org/cats.org" "Domestication")
	   "+ %t %?\n" :prepend t)
	  ("zg" "Genetics" entry (file+olp "~/org/cats.org" "Genetics")
	   "+ %t %?\n" :prepend t)
	  ;; Drugs
	  ("d" "Drugs")
	  ("dr" "Research")
	  ("drc" "Cannabis" item (file+olp "~/org/drugs.org" "Research" "Cannabis")
	   "+ %?\n" :prepend t)
	  ("drd" "DMT" item (file+olp "~/org/drugs.org" "Research" "DMT")
	   "+ %?\n" :prepend t)
	  ("drl" "LSD" item (file+olp "~/org/drugs.org" "Research" "LSD")
	   "+ %?\n" :prepend t)
	  ("drm" "MDMA" item (file+olp "~/org/drugs.org" "Research" "MDMA")
	   "+ %?\n" :prepend t)
	  ("drp" "Psilocybin" item (file+olp "~/org/drugs.org" "Research" "Psilocybin")
	   "+ %?\n" :prepend t)
	  ("db" "Books" item (file+olp "~/org/drugs.org" "Books")
	   "+ %?\n" :prepend t)
	  ("da" "Articles")
	  ("dam" "Mushrooms" item (file+olp "~/org/drugs.org" "Articles" "Mushrooms")
	   "+ %?\n" :prepend t)
	  ("dac" "Culture" item (file+olp "~/org/drugs.org" "Articles" "Culture")
	   "+ %?\n" :prepend t)
	  ("dag" "General" item (file+olp "~/org/drugs.org" "Articles" "General")
	   "+ %?\n" :prepend t)
	  ("di" "Interviews" item (file+olp "~/org/drugs.org" "Interviews")
	   "+ %?\n" :prepend t)
	  ("dg" "Blogs / Podcasts /Videos")
	  ("dgd" "DMT" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "DMT")
	   "+ %?\n" :prepend t)
	  ("dgm" "Mushrooms" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "Mushrooms")
	   "+ %?\n" :prepend t)
	  ("dgp" "Mushrooms" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "Psychedelics")
	   "+ %?\n" :prepend t)
	  ("dgz" "Misc" item (file+olp "~/org/drugs.org" "Blogs / Podcasts / Videos" "Misc")
	   "+ %?\n" :prepend t)
	  ("dt" "Terrence McKenna" item (file+olp "~/org/drugs.org" "Terrence McKenna")
	   "+ %?\n" :prepend t)
	  ;; Exercise
	  ("e" "Exercise")
	  ("er" "Logging a run" table-line (file "~/org-roam/main/log/running_2026.org")
	   "| %U | %? | km | min + s | | |" :prepend t)
	  ("ec" "Logging a cycle" table-line (file "~/org-roam/main/log/cycling.org")
	   "| %U | %? | km | min + s | | |" :prepend t)
	  ("eh" "Logging a hike" table-line (file "~/org-roam/main/log/hiking.org")
	   "| %U | %? | km | m | min + s| |" :prepend t)
	  ("ep" "Logging Pilates" table-line (file "~/org-roam/main/log/pilates_2026.org")
	   "| %U | %? | |" :prepend t)
	  ("em" "Weight & Waist/Hip" table-line (file "~/org-roam/main/log/metrics_weight.org")
	   "| %U | %? | | | |" :prepend t)
	  ("es" "Steps" table-line (file "~/org-roam/main/log/metrics_steps.org")
	   "| %t | %? |" :prepend t)
	  ("eb" "Blood" table-line (file "~/org-roam/main/log/metrics_blood.org")
	   "| %U | %? | | | | | |" :prepend t)
	  ("et" "Training Resources") ;; Training Resources
	  ("etc" "Training Resources (Climbing)")
	  ("etcf" "Fingerboarding" item (file+olp "~/org-roam/main/training.org" "Resources" "Climbing" "Fingerboarding")
	   "+ %?\n" :prepend t)
	  ("etcl" "Lattice" item (file+olp "~/org-roam/main/training.org" "Resources" "Climbing" "Lattice")
	   "+ %?\n" :prepend t)
	  ("etcd" "Dave MacLeod" item (file+olp "~/org-roam/main/training.org" "Resources" "Climbing" "Dave Macleod")
	   "+ %?\n" :prepend t)
	  ("etch" "Hoopers Beta" item (file+olp "~/org-roam/main/training.org" "Resources" "Climbing" "Hoopers Beta")
	   "+ %?\n" :prepend t)
	  ("etcm" "Miscellaneous" item (file+olp "~/org-roam/main/training.org" "Resources" "Climbing" "Miscellaneous")
	   "+ %?\n" :prepend t)
	  ("etcs" "Shauna Coxy" item (file+olp "~/org-roam/main/training.org" "Resources" "Climbing" "Shauna Coxy")
	   "+ %?\n" :prepend t)
	  ("etr" "Running" entry (file+olp "~/org-roam/main/training.org" "Resources" "Running")
	   "+ %t %?\n" :prepend t)
	  ("etl" "Calisthenics")
	  ("etlg" "General" entry (file+olp "~/org-roam/main/training.org" "Resources" "Calisthenics" "General")
	   "+ %t %?\n" :prepend t)
	  ("etlr" "Recommended Routine" entry (file+olp "~/org-roam/main/training.org" "Resources" "Calisthenics" "Recommended
Routine")
	   "+ %t %?\n" :prepend t)
	  ("etls" "Stretching" entry (file+olp "~/org-roam/main/training.org" "Resources" "Calisthenics" "Stretching")
	   "+ %t %?\n" :prepend t)
	  ("ets" "Swimming" entry (file+olp "~/org-roam/main/training.org" "Resources" "Swimming")
	   "+ %t %?\n" :prepend t)
	  ("etx" "Research" entry (file+olp "~/org-roam/main/training.org" "Resources" "Research")
	   "+ %t %?\n" :prepend t)
	  ("eta" "Apps" entry (file+olp "~/org-roam/main/training.org" "Resources" "Apps")
	   "+ %t %?\n" :prepend t)
	  ("etd" "Apps" entry (file+olp "~/org-roam/main/training.org" "Resources" "Summarising Data")
	   "+ %t %?\n" :prepend t)
	  ;; Cooking
	  ("f" "Food & Drink")
	  ("fc" "Chinese")
	  ("fcs" "Starters" item (file+olp "~/org-roam/food_chinese.org" "Starters")
	   "+ %?\n" :prepend t)
	  ("fcr" "Rice" item (file+olp "~/org-roam/food_chinese.org" "Rice")
	   "+ %?\n" :prepend t)
	  ("fcm" "Main" item (file+olp "~/org-roam/food_chinese.org" "Main")
	   "+ %?\n" :prepend t)
	  ("fcn" "Noodles" item (file+olp "~/org-roam/food_chinese.org" "Noodles")
	   "+ %?\n" :prepend t)
	  ("fu" "Indian")
	  ("fus" "Starters" item (file+olp "~/org-roam/food_indian.org" "Starters")
	   "+ %?\n" :prepend t)
	  ("fuc" "Curries" item (file+olp "~/org-roam/food_indian.org" "Curries")
	   "+ %?\n" :prepend t)
	  ("fub" "Breads" item (file+olp "~/org-roam/food_indian.org" "Breads")
	   "+ %?\n" :prepend t)
	  ("fi" "Italian")
	  ("fip" "Pasta" item (file+olp "~/org-roam/food_italian.org" "Pasta Dishes")
	   "+ %?\n" :prepend t)
	  ("fiz" "Pizza" item (file+olp "~/org-roam/food_italian.org" "Pizza")
	   "+ %?\n" :prepend t)
	  ("fs" "Spanish" item (file+olp "~/org-roam/food_italian.org" "Pasta")
	   "+ %?\n" :prepend t)
	  ("fv" "Vegetarian" item (file+olp "~/org-roam/food_vegetarian.org" "Vegetarian")
	   "+ %?\n" :prepend t)
	  ("fw" "Web sites" item (file+olp "~/org-roam/food_drink.org" "Links")
	   "+ %?\n" :prepend t)
	  ("fb" "Books" item (file+olp "~/org-roam/food_drink.org" "Books")
	   "+ %?\n" :prepend t)
	  ;; Isla
	  ("I" "Activities for Isla")
	  ("Ie" "Educational" item (file+olp "~/org/isla.org" "Educational")
	   "+ %t %?\n" :prepend t)
	  ("Ix" "Exercise" item (file+olp "~/org/isla.org" "Exercise")
	   "+ %t %?\n" :prepend t)
	  ("If" "Fun" item (file+olp "~/org/isla.org" "Fun")
	   "+ %t %?\n" :prepend t)
	  ("Ig" "Gardening" item (file+olp "~/org/isla.org" "Gardening")
	   "+ %t %?\n" :prepend t)
	  ;; Paula
	  ("p" "Paula")
	  ("pa" "Anger" item (file+olp "~/org/paula.org" "Anger")
	   "+ %U %?\n" :prepend t)
	  ("pf" "Food" item (file+olp "~/org/paula.org" "Food")
	   "+ %U %?\n" :prepend t)
	  ("ph" "Help" item (file+olp "~/org/paula.org" "Help")
	   "+ %U %?\n" :prepend t)
	  ("pl" "Listening" item (file+olp "~/org/paula.org" "Not Listening")
	   "+ %U %?\n" :prepend t)
	  ("pt" "Tidying" item (file+olp "~/org/paula.org" "Tidying")
	   "+ %U %?\n" :prepend t)
	  ;; Reading
	  ("r" "Reading")
	  ("rb" "Books" entry (file+olp "~/org/reading.org" "Books")
	   "* TODO %?\n" :prepend t)
	  ("re" "Economics" entry (file+olp "~/org/reading.org" "Economics")
	   "* TODO %?\n" :prepend t)
	  ("rg" "Genetics" entry (file+olp "~/org/reading.org" "Genetics")
	   "* TODO %?\n" :prepend t)
	  ("rs" "Statistics")
	  ("rsd" "Data/Machine Learning/AI" entry (file+olp "~/org/reading.org" "Statistics" "Data/Machine Learning/AI")
	   "* TODO %?\n" :prepend t)
	  ("ri" "Internet")
	  ("rid" "Data/Machine Learning/AI" entry (file+olp "~/org/reading.org" "Internet" "Social Media")
	   "* TODO %?\n" :prepend t)
	  ("rm" "Miscellany" entry (file+olp "~/org/reading.org" "Miscellany")
	   "* TODO %?\n" :prepend t)
	  ;; ("s" "Org-Roam Notes" entry (file "~/work/org-roam/20220206201656-notes.org")
	  ;;  "* %U %?\n" :prepend t)
	  ;; TODO
	  ("t" "Stuff ToDo in my Life")
	  ("th" "House Tasks" entry (file+olp "~/org/todo.org" "House")
	   "* TODO %t %?\n" :prepend t)
	  ("tg" "Gardening" entry (file+olp "~/org/todo.org" "Garden")
	   "* TODO %t %?\n" :prepend t)
	  ("tv" "Campervan" entry (file+olp "~/org/todo.org" "Campervan")
	   "* TODO %t %?\n" :prepend t)
	  ("tc" "Car" entry (file+olp "~/org/todo.org" "Car")
	   "* TODO %t %?\n" :prepend t)
	  ("tg" "Bike" entry (file+olp "~/org/todo.org" "Bike")
	   "* TODO %t %?\n" :prepend t)
	  ("ts" "Stuff to Sell" entry (file+olp "~/org/todo.org" "Stuff To Sell")
	   "* TODO %t %?\n" :prepend t)
	  ;; Coronavirus
	  ("v" "Coronavirus")
	  ("va" "Air Quality" item (file+olp "~/org/coronavirus.org" "Air Quality")
	   "+ %t %?\n" :prepend t)
	  ("vc" "Collections/Streams")
	  ("vca" "The Atlantic" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Atlantic")
	   "+ %t %?\n" :prepend t)
	  ("vcb" "BMJ" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "BMJ")
	   "+ %t %?\n" :prepend t)
	  ("vcd" "David Spiegelhalter" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "David Spiegelhalter")
	   "+ %t %?\n" :prepend t)
	  ("vcg" "The Guardian" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Guardian")
	   "+ %t %?\n" :prepend t)
	  ("vcl" "The Lancet" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "The Lancet")
	   "+ %t %?\n" :prepend t)
	  ("vcn" "New Scientist" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "New Scientist")
	   "+ %t %?\n" :prepend t)
	  ("vco" "ONS" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "ONS")
	   "+ %t %?\n" :prepend t)
	  ("vcs" "Significance" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "Significance magazine")
	   "+ %t %?\n" :prepend t)
	  ("vcw" "Wired" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "Wired")
	   "+ %t %?\n" :prepend t)
	  ("vcx" "BioRxiv/MedRxiv" item (file+olp "~/org/coronavirus.org" "Collections/Streams" "BioRxiv/MedRxiv")
	   "+ %t %?\n" :prepend t)
	  ("vd" "Data" item (file+olp "~/org/coronavirus.org" "Data")
	   "+ %t %?\n")
	  ("ve" "Evolutionary Genetics" item (file+olp "~/org/coronavirus.org" "Evolutionary Genetics"))
	  ("vg" "Genetics" item (file+olp "~/org/coronavirus.org" "Genetics"))
	  ("vh" "Herd Immunity" item (file+olp "~/org/coronavirus.org" "Herd Immunity")
	   "+ %t %?\n")
	  ("vi" "Immunity / Testing / Vaccine / Treatment")
	  ("vie" "ENSEMBLE2" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "ENSEMBLE 2")
	   "+ %t %?\n" :prepend t)
	  ("vii" "Immunity" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "Immunity")
	   "+ %t %?\n" :prepend t)
	  ("vis" "Testing" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "Testing")
	   "+ %t %?\n" :prepend t)
	  ("viv" "Vaccine" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Vaccine" "Vaccine")
	   "+ %t %?\n" :prepend t)
	  ("vit" "Treatment" item (file+olp "~/org/coronavirus.org" "Immunity / Testing / Treatment" "Treatment")
	   "+ %t %?\n" :prepend t)
	  ("ve" "Independent SAGE" item (file+olp "~/org/coronavirus.org" "Independent SAGE")
	   "+ %t %?\n" :prepend t)
	  ("vl" "Long Term Outcomes" item (file+olp "~/org/coronavirus.org" "Long Term Outcomes")
	   "+ %t %?\n" :prepend t)
	  ("vh" "Mechanism" item (file+olp "~/org/coronavirus.org" "Mechanism")
	   "+ %t %?\n" :prepend t)
	  ("vhs" "Susceptibility" item (file+olp "~/org/coronavirus.org" "Mechanism" "Susceptibility")
	   "+ %t %?\n" :prepend t)
	  ("vm" "Miscellaneous" item (file+olp "~/org/coronavirus.org" "Miscellaneous")
	   "+ %t %?\n" :prepend t)
	  ("vn" "Non-Pharmaceutical Interventions")
	  ("vo" "Mortality Rates" item (file+olp "~/org/coronavirus.org" "Mortality Rates")
	   "+ %t %?\n" :prepend t)
	  ("vp" "Molecular Biology" item (file+olp "~/org/coronavirus.org" "Molecular Biology")
	   "+ %t %?\n" :prepend t)
	  ("vr" "Risk" item (file+olp "~/org/coronavirus.org" "Risk Assessment")
	   "+ %t %?\n" :prepend t)
	  ("vs" "SAGE" item (file+olp "~/org/coronavirus.org" "SAGE")
	   "+ %t %?\n" :prepend t)
	  ("vt" "Track and Trace" item (file+olp "~/org/coronavirus.org" "Track and Trace")
	   "+ %t %?\n" :prepend t)
	  ("vu" "Transmission" item (file+olp "~/org/coronavirus.org" "Transmission")
	   "+ %t %?\n" :prepend t)
	  ("vnd" "Physical Distancing" item (file+olp "~/org/coronavirus.org" "Transmission" "Physical Distancing")
	   "+ %t %?\n" :prepend t)
	  ("vnm" "Face Masks" item (file+olp "~/org/coronavirus.org" "Transmission" "Face Masks")
	   "+ %t %?\n" :prepend t)
	  ("vup" "Prevalence" item (file+olp "~/org/coronavirus.org" "Transmission" "Prevalence")
	   "+ %t %?\n" :prepend t)
	  ("vx" "Traffic")
	  ("vxc" "Cycling" item (file+olp "~/org/coronavirus.org" "Traffic" "Cycling")
	   "+ %t %?\n")
	  ("vxr" "Roads" item (file+olp "~/org/coronavirus.org" "Traffic" "Roads")
	   "+ %t %?\n")
	  ("vw" "Work" item (file+olp "~/org/coronavirus.org" "Work")
	   "+ %t %?\n")
	  ("vy" "Humour") ;; Humour
	  ("vyg" "Graphics" item (file+olp "~/org/coronavirus.org" "Humour" "Graphics")
	   "+ %t %?\n" :prepend t)
	  ("vyx" "XKCD" item (file+olp "~/org/coronavirus.org" "Humour" "XKCD")
	   "+ %t %?\n" :prepend t)
	  ("vz" "Non-Science")
	  ("vzs" "Sheffield" item (file+olp "~/org/coronavirus.org" "Non-Science" "Sheffield")
	   "+ %t %?\n" :prepend t)
	  ;; Work
	  ("w" "Work")
	  ("wj" "Reproducibilitea" entry (file+olp "~/org/gtd/reproducibilitea.org" "Reproducibilitea")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wo" "OSC" entry (file+olp "~/org/gtd/osc.org" "Open Scholarship Sheffield")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wR" "Sheffield R" entry (file+olp "~/org/gtd/sheffieldr.org" "SheffieldR")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wr" "RSE" entry (file+olp "~/org/gtd/rse.org" "RSE")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wt" "TopoStats" entry (file+olp "~/org/gtd/topostats.org" "TopoStats")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wc" "Clarity" entry (file+olp "~/org/gtd/clarity.org" "Clarity")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wC" "Carpentries Courses" entry (file+olp "~/org/gtd/carpentries.org" "Courses")
	   "** TODO %U %?\n %a" :prepend t)
	  ("wp" "PGFinder" entry (file+olp "~/org/gtd/pgfinder.org" "PGFinder")
	   "** TODO %U %?\n %a" :prepend t)
	  )))

#+END_SRC

** Org GTD
<<sec:org-gtd>>

[[https://github.com/Trevoke/org-gtd.el][org-gtd.el]] is a system for capturing, processing and organising tasks that follows the [[https://en.wikipedia.org/wiki/Getting_Things_Done][Getting Things Done]] methodology.

+ [[https://blog.jethro.dev/posts/capturing_inbox/][Org-GTD - Capturing Inbox]]
+ [[https://blog.jethro.dev/posts/processing_inbox/][Org-GTD - Processing Inbox]]
+ [[https://lucidmanager.org/productivity/getting-things-done-with-emacs/][Getting Things Done with Emacs: Manage your life with Org Mode]] (uses [[https://protesilaos.com/emacs/denote][Denote]] as a backend and standard [[sec:org-agenda][org-agenda]]
  methods)

#+NAME: code-org-gtd
#+BEGIN_SRC emacs-lisp :tangle init.el
(setq org-gtd-update-ack "3.0.0")
(use-package org-gtd
  :ensure t
  :after org
  ;; :quelpa (org-gtd :fetcher github :repo "trevoke/org-gtd.el"
  ;;                  :branch "2.0.0" :upgrade t)
  :demand t
  :custom
  ;; (org-gtd-directory stag-org-gtd-directory)
  (org-gtd-directory '"~/org/gtd")
  (org-edna-use-inheritance t)
  :config
  (org-edna-mode)
  :bind
  (("C-c d c" . org-gtd-capture)
   ("C-c d e" . org-gtd-engage)
   ("C-c d p" . org-gtd-process-inbox)
   ("C-c d n" . org-gtd-show-all-next)
   ("C-c d s" . org-gtd-show-stuck-projects)
   :map org-gtd-clarify-map
   ("C-c c" . org-gtd-organize)
   ))

#+END_SRC

* IDE and LSP

Emacs is my Integrated Development Environment (IDE) when programming and writing documents. I use a number of language
specific modes but also leverage the power of Language Server Protocol (LSP) to help with navigation, function
arguments, refactoring and so forth.

** direnv
<<sec:direnv>>

[[https://direnv.net/][direnv]] allows easy activation of virtual environment, setting custom variables or running other actions conditional on
entering a directory. Naturally there is [[https://github.com/wbolster/emacs-direnv][emacs-direnv]] which provides integration with Emacs. Pretty much always want
this available so sticking with `:config` to ensure the package is always loaded.

#+NAME: code-direnv
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package direnv
  :ensure t
  :config
  (direnv-mode))
#+END_SRC

** Code folding
*** kirigami
<<sec:kirigami>>

#+NAME: code-kirigami
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package kirigami
  :ensure t
  :after treesit-fold-mode
  :defer 2
  :bind-keymap ("C-c C-f"))

#+END_SRC


** Programming Modes

*** CSV Mode
<<sec:csv-mode>>

[[https://elpa.gnu.org/packages/csv-mode.html][csv-mode]] is a mode for working with ~.csv~ files. There is a handy ~casual-csv~ transient courtesy of Charles Choi's
excellent [[sec:casual-suite][casual]] package which provides [[sec:transient][transient]] buffers to hold your hand through the options for [[http://yummymelon.com/devnull/announcing-casual-csv.html][manipulating]] ~.csv~
files.

*TODO* This still needs some work, need to make sure the hooks suggested work correctly, don't think they do at the
moment.

#+NAME: code-csv-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package csv-mode
  :ensure t
  :defer 6
  :mode (("\\.csv" . csv-mode))
  :hook
    (csv-mode . csv-guess-set-separator)
    (csv-mode . 'csv-align-mode))

#+END_SRC

*** ESS Mode
<<sec:ess>>

#+NAME: code-ess
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ess
  :ensure t
  ;;     :requires ess-r-mode
  ;;     ess-r-package
  :init
  :mode (("/R/.*\\.q\\'"       . R-mode)
	 ("\\.[rR]\\'"         . R-mode)
	 ("\\.[rR]profile\\'"  . R-mode)
	 ("NAMESPACE\\'"       . R-mode)
	 ("CITATION\\'"        . R-mode)
	 ("\\.[Rr]out"         . R-transcript-mode)
	 ("\\.Rmd\\'"          . Rd-mode)
	 ("\\.Rd\\'"           . Rd-mode))
  :interpreter (("R" . R-mode)
		("R" . R-transcript-mode)
		("R" . Rd-mode))
  :config
  (require 'ess-r-mode)
  (require 'ess-r-package)
  (setq ess-r-backend 'lsp)
  (setq comint-input-ring-size 1000)
  (setq ess-indent-offset 2)
  (setq ess-eval-visibly-p nil)
  (setq ess-startup-directory nil)
  (setq ess-ask-for-ess-directory nil)
  (setq ess-togggle-underscore nil)
  (setq ess-eval-visibly 'nowait)
  (setq ess-use-tracebug nil)
  :hook
  (ess-mode . company-mode)
  (inferior-ess-mode . company-mode)
  :bind
  (:map ess-r-mode-map
	("_" . 'ess-insert-assign)  ;;
	("C-q" . 'ess-eval-region-or-line-and-step)
	("C-|" . " |>\n"))
  (:map inferior-ess-r-mode-map
	("_" . 'ess-insert-assign)
	("C-|" . " |>\n")))

#+END_SRC

**** ess-smart-underscore
<<sec:ess-smart-underscore>>

[[http://github.com/mlf176f2/ess-smart-underscore.el][ess-smart-underscore]] sorts out the use of ~_~ (underscore) in
[[sec:ess][ess-mode]] to insert ~<-~ by default and smartly only uses this default in certain conditions. I've not yet
found it to work consistently across buffers and <<sec:polymode>> seems to be a particular problem.

#+NAME: code-ess-smart-underscore
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ess-smart-underscore
  :ensure t
  :after (ess))

#+END_SRC

**** ess-gd
<<sec:ess-gd>>

[[https://github.com/sje30/essgd][essgd]] facilitates displaying generated plots in an Emacs buffer rather than an
external X-window.

#+NAME: code-ess-gd
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package essgd
  :ensure t)

#+END_SRC

**** quarto-mode
<<sec:quarto-mode>>

[[https://github.com/quarto-dev/quarto-emacs][quarto-emacs]] was a package released by the official
[[https://quarto.org][Quarto]] project but active development has
[[https://github.com/quarto-dev/quarto-emacs/issues/26#issuecomment-2668762979][ceasesd]] unfortunately.

Not currently tangled

#+NAME: code-quarto-mode
#+BEGIN_SRC emacs-lisp :tangle no
;; By default associated with .qmd files
(use-package quarto-mode
  :ensure t
  :mode (("\\.Rmd" . poly-quarto-mode))
  :bind (("C-c q" . quarto-preview)))

#+END_SRC

Instead I found a custom Quarto configuration from
[[https://github.com/aceross/emacs/commits/master/site-elisp/quarto-mode.el][aceross/emacs]]'s configuration and use
that. It is included below verbatim as of 2025-02-15.

#+NAME:code-quarto-mode-custom
#+BEGIN_SRC emacs-lisp :tangle yes
;; Following requires that polymode, markdown and python are all loaded/configured first
(load "~/.config/emacs/site-lisp/quarto-mode.el")
;;; quarto-mode.el --- Major mode for Quarto (qmd) documents -*- lexical-binding: t; -*-

;; Author: Aaron Ceross
;; Version: 0.2
;; Keywords: quarto, markdown, polymode
;; Package-Requires: ((emacs "26.1") (polymode "0.2.2") (markdown-mode "2.3") (ess "18.10.2"))

;;; Commentary:
;; This configuration defines a Quarto mode using polymode with inner modes for R and Python.
;; It disables tree-sitter highlighting, highlight-indent-guides, and LSP in the outer (Markdown)
;; buffer to help prevent erratic cursor behavior.
;;
;; https://github.com/aceross/emacs/commits/master/site-elisp/quarto-mode.el
;;
;; It provides:
;;   - A command (C-c C-c) to send the current code block to the appropriate REPL.
;;   - A build command (C-c C-b) to render the current Quarto document.
;;   - A preview command (C-c C-p) to preview the current document.
;;; Code:

;; (require 'polymode)
;; (require 'markdown-mode)
;; (require 'ess)        ;; for ess-r-mode
;; (require 'python)     ;; for python-mode

;; --- Disable Tree-sitter and Highlight-Indent-Guides in the Outer Mode ---
(defun ns/poly-markdown-disable-extras ()
  "Disable tree-sitter-hl, highlight-indent-guides, and LSP in the outer markdown buffer."
  (when (bound-and-true-p tree-sitter-hl-mode)
    (tree-sitter-hl-mode -1))
  (when (bound-and-true-p highlight-indent-guides-mode)
    (highlight-indent-guides-mode -1))
  ;; Optionally disconnect LSP in the outer buffer if active.
  (when (bound-and-true-p lsp-mode)
    (lsp-disconnect)))
(add-hook 'poly-markdown-mode-hook #'ns/poly-markdown-disable-extras)

;; --- Define R Innermode ---
(define-innermode poly-quarto-r-innermode
		  :mode 'ess-r-mode
		  :head-matcher "^```{[rR].*}\\(?:\n\\|$\\)"
		  :tail-matcher "^```\\s-*$"
		  :head-mode 'host
		  :tail-mode 'host)

;; --- Define Python Innermode ---
(define-innermode poly-quarto-python-innermode
		  :mode 'python-mode
		  :head-matcher "^```{[pP]ython.*}\\(?:\n\\|$\\)"
		  :tail-matcher "^```\\s-*$"
		  :head-mode 'host
		  :tail-mode 'host)

;; --- Define the Quarto Polymode ---
(define-polymode poly-quarto-mode poly-markdown-mode
		 "Polymode for Quarto (qmd) files.
Automatically switches to the appropriate mode for code blocks."
		 :lighter " Quarto"
		 :innermodes '(poly-quarto-r-innermode
			       poly-quarto-python-innermode))

;; --- Command: Send Current Code Block to REPL ---
(defun quarto-send-code-block-to-repl ()
  "Send the current Quarto code block to the appropriate REPL.
This command only works if the point is in a code block (inner region).
For R, uses ESS; for Python, uses the Python shell."
  (interactive)
  (if (not (member major-mode '(ess-r-mode python-mode)))
      (message "Not in a code block")
    (let (lang start end code)
      (save-excursion
        (when (re-search-backward "^```{\\([^,}]+\\)" nil t)
          (setq lang (downcase (car (split-string (match-string 1) "[, ]+" t))))
          (forward-line)
          (setq start (point))
          (when (re-search-forward "^```\\s-*$" nil t)
            (setq end (match-beginning 0))
            (setq code (buffer-substring-no-properties start end)))))
      (if (not (and lang code))
          (message "No valid code block found.")
        (cond
         ((string= lang "r")
          (if (fboundp 'ess-eval-linewise)
              (ess-eval-linewise code)
            (message "ESS not available.")))
         ((string= lang "python")
          (if (fboundp 'python-shell-send-string)
              (python-shell-send-string code)
            (message "Python shell not available.")))
         (t (message "Unsupported language: %s" lang)))))))

;; --- Command: Build Quarto Document ---
(defcustom quarto-build-flags ""
  "Extra flags to pass to the Quarto build command."
  :group 'quarto
  :type 'string)

(defun quarto-build-document ()
  "Build the current Quarto document using Quarto.
Runs: `quarto render <current-file> <quarto-build-flags>` asynchronously."
  (interactive)
  (let* ((file (buffer-file-name))
         (cmd (format "quarto render %s %s"
                      (shell-quote-argument file)
                      quarto-build-flags)))
    (message "Executing: %s" cmd)
    (compilation-start cmd 'compilation-mode)))

;; --- Command: Preview Quarto Document ---
(defcustom quarto-preview-flags ""
  "Extra flags to pass to the Quarto preview command."
  :group 'quarto
  :type 'string)

(defun quarto-preview-document ()
  "Preview the current Quarto document using Quarto.
Runs: `quarto preview <current-file> <quarto-preview-flags>` asynchronously."
  (interactive)
  (let* ((file (buffer-file-name))
         (cmd (format "quarto preview %s %s"
                      (shell-quote-argument file)
                      quarto-preview-flags)))
    (message "Executing: %s" cmd)
    (compilation-start cmd 'compilation-mode)))

;; --- Bind the Commands in poly-quarto-mode ---
(define-key poly-quarto-mode-map (kbd "C-c C-c") 'quarto-send-code-block-to-repl)
(define-key poly-quarto-mode-map (kbd "C-c C-b") 'quarto-build-document)
(define-key poly-quarto-mode-map (kbd "C-c C-p") 'quarto-preview-document)

;; --- Improve Cursor Stability: Disable Electric Indent in Inner Modes ---
(add-hook 'ess-r-mode-hook
          (lambda () (setq-local electric-indent-inhibit t)))
(add-hook 'python-mode-hook
          (lambda () (setq-local electric-indent-inhibit t)))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.qmd\\'" . poly-quarto-mode))

(provide 'quarto-mode)
;;; quarto-mode.el ends here

#+END_SRC

**** r-autoyas
<<sec:r-autoyas>>

[[https://github.com/mattfidler/r-autoyas.el][r-autoyas]] is something I appear to have used at some point in the past but I've noted I disabled it in 2023-01-28 along
with a link to [[https://github.com/emacs-ess/ESS/issues/967#issuecomment-541276597][this issue]]. For now it is /not/ included when tangling my configuration.

#+NAME: code-r-autoyas
#+BEGIN_SRC emacs-lisp :tangle no
(use-package r-autoyas
  :ensure t
  :hook
  (ess-mode . r-autoyas-ess-activate))

#+END_SRC

*** jq Mode
<<sec:jq-mode>>

#+NAME: code-jq-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package jq-mode
  :ensure t
  :defer 5
  :mode ("\\.json\\'" . jq-mode)
  :custom
  (add-to-list 'auto-mode-alist '("\\.json$" . jq-mode))
  (add-to-list 'auto-mode-alist '("\\.jq$" . jq-mode))
  )
#+END_SRC

*** JS Mode
<<sec:js>>

I (thankfully) don't write much JavaScript but add the file extensions below to the appropriate modes.

#+NAME: code-js
#+BEGIN_SRC emacs-lisp :tangle init.el
(add-to-list 'auto-mode-alist '("\\.js" . js-mode))
(add-to-list 'auto-mode-alist '("\\.json" . json-mode))
(add-to-list 'auto-mode-alist '("\\.svelte" . js-ts-mode))
#+END_SRC

*** Just Mode
<<sec:just>>

[[https://github.com/leon-barrett/just-mode.el][just-mode]] is for editing [[https://just.systems/man/en/][just]] files.

#+NAME: code-just
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package just-mode
  :ensure t
  :defer 0.5)

#+END_SRC

*** Latex Mode
<<sec:latex>>

Don't use LaTeX much these days but like to keep things available.

+ [[https://blog.karssen.org/2011/08/21/reftex-how-could-i-have-missed-this/][Enable RefTex on startup]] - also has a function and hook enabled under ~org-settings.el~.
+ [[https://github.com/jsinglet/latex-preview-pane][LaTeX Preview Pane]]
+ [[https://superuser.com/a/142468][Run pdflatex]]

#+NAME: code-latex
#+BEGIN_SRC emacs-lisp :tangle init.el
(add-hook 'LaTeX-mode-hook 'turn-on-reftex)
(add-hook 'latex-mode-hook 'turn-on-reftex)
;;(latex-preview-pane-enable)
(setq latex-run-command "pdflatex")

#+END_SRC

**** latex-extra
<<sec:latex-extra>>

[[https://github.com/Malabarba/latex-extra][latex-extra]] "/defines extra commands and keys for LaTeX-mode/".

#+NAME: code-latex-extra
#+BEGIN_SRC emacs-lisp :tangle no
(use-package latex-extra
  :ensure t
  :defer 3
  :after (latex-mode)
  :hook
  (LaTeX-mode-hook . 'latex-extra-mode)
)
#+END_SRC

*** Markdown Mode
<<sec:markdown>>

[[https://github.com/jrblevin/markdown-mode][markdown-mode]] is for editing Markdown files.

#+NAME: code-markdown
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package markdown-mode
  :ensure t
  :mode ("\\.md\\'" . gfm-mode)
  :hook (markdown-mode . auto-fill-mode)
  :init (setq markdown-command "pandoc")
  :bind (:map markdown-mode-map
              ("C-c C-m" . markdown-do)))

#+END_SRC

**** markdown-ts-mode
<<sec:markdown-ts-mode>>

[[https://github.com/LionyxML/markdown-ts-mode][markdown-ts-mode]] provides [[sec:treesitter][Tree Sitter]] support for ~.md~ files.

The following /isn't/ tangled and needs checking
#+NAME: code-markdown-ts-mode
#+BEGIN_SRC emacs-lisp :tangle no
(use-package markdown-ts-mode
  :ensure t
  :after (markdown-mode)
  :mode ("\\.md\\'" . markdown-ts-mode)
  :custom
  (add-to-list 'treesit-language-source-alist '(markdown "https://github.com/ikatyang/tree-sitter-markdown" "master"
"src")))

#+END_SRC

*** Mermaid Mode
<<sec:mermaid>>

[[https://github.com/abrochard/mermaid-mode/][mermaid-mode]] provides support for [[https://mermaid.js.org/][Mermaid.js]] a code-based, declarative diagramming system.

#+NAME: code-mermaid
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package mermaid-mode
  :ensure t
  :defer 10)

#+END_SRC

**** ob-mermaid
<<sec:ob-mermaid>>

[[https://github.com/arnm/ob-mermaid][ob-mermaid]] provides org-babel exporting of mermaid diagrams using [[https://github.com/mermaid-js/mermaid-cli][mermaid-cli]].

#+NAME: code-ob-mermaid
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ob-mermaid
  :ensure t
  :after (mermaid-mode))

#+END_SRC

**** mermaid-ts-mode
<<sec:mermaid-ts-mode>>

[[https://github.com/JonathanHope/mermaid-ts-mode][mermaid-ts-mode]] provides [[sec:treesitter][Tree Sitter]] support for Mermaid.

#+NAME: code-mermaid-ts-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package mermaid-ts-mode
  :ensure t
  :after (mermaid-mode))

#+END_SRC

*** Nix Mode
<<sec:nix>>

I dabbled with [[https://nixos.org/][NixOS]] in the past and used these packages to help with writing nix packages and code.

**** nixfmt
<<sec:nixfmt>>

[[https://github.com/purcell/emacs-nixfmt][nixfmt]]

#+NAME: code-nixfmt
#+BEGIN_SRC emacs-lisp :tangle no
(use-package nixfmt
  :ensure t
  :defer 3
)

#+END_SRC

**** nix-ts-mode
<<sec:nix-ts-mode>>

[[https://github.com/nix-community/nix-ts-mode][nix-ts-mode]] provides [[sec:treesitter][Tree Sitter]] support for ~.nix~ files.

#+NAME: code-nix-ts-mode
#+BEGIN_SRC emacs-lisp :tangle no

(use-package nix-ts-mode
  :ensure t
  :mode "\\.nix\\'")

#+END_SRC

**** agenix
<<sec:agenix>>

[[https://github.com/t4ccer/agenix.el][agenix]] is for working with secrets.

#+NAME: code-agenix
#+BEGIN_SRC emacs-lisp :tangle no
(use-package agenix
  :ensure t
  :mode "\\.age\\'")

#+END_SRC

*** Python Mode
<<sec:python>>

[[https://gitlab.com/python-mode-devs/python-mode][Python mode]] is a major mode for editing Python files. I don't do much to customise this, the following is loaded _after_
[[sec:pyvenv][pyvenv]]...

+ Disable a guess indent message.
+ Enables [[https://ipython.org/][IPython]] as the ~python-shell-interpreter~ and sets some arguments.
+ Defines two custom skeletons, the first to insert a ~print()~ statement with an f-string to show the value of a
  parameters (useful for debugging code). The second to insert a ~@pytest.mark.parametrize()~ test function (which is
  ultimately redundant since I have a [[sec:yasnippet][YASnippet]] template to do the same thing).
+ Maps some keybindings to make it easy to run some short-cuts such as ~python-test-dispatch~, ~pylint~,
  ~blacken-buffer~ and insert some of the common ~python-skeleton~'s.

I used to define a couple of [[https://emacs.stackexchange.com/questions/80320/defining-custom-python-skeletons][skeletons]] here but only use the ~print~ one these days as I use [[sec:yasnippet][YASnippet]] for inserting
most templates these days (I should probably shift over but have the muscle memory that binds ~print~ to ~C-c P~).

#+NAME: code-python
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package python
  :after (pyvenv)
  :ensure t
  :defer 1
  :config
  ;; Remove guess indent python message
  (setq python-indent-guess-indent-offset-verbose nil
	python-shell-interpreter "ipython"
	python-shell-interpreter-args "-i --simple-prompt"
	python-environment-directory venv-location)
  (add-to-list 'python-shell-completion-native-disabled-interpreters "ipython")
  ;; Define a skeleton for printing
  (python-skeleton-define print
			  "Insert a print statement that will show the value of the argument."
			  "Enter the variable/object name: "
			  "print(f'\\n{" str "=}\\n')")
  :bind (:map python-mode-map
	      ("C-c p t" . python-pytest-dispatch)
	      ("C-c p l" . pylint)
	      ("C-c p y" . pylint-insert-ignore-comment)
	      ("C-c p n" . numpydoc-generate)
	      ("C-c p b" . blacken-buffer)
	      ("C-c p r" . ruff-format-buffer)
	      ("C-c p v" . pyvenv-workon)
	      ("C-c p T c" . python-skeleton-class)
	      ("C-c p T d" . python-skeleton-def)
	      ("C-c p T f" . python-skeleton-for)
	      ("C-c p T i" . python-skeleton-if)
	      ("C-c p T m" . python-skeleton-import)
	      ("C-c P" . python-skeleton-print)
	      ("C-c p T t" . python-skeleton-try)
	      ("C-c p T T" . python-skeleton-parameterized-test)
	      ("C-c p T w" . python-skeleton-while)))

#+END_SRC

**** Virtual Environments

I use two packages to manage virtual environments in conjunction with [[sec:direnv][~direnv~]]. For general Python virtual environments
I use [[https://github.com/jorgenschaefer/pyvenv][pyvenv]] which allows me to define on a per-host basis the location of virtual environments which are defined
globally, typically I use ~~/.virtualenvs~ which I will activate via a project/repository specific ~.envrc~ file which
[[sec:direnv][direnv]] takes care of activating when I switch to the project directory. Recently I've started using [[https://docs.astral.sh/uv/][uv]] to manage
packages and projects and so have also added [[https://github.com/z80dev/uv-mode][uv-mode]] to my configuration to take care of activating project specific
virtual environments which reside in the ~.venv~ directory created by ~uv~ within the project directory itself.

***** envdir

***** pyvenv
<<sec:pyvenv>>

#+NAME: code-pyvenv
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package pyvenv
  :ensure t
  :defer 1
  :config
  ;; Setting work on to easily switch between environments
  (setenv "WORKON_HOME" (expand-file-name "~/.virtualenvs/"))
  (pyvenv-mode 1)
  ;; Display virtual envs in the menu bar
  (setq pyvenv-menu t
	venv-byhost
	'(("kimura" . "~/.virtualenvs/")
	  ("fisher" . "~/.virtualenvs/")
	  ("haldane" . "~/.virtualenvs/")
	  ("ovh" . "~/.virtualenvs/")
	  ("alarmpi" . "~/.virtualenvs/")
	  ("alarmpi-4b" . "~/.virtualenvs/"))
	venv-location (cdr
		       (assoc system-name venv-byhost))
	default-venv-byhost
	'(("kimura" . "~/.virtualenvs/default")
	  ("fisher" . "~/.virtualenvs/python3_9")
	  ("haldane" . "~/.virtualenvs/default")
	  ("ovh" . "~/.virtualenvs/default")
	  ("alarmpi" . "~/.virtualenvs/default")
	  ("alarmpi-4b" . "~/.virtualenvs/default"))
	default-venv (cdr
		      (assoc system-name default-venv-byhost))
	python-environment-directory venv-location)
  ;; Restart the python process when switching environments
  (add-hook 'pyvenv-post-activate-hooks (lambda ()
					  (pyvenv-restart-python)))
  :hook (python-mode . pyvenv-mode)
  (after-init-hook . (pyvenv-workon default-env))
  )
#+END_SRC

***** pyvenv-auto
<<sec:pyvenv-auto>>

[[https://github.com/ryotaro612/pyvenv-auto][pyvenv-auto]] "/automatically activates a Python venv with pyvenv. When you open a file in python-mode, it searches for
the venv directory near the file, and activates it./". As I use [[sec:direnv][direnv]] and am migrating to [[sec:uv-mode][uv]] I've stopped using this.

Not currently tangled.

#+NAME: code-pyvenv
#+BEGIN_SRC emacs-lisp :tangle no
(use-package pyvenv-auto
  :ensure t
  :after (python-mode)
  :hook ((python-mode . pyvenv-auto-run)))

#+END_SRC

***** uv-mode
<<sec:uv-mode>>

[[https://github.com/z80dev/uv-mode][uv-mode]] "/provides seamless integration between [[https://docs.astral.sh/uv][uv]] and Emacs ~python-mode~/".

#+NAME: code-uv-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package uv-mode
  :ensure t
  :defer 0.5
  :after (python-mode)
  :hook (python-mode . uv-mode-auto-activate-hook))

#+END_SRC

**** Additional packages

***** Blacken
<<sec:blacken>>

[[https://black.readthedocs.io/en/stable/][Black]] is "/the uncompromising code formatter/" and Emacs has the [[https://github.com/pythonic-emacs/blacken][blacken]] package which allows applying Black formatting
to a buffer via keybinding (see above configuration option under [[sec:python][Python]]) or automatically on saving.

#+NAME: code-blacken
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package blacken
  :ensure t
  :defer 0.5
  :after (python-mode)
  :bind (:map python-mode-map
          ("C-c p b" . blacken-buffer))
  :custom
  (blacken-line-length 120)
  :hook (python-mode . blacken-mode))
#+END_SRC

***** Numpydoc
<<sec:numpydoc>>

[[https://github.com/douglasdavis/numpydoc.el][numpydoc.el]] is a great package that simplifies writing docstrings for functions.

I've made a minor [[https://github.com/douglasdavis/numpydoc.el/pull/20][contribution]] to it in so much as it didn't write docstrings that were compliant with [[https://numpydoc.readthedocs.io/en/latest/validation.html][Numpydoc
validation]] rules.

#+NAME: code-numpydoc
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package numpydoc
  :ensure t
  :defer 0.5
  :after (python-mode)
  :bind (:map python-mode-map
	      ("C-c p n" . numpydoc-generate))
  :custom
  (numpydoc-prompt-for-input t)
  (numpydoc-insert-examples-block 0)
  ;; Awaiting merge
  ;; (numpydoc-newline-after-opening-quotes t)
  (numpydoc-insert-raises-block 0))
#+END_SRC

***** Pylint
<<sec:pylint>>

There is an orphaned [[https://github.com/emacsorphanage/pylint][pylint]] package which is referenced for completeness. Typically I defer running [[https://pylint.org][Pylint]] to a
[[https://pre-commit.com][Pre-commit]] hook.

#+NAME: code-pylint
#+BEGIN_SRC emacs-lisp :tangle no
(use-package pylint
  :ensure t
  :defer 0.5
  :after (python-mode)
  :bind (:map python-mode-map
	  ("C-c p l" . pylint))
  :hook (python-mode . pylint-add-menu)
  (python-mode . add-key-bindings))

#+END_SRC

***** Pytest
<<sec:pytest>>

[[https://pytest.org][Pytest]] is well supported via [[https://github.com/wbolster/emacs-python-pytest][emacs-python-pytest]]. I've bound ~python-pytest-dispatch~ to ~C-c p t~ which brings up a
transient buffer with options for running ~pytest~ on a given file or function at the cursor location. This transient
buffer is highly configurable and I add some options for running regression tests (both [[https://pytest-regtest.readthedocs.io/en/latest/][pytest-regtest]] and [[https://syrupy-project.github.io/syrupy/][syrupy]] as
well as profiling).

#+NAME: code-pytest
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package python-pytest
  :ensure t
  :defer 0.5
  :after (python-mode)
  :bind (:map python-mode-map
	      ("C-c p t" . python-pytest-dispatch))
  :custom
  (transient-append-suffix
    'python-pytest-dispatch
    '(0)
    ["Regression Tests"
     ("-r" "Reset regression tests" "--regtest-reset")
     ("--su" "Reset Syrupy snapshot" "--snapshot-update")
     ("--tee" "Print results" "--regtest-tee")
     ("--nodiff" "Suppress output" "--regtest-nodiff")
     ("--endings" "Do not strip whitespaces at end of recorded lines" "--regtest-consider-line-endings")])
  (transient-append-suffix
    'python-pytest-dispatch
    '(0)
    ["Profiling"
     ("-P" "Generate profiling information" "--profile")
     ("--profile-svg" "Generate profiling graph" "--profile-svg")
     ("--pstats-dir" "Configure the dump directory of profile data files" "--pstats-dir")
     ("--element-number" "Defines how many elements will display in a result" "--element-number")
     ("--strip-dirs" "Configure to show/hide the leading path information from file names" "--strip-dirs")])
  )
#+END_SRC

***** Ruff
<<sec:ruff>>

[[https://docs.astral.sh/ruff][Ruff]] is a fast Python linter that is subsuming Black, Flake8, Yapf and Pylint.

+ [[https://github.com/scop/emacs-ruff-format][emacs-ruff-format]]
+ [[https://github.com/christophermadsen/emacs-lazy-ruff][emacs-lazy-ruff]]
+ [[https://github.com/erickgnavar/flymake-ruff][flymake-ruff]]

#+NAME: code-ruff
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ruff-format
  :ensure t
  :defer 0.5
  :after (python-mode)
  :bind (:map python-mode-map
	  ("C-c p r" . ruff-format-buffer))
  :after (python-mode)
  :hook (python-mode . ruff-format-on-save-mode))

(use-package lazy-ruff
  :ensure t
  :defer 0.5
  :after (python-mode)
  :bind (("C-c p l" . lazy-ruff-lint-format-dwim)) ;; keybinding
  :config
  (lazy-ruff-mode-global-toggle t)) ;; Enable the lazy-ruff minor mode globally

(use-package flymake-ruff
  :ensure t
  :defer 0.5
  :after (python-mode)
  ;; :hook (python-mode . flymake-ruff-load))
  :hook (lsp-managed-mode . flymake-ruff-load))

#+END_SRC

***** Yapf
<<sec:yapf>>

[[https://github.com/JorisE/yapfify][Yapfify]] can be used to apply Googles [[https://github.com/google/yapf][yapf]] formatting. I don't use this so the following section is not tangled to my
config but is included on the off-chance I change my mind or someone else finds it useful.

#+NAME: code-yapf
#+BEGIN_SRC emacs-lisp :tangle no
(use-package yapfify
  :ensure t
  :defer t
  :after (python-mode)
  :hook (python-mode . yapf-mode))

#+END_SRC

*** Rust Mode
<<sec:rust>>

Rust is something I intend to learn at some point (right after I've learnt Elisp!). The various packages here integrate
with [[sec:lsp-mode][lsp-mode]].

**** rust-mode
<<sec:rust-mode>>

[[https://github.com/rust-lang/rust-mode][rust-mode]] for editing [[https://rust-lang.org/][Rust]] source files (~.rs~).

#+NAME: code-rust
#+BEGIN_SRC emacs-lisp :tangle no
;; https://github.com/rust-lang/rust-mode
(use-package rust-mode
  :ensure t
  :defer 0.5
  :custom
  (add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-mode))
  (rust-mode-treesitter-derive t)
  ;; :hook
  ;; (rust-mode . (lambda () (prettify-symbols-mode)))
  )

#+END_SRC

**** rustic
<<sec:rustic>>

[[https://github.com/emacs-rustic/rustic][rustic]] is based on [[sec:rust-mode][rust-mode]] and provides additional features such as automatic LSP configuration, [[sec:cargo][Cargo]] popups, async
with [[sec:org-babel][Org Babel]] and more.

#+NAME: code-rustic
#+BEGIN_SRC emacs-lisp :tangle no
(use-package rustic
  :ensure t
  :defer 3
  :custom
  (rustic-format-on-save t)
  (rustic-cargo-use-last-stored-arguments t))
#+END_SRC

**** Cargo
<<sec:cargo>>

 [[https://doc.rust-lang.org/cargo/][Cargo]] is the Rust package manager.

***** cargo.el
<<sec:cargo-el>>

[[https://github.com/kwrooijen/cargo.el][cargo.el]] is in maintenance mode but provides a set of key combinations to perform various tasks.
#+NAME: code-cargo-el
#+BEGIN_SRC emacs-lisp :tangle no
body
#+END_SRC

***** cargo-mode
<<sec:cargo-mode>>

[[https://github.com/ayrat555/cargo-mode][cargo-mode]] is a minor mode for dynamically selecting commands from the Rust package manager.

#+NAME: code-cargo-mode
#+BEGIN_SRC emacs-lisp :tangle no
;; https://github.com/ayrat555/cargo-mode
(use-package cargo-mode
  :ensure t
  :defer 0.5
  :hook
  (rust-mode . cargo-minor-mode)
  :config
  (setq compulation-scroll-output t))

#+END_SRC

*** Sqlite Mode
<<sec:sqlite>>

Emacs can be compiled with [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Database.html][built-in support for SQLite databases]]. I have picked up one [[https://christiantietze.de/posts/2024/01/emacs-sqlite-mode-open-sqlite-files-automatically/][custom function]] along the way.

#+NAME: code-sqlite
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package sqlite-mode
  :custom
  (defun ns/sqlite-view-file-magically ()
    "Runs `sqlite-mode-open-file' on the file name visited by the
current buffer, killing it."
    (require 'sqlite-mode)
    (let ((file-name buffer-file-name))
      (kill-current-buffer)
      (sqlite-mode-open-file file-name)))
    (add-to-list 'magic-mode-alist '("SQLite format 3\x00" . ns/sqlite-view-file-magically)))

#+END_SRC

**** sqlite-mode-extras
<<sec:sqlite-mode-extras>>

[[https://github.com/xenodium/sqlite-mode-extras][sqlite-mode-extras]] provides a suite of extra functions which extend the built-in.

#+NAME: code-sqlite-mode-extras
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package sqlite-mode-extras
  :bind (:map
          sqlite-mode-map
          ("n" . next-line)
          ("p" . previous-line)
          ("b" . sqlite-mode-extras-backtab-dwim)
          ("f" . sqlite-mode-extras-tab-dwim)
          ("+" . sqlite-mode-extras-add-row)
          ("D" . sqlite-mode-extras-delete-row-dwim)
          ("C" . sqlite-mode-extras-compose-and-execute)
          ("E" . sqlite-mode-extras-execute)
          ("S" . sqlite-mode-extras-execute-and-display-select-query)
          ("DEL" . sqlite-mode-extras-delete-row-dwim)
          ("g" . sqlite-mode-extras-refresh)
          ("<backtab>" . sqlite-mode-extras-backtab-dwim)
          ("<tab>" . sqlite-mode-extras-tab-dwim)
          ("RET" . sqlite-mode-extras-ret-dwim)))

#+END_SRC

*** Yaml Mode
<<sec:yaml>>

[[https://github.com/yoshiki/yaml-mode][yaml-mode]] is a bit dated but works ok. I think a lot of the functionality I get when working with YAML files comes from
the LSP protocol but I retain this in my configuration for now.

#+NAME: code-yaml
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package yaml-mode
  :init
  (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode))
  (add-to-list 'auto-mode-alist '("\\.cff\\'" . yaml-mode)))
#+END_SRC

*** Polymode Mode
<<sec:PolyMode>>

**** polymode
<<sec:polymode>>

#+NAME: code-polymode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package polymode
  :ensure t
  :custom
  (add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
  (add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
  (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode)))

#+END_SRC

***** Miscellaneous

I had the following code lingering in my init on migrating to literate configuration and didn't want to lose it on the
off-chance it might be needed.

Not tangled
#+NAME: code-polymode-misc
#+BEGIN_SRC emacs-lisp :tangle no
;;; Hopefully work around the freezes from https://goo.gl/l6mtG5
(defun ns/markdown-match-propertized-text (property last)
  "Match text with PROPERTY from point to LAST.
Restore match data previously stored in PROPERTY."
  (let ((saved (get-text-property (point) property))
        pos)
    (unless saved
      (setq pos (next-single-char-property-change (point) property nil last))
      (setq saved (get-text-property pos property)))
    (when saved
      (set-match-data saved)
      ;; Step at least one character beyond point. Otherwise
      ;; `font-lock-fontify-keywords-region' infloops.
      (goto-char (min (1+ (max (match-end 0) (point)))
                      (point-max)))
      saved)))
;;; This hasn't worked, I still get lock-ups, but perhaps a little less frequently.
;;; Found another thread at https://stat.ethz.ch/pipermail/ess-help/2016-January/010886.html
;;;
;;; Other pages on installing Polymode are...
;;;
;;; http://johnstantongeddes.org/open%20science/2014/03/26/Rmd-polymode.html
;;; http://simon.bonners.ca/bonner-lab/wpblog/?p=142
;;;
;;; Python Polymode (Markdown + Python)
;;;
;;; https://stackoverflow.com/questions/52489905/emacs-polymode-for-markdown-and-python
;;; https://emacs.stackexchange.com/questions/20437/polymode-with-python-and-latex-mode/
;;;
;;; Further discussion and working solution at...
;;;
;;; https://github.com/polymode/polymode/issues/180



;; Python/Markdown
(defcustom pm-inner/noweb-python
  (clone pm-inner/noweb
         :name "noweb-python"
         :mode 'python-mode)
  "Noweb for Python"
  :group 'poly-innermodes
  :type 'object)

(define-polymode poly-pweave-mode poly-markdown-mode
		 :innermodes '(pm-inner/noweb-python :inherit))

(add-to-list 'auto-mode-alist '("\\.pymd" . poly-pweave-mode))


;; Python/LaTeX (see https://emacs.stackexchange.com/a/20446)
(defcustom pm-inner/python
  (clone pm-inner/noweb
	 :name "python"
	 :mode 'python-mode
	 :head-matcher  "\\\\begin{pycode}"
	 :tail-matcher  "\\\\end{pycode}")
  "Python inline code."
  :group 'innermodes
  :type 'object)

(defcustom pm-poly/latex-python
  (pm-polymode-one :name "latex-python"
		   :hostmode 'pm-host/latex
		   :innermode 'pm-inner/python)
  "latex-python typical polymode."
  :group 'polymodes
  :type 'object)

(define-polymode poly-latex+python-mode
		 :hostmode 'pm-host/latex
		 :innermodes '(pm-inner/python))
(add-to-list 'auto-mode-alist '("\\.texw$" . poly-latex+python-mode))

#+END_SRC

**** poly-markdown
<<sec:poly-markdown>>

#+NAME: code-poly-markdown
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package poly-markdown
  :ensure t
    :defer 0.5
    :after (polymode))

#+END_SRC

**** poly-noweb
<<sec:poly-noweb>>

#+NAME: code-poly-noweb
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package poly-noweb
  :ensure t
    :defer 0.5
    :after (polymode))

#+END_SRC

**** poly-org
<<sec:poly-org>>

#+NAME: code-poly-org
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package poly-org
  :ensure t
    :defer 0.5
    :after (polymode))

#+END_SRC

**** poly-R
<<sec:poly-R>>

#+NAME: code-poly-R
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package poly-R
  :ensure t
    :defer 0.5
    :after (polymode))

#+END_SRC

**** poly-rst
<<sec:poly-rst>>

#+NAME: code-poly-rst
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package poly-rst
  :ensure t
    :defer 0.5
    :after (polymode))

#+END_SRC
** LSP Mode
<<sec:lsp>>

Whilst Eglot is built-in to Emacs since ~v30-ish I started using [[https://emacs-lsp.github.io/lsp-mode/][LSP Mode]] before this and have stuck with it.

*** mason
<<sec:mason>>

[[https://github.com/deirn/mason.el][mason]] solves a major headache with using either [[sec:lsp-mode][lsp-mode]] or the built-in ~eglot~ which is that external language servers
are required to do the leg work (aka "magic") in the background. Many operating systems have these in their package
manager or they can be manually installed (e.g. [[https://github.com/ltex-plus/ltex-ls-plus][ltex-ls-plus]]). ~mason~ solves this by being an installed to the
[[https://github.com/mason-org/mason-registry][mason-registry]] which packages and [[https://mason-registry.dev/registry/list][lists]] pretty much all the language servers going.

Language servers I've installed with varying success (see [[https://github.com/deirn/mason.el/issues/2][issue #2]]).

+ [[https://github.com/pappasam/jedi-language-server][jedi-language-server]] for [[sec:python][Python]]
+ [[https://github.com/wader/jq-lsp][jq-lsp]] for [[sec:jq-mode][~jq~]]
+ [[https://ltex-plus.github.io/ltex-plus/][ltex-ls-plus]] for [[sec:latex][LaTeX]], [[sec:org-mode][org-mode]] and more.
+ [[https://github.com/DavidAnson/markdownlint-cli2][markdownlint-cli2]] for [[sec:markdown][markdown]]
+ [[https://github.com/python/mypy][mypy]]
+ [[https://github.com/fsouza/prettierd][prettierd]]
+ [[https://www.pydocstyle.org/][pydocstyle]] for [[sec:python][Python]]
+ [[https://pypi.org/project/pylint/][pylint]] for [[sec:python][Python]]
+ [[https://github.com/astral-sh/ruff/][ruff]] for [[sec:python][Python]]
+ [[https://github.com/REditorSupport/languageserver][r-languageserver]]
+ [[https://github.com/rust-lang/rust-analyzer][rust-analyzer]]
+ [[https://www.shellcheck.net/][shellcheck]]
+ [[https://github.com/quarylabs/sqruff][sqruff]]
+ [[https://docs.astral.sh/uv/][uv]] for [[sec:python][Python]]
+ [[https://github.com/redhat-developer/yaml-language-server][yaml-language-server]]
+ [[https://github.com/adrienverge/yamllint][yamllint]]

*TODO* - How to automate installation of language servers? ~mason-install~ as defined in the commented sections below
 doesn't work.
#+NAME: code-mason
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package mason
    :ensure t
    :defer 0.5
    :hook
    (after-init-hook . mason-ensure))
;; (mason-install('jedi-language-server))
;; (mason-install jq-lsp)
;; (mason-install ltex-ls-plus)
;; (mason-install markdownlint-cli2)
;; (mason-install mypy)
;; (mason-install prettierd)
;; (mason-install pydocstyle)
;; (mason-install pylint)
;; (mason-install ruff)
;; (mason-install r-languageserver)
;; (mason-install rust-analyzer)
;; (mason-install shellcheck)
;; (mason-install yaml-language-server)
;; (mason-install yamllint)

#+END_SRC

<<sec:mason>>

*** lsp-mode
<<sec:lsp-mode>>

#+NAME: code-lsp-mode
#+BEGIN_SRC emacs-lsp :tangle init.el
 (use-package lsp-mode
  :ensure t
  :defer t
  :commands (lsp lsp-deferred)
  :custom (lsp-keymap-prefix "s-l")
  (lsp-disabled-clients '(pylsp pyls))
  ;; :init (setq lsp-keymap-prefix "s-l")
  :hook ((R-mode . lsp-deferred)
	 (bash-mode . lsp-deferred)
	 ;; (dockerfile-mode . lsp-deferred)
	 (ess-r-mode . lsp-deferred)
	 (gfm-mode . lsp-deferred)
	 (forge-post-mode . lsp-deferred)
	 ;; (groovy-mode . lsp-deferred)
	 (html-mode . lsp-deferred)
	 ;; (julia-mode . lsp-deferred)
	 (js-ts-mode . lsp-deferred)
	 (latex-mode . lsp-deferred)
	 (markdown-mode . lsp-deferred)
	 (org-mode . lsp-deferred)
	 (python-mode . lsp-deferred)
	 (rust-mode . lsp-deferred)
	 (sh-mode . lsp-deferred)))
;; (terraform-mode . lsp-deferred)
;; (typescript-mode . lsp-deferred)))

#+END_SRC

*** lsp-jedi
<<sec:lsp-jedi>>

[[https://github.com/fredcamps/lsp-jedi][lsp-jedi]] is an Emacs client for the Python [[https://github.com/pappasam/jedi-language-server][jedi-language-server]] which I opted for over other offerings as I'd used the
plain [[https://jedi.readthedocs.io/en/latest/][Jedi]] before I started using [[sec:lsp-mode][lsp-mode]] and its not written my Micro$oft like some of the others.

#+NAME: code-lsp-jedi
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package lsp-jedi
  :ensure t
  :after lsp-mode
  :defer 0.5
  :config
  (with-eval-after-load "python-mode"
    (add-to-list 'lsp-enabled-clients 'jedi)))

#+END_SRC

*** lsp-ui
<<sec:lsp-ui>>

[[https://github.com/emacs-lsp/lsp-ui][lsp-ui]] is something I've had installed for a while but don't really use. I should read the [[https://emacs-lsp.github.io/lsp-ui/][documentation]] and
configure/use it properly as it contains the modules that add [[sec:flycheck][Flycheck]] support and a few other things.

#+NAME: code-lsp-ui
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package lsp-ui
  :ensure t
  :after lsp-mode
  :defer t
  :config
  (setq lsp-ui-sideline-enable nil
	lsp-ui-doc-delay 2)
  :hook (lsp-mode . lsp-ui-mode)
  :bind (:map lsp-ui-mode-map
	      ("C-c i" . lsp-ui-imenu)))

#+END_SRC

*** lsp-ltex-plus
<<sec:lsp-ltex-plus>>

[[https://github.com/emacs-languagetool/lsp-ltex-plus][lsp-ltex-plus]] uses the [[https://ltex-plus.github.io/ltex-plus/][ltex-plus]] language server for checking LaTeX, Markdown, Org, reStructuredTest, R Sweave and XHTML
files. Needs the language server installing (unless done via [[sec:mason][Mason]])

#+NAME: code-lsp-ltex-plus
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package lsp-ltex-plus
  :ensure t
  :hook (text-mode . (lambda ()
                       (require 'lsp-ltex-plus)
                       (lsp)))  ; or lsp-deferred
  :config
  (setq lsp-ltex-plus-version "18.2.0"))

#+END_SRC

** Debugging
<<sec::debugging>>

*** dap-mode
<<sec:dap-mode>>

[[https://github.com/emacs-lsp/dap-mode][dap-mode]] interfaces with the [[https://microsoft.github.io/debug-adapter-protocol/][Debug Adapter Protocol]]. I don't really use this and since its another Micro$oft product
should really get into using something like [[sec:realgud][RealGUD]] instead.

Not currently tangled

#+NAME: code-dap-mode
#+BEGIN_SRC emacs-lisp :tangle no
(use-package dap-mode
  :ensure t
  :defer t
  :after lsp-mode
  :config
  (dap-auto-configure-mode))
#+END_SRC

*** RealGUD
<<sec:realgud>>

[[https://github.com/realgud/realgud][realgud]] is a debugger mode, it relies on external debuggers such as Python's ~pdb~.

#+NAME: code-realgud
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package realgud
  :ensure t
  :defer 1
  :after (lsp-mode))

#+END_SRC

*** RealGUD-ipdb
<<sec:realgud-ipdb>>

[[https://github.com/realgud/realgud-ipdb/][realgud-ipdb]] adds support [[https://pypi.org/project/ipdb/][iPython debugger]].

#+NAME: code-realgud-ipdb
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package realgud-ipdb
  :ensure t
  :defer 0.5
  :after (realgud))

#+END_SRC

** Projectile
<<sec:projectile>>

[[https://github.com/bbatsov/projectile/][projectile]] ([[https://docs.projectile.mx/][docs]]) is a neat package for managing and navigating projects.

#+NAME: code-projectile
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package projectile
  :ensure t
  :bind
  (:map projectile-mode-map
        ("s-p" . projectile-command-map))
  :custom
  (projectile-project-search-path '("~/org/" "~/org-roam" "~/.config/emacs" ("~/work/git/" . 3)))
  (projectile-enable-caching t)
  (projectile-switch-project-action #'projectile-commander)
  :init
  (projectile-mode +1))

#+END_SRC

*** consult-projectile
<<sec:consult-projectile>>

[[https://gitlab.com/OlMon/consult-projectile][consult-projectile]] incorporates [[sec:projectile][projectile]] into [[sec:consult][consult]].

#+NAME: code-consult-projectile
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package consult-projectile
  :ensure t
  :after projectile)

#+END_SRC

** Tree Sitter
<<sec:TreeSitter>>

[[https://tree-sitter.github.io/tree-sitter/][Tree-sitter]] is a "magic" tool that performs incremental parsing to build concrete syntax trees as files are
edited. [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Language-Grammar.html][treesit.el]] is built-in to Emacs since 29.1, older versions required [[https://github.com/emacs-tree-sitter/elisp-tree-sitter][tree-sitter.el]].


+ [[https://emacs-tree-sitter.github.io/][emacs-tree-sitter]] - mostly obsolete since it [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Language-Grammar.html][treesit.el]] is built-in now.
+ [[https://archive.casouri.cc/note/2023/tree-sitter-in-emacs-29/index.html][Tree-sitter in Emacs 29]]
+ [[https://takeonrules.com/2023/03/08/coloring-regular-expression-via-modus-themes-for-treesit-faces/][Coloring regular expression via modus themes for treesit faces]]
+ [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][Mastering Emacs - How to get Started with Tree-sitter]]

*** treesit
<<sec:treesit>>


*** treesit-fold
<<sec:tree-sitter-fold>>

[[https://github.com/emacs-tree-sitter/treesit-fold][treesit-fold]] provides tree-folding for the built-in

#+NAME: code-tree-sitter-fold
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package treesit-fold
  :ensure t
  :defer 1
  :after (treesit)
  :custom
  (treesit-fold-line-comment-mode t)
  :init
  (global-treesit-fold-mode))

#+END_SRC

*** tree-sitter-ispell
<<sec:treesit-ispell>>

[[https://github.com/erickgnavar/tree-sitter-ispell.el][tree-sitter-ispell]]

#+NAME: code-treesit-ispell
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package treesit-ispell
  :ensure t
  :defer 0.5
  :after (treesit))

#+END_SRC

*** treesit-auto
<<sec:treesit-auto>>

[[https://github.com/renzmann/treesit-auto][treesit-auto]]

*LEGACY* - Not tangled
#+NAME: code-treesit-auto
#+BEGIN_SRC emacs-lisp :tangle no

(use-package treesit-auto
  :ensure t
  :config
  (treesit-auto-apply-remap))

#+END_SRC

** Flycheck
<<sec:flycheck>>

#+NAME: code-flycheck
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))

#+END_SRC

*** FlySpell
<<sec:flyspell>>
[[https://www.emacswiki.org/emacs/FlySpell#h5o-3][FlySpell]] is a method of spell-checking a buffer on the fly.

#+NAME: code-flyspell
#+BEGIN_SRC emacs-lisp :tangle init.el
(defun flyspell-on-for-buffer-type ()
  "Enable Flyspell appropriately for the major mode of the current buffer.  Uses `flyspell-prog-mode' for modes derived
from `prog-mode', so only strings and comments get checked.  All other buffers get `flyspell-mode' to check all text.
If flyspell is already enabled, does nothing."
  (interactive)
  (if (not (symbol-value flyspell-mode)) ; if not already on
      (progn
	(if (derived-mode-p 'prog-mode)
	    (progn
	      (message "Flyspell on (code)")
	      (flyspell-prog-mode))
	  ;; else
	  (progn
	    (message "Flyspell on (text)")
	    (flyspell-mode 1)))
	;; I tried putting (flyspell-buffer) here but it didn't seem to work
	)))

(defun flyspell-toggle ()
  "Turn Flyspell on if it is off, or off if it is on.  When turning on, it uses `flyspell-on-for-buffer-type' so
code-vs-text is handled appropriately."
  (interactive)
  (if (symbol-value flyspell-mode)
      (progn ; flyspell is on, turn it off
	(message "Flyspell off")
	(flyspell-mode -1))
    ;; else - flyspell is off, turn it on
    (flyspell-on-for-buffer-type)))

(add-hook 'find-file-hook 'flyspell-on-for-buffer-type)
#+END_SRC

*** FlyOver
<<sec:flyover>>

[[https://github.com/konrad1977/flyover][flyover]] shows [[sec:flycheck][flycheck]] and flymake output in-line. Not completely convinced by this package as I like these messages to
stay out of the way until I'm ready to address them. I don't mind the wiggly snake underscores or the notes on the left
side of the buffer though as they are less intrusive.

Not tangled

#+NAME: code-flyover
#+BEGIN_SRC emacs-lisp :tangle no

(use-package flyover
  :ensure t
  :hook
  (flycheck-mode-hook . flyover-mode)
  :config
  (setq flyover-levels '(error warning info))
  (setq flyover-use-theme-colors t)
  (setq flyover-background-lightness 45) ;;  lower values = darker
  (setq flyover-percent-darker 40) ;; Make icon background darker than foreground
  (setq flyover-text-tint 'lighter) ;; or 'darker or nil
  (setq flyover-text-tint-percent 50) ;; Percentage to lighten or darken the text when tinting is enabled.
  (setq flyover-checkers '(flycheck flymake)) ;; Which checks to use
  (setq flyover-debug nil) ;; Enable debug messages
  (setq flyover-debounce-interval 0.2) ;; Time in seconds to wait before checking and displaying errors after a change
  (setq flyover-line-position-offset 1) ;; Lines below error to display overlay (0 = same)
  (setq flyover-wrap-messages t)  ;; Enable wrapping of long error messages across multiple lines
  (setq flyover-max-line-length 80) ;; Maximum length of each line when wrapping messages
  (setq flyover-hide-checker-name t) ;; Hide checker name for a cleaner UI
  (setq flyover-hide-when-cursor-is-on-same-line t))

#+END_SRC

** YASnippet
<<sec:yasnippet>>

[[https://joaotavora.github.io/yasnippet/][YASnippet]] (Yet another snippet extension) is a brilliant templating system that allows you to define code-chunks that
are inserted with a few keystrokes, and then prompting you for specific fields, saving you considerable time in writing
boiler-plate code. We enable the templates via hooks for ~prog-mode~, ~org-mode~ and ~r-mode~ and load a bunch of
pre-defined snippets from the [[https://github.com/AndreaCrotti/yasnippet-snippets][yasnippet-snippets]] package.

#+NAME: code-yasnippet
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package yasnippet
  :ensure t
  :config
  (yas-reload-all)
  (add-hook 'prog-mode-hook #'yas-minor-mode)
  (add-hook 'org-mode-hook #'yas-minor-mode)
  (add-hook 'ess-r-mode-hook #'yas-minor-mode))
#+END_SRC

#+NAME: code-yasnippet
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package yasnippet-snippets
  :ensure t)

#+END_SRC

The snippets I have written/customised are not included here. They are loaded from the ~snippet/~ directory. If you are
interested in my snippets see the [[https://codeberg.org/slackline/emacs/src/branch/master/snippets][snippets]] in my configuration repository.

* Dired
<<sec:dired>>

I like the [[https://github.com/alexluigit/dirvish][dirvish]] package for extending the basic [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][built-in Dired]].

Some useful resources on ~dired~ can also be found in

+ [[https://pragmaticemacs.wordpress.com/category/dired/][dired | Pragmatic Emacs]]
+ [[https://www.masteringemacs.org/article/working-multiple-files-dired][Working with multiple files in dired - Mastering Emacs]]
+ [[https://github.com/Fuco1/dired-hacks][Fuco1/dired-hacks: Collection of useful dired additions]]

#+NAME: code-dirvish
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dirvish
  :ensure t
  :init
  (dirvish-override-dired-mode)
  :config
  (setq dirvish-attributes
	'(vc-state subtree-state all-the-icons collapse git-msg file-time file-size))
  ;; Placement
  ;; (setq dirvish-use-header-line nil)     ; hide header line (show the classic dired header)
  ;; (setq dirvish-use-mode-line nil)       ; hide mode line
  (setq dirvish-use-header-line 'global)    ; make header line span all panes

  ;; Hide the parent directory
  (setq dirvish-default-layout '(0 0.4 0.6))
  ;; Height
  ;;; '(25 . 35) means
  ;;;   - height in single window sessions is 25
  ;;;   - height in full-frame sessions is 35
  (setq dirvish-header-line-height '(25 . 35))
  (setq dirvish-mode-line-height 25) ; shorthand for '(25 . 25)

  ;; Segments
  ;;; 1. the order of segments *matters* here
  ;;; 2. it's ok to place raw string inside
  (setq dirvish-header-line-format
	'(:left (path) :right (free-space))
	dirvish-mode-line-format
	'(:left (sort file-time " " file-size symlink) :right (omit yank index))))
#+END_SRC

** All the Icons
<<sec:all-the-icons>>

To make Dired/Dirvish look nice we also need icons.

#+NAME: code-all-the-icons
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package all-the-icons
  :ensure t
  :after dirvish)

(use-package all-the-icons-dired
  :ensure t
  :after all-the-icons)

(use-package all-the-icons-ibuffer
  :ensure t
  :after all-the-icons)
#+END_SRC

** Dired Extensions
<<sec::dired-extensions>>

There are a bunch of useful extensions to ~dired~ and [[https://github.com/Fuco1/dired-hacks][Fuco1/dired-hacks: Collection of useful dired additions]] has most
of them listed. I currently use the following

+ dired-quick-sort
+ [[https://github.com/stsquad/dired-rsync][dired-rsync]] (also the source for ~dired-rsync-transient~)
+ [[https://codeberg.org/danrobi/dired-multi-copy][dired-multi-copy]] (installed via ~:vc~ option to ~use-package~ as not yet on [[https://melpa.org/][MELPA]])
+ [[https://github.com/punassuming/ranger.el][dired-ranger]]
+ dired-subtree

*** dired-multi-copy
<<sec:dired-multi-copy>>

[[https://codeberg.org/danrobi/dired-multi-copy][dired-multi-copy]]

Not tangled as not on MELPA yet.
#+NAME: code-dired-multi-copy
#+BEGIN_SRC emacs-lisp :tangle no
(use-package dired-multi-copy
  :ensure t
  :defer 0.5
  :after (dirvish))

#+END_SRC

*** dired-duplicates
<<sec:dired-duplicates>>

#+NAME: code-dired-duplicates
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dired-duplicates
  :ensure t
  :defer 0.5
  :after (dirvish))

#+END_SRC

*** dired-quick-sort
<<sec:dired-quick-sort>>

#+NAME: code-quick-sort
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dired-quick-sort
  :ensure t
  :defer 0.5
  :after dirvish
  :config
  (dired-quick-sort-setup))

#+END_SRC

*** dired-rsync
<<sec:dired-rsync>>

Not tangled as its installed/loaded by the transient

#+NAME: code-dired-rsync
#+BEGIN_SRC emacs-lisp :tangle no
(use-package dired-rsync
  :ensure t
  :defer 0.5
  :after (dirvish))

#+END_SRC

*** dired-rsync-ranger
<<sec:dired-rsync-ranger>>

[[https://github.com/punassuming/ranger.el][ranger]]

#+NAME: code-dired-rsync-ranger
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dired-ranger
  :ensure t
  :defer 0.5
  :after (dirvish)
  :bind (:map dired-mode-map
              ("W" . dired-ranger-copy)
              ("X" . dired-ranger-move)
              ("Y" . dired-ranger-paste)))

#+END_SRC

*** dired-rsync-subtree
<<sec:dired-subtree>>

#+NAME: code-dired-subtree
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dired-subtree
  :ensure t
  :defer 0.5
  :after (dirvish)
  :custom
  (bind-keys :map dired-mode-map
             ("i" . dired-subtree-insert)
             (";" . dired-subtree-remove)))
#+END_SRC

*** dired-rsync-transient
<<sec:dired-rsync-transient>>

#+NAME: code-dired-rsync-transient
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dired-rsync-transient
  :ensure t
  :defer 0.5
  :after (dirvish))

#+END_SRC

* TRAMP
<<sec:tramp>>

[[TRAMP]] (Transparent Remote (file) Access, Multiple Protocol) "/ provides an easy, convenient, and consistent interface to
editing remote files transparently, just as if they are local files. This extends to editing, version control, dired,
and more./". The "more" part includes files under ~su~ both locally and remotely. It is one of the amazing packages in
Emacs that makes people's lives considerably easier. I don't use it nearly enough, the first time I tried it out I had
major issues which were down to the prompts on the remote machine. Took a while to find a [[https://emacs.stackexchange.com/questions/47969/trouble-connecting-gnu-emacs-to-work-machine-through-ssh-tramp][thread]] with a simple way to
disable the ~PS1~ prompt [[https://emacs.stackexchange.com/a/48089][if ~$TERM == "dumb"~]].

+ [[https://coredumped.dev/2025/06/18/making-tramp-go-brrrr./][Making TRAMP go Brrrr...]] is a useful article on speeding things up which is where most of my customisations came from
  (not implemented them all yet though!)

#+NAME: code-tramp
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package tramp
  :ensure t
  :custom
  (tramp-default-method "ssh")
  (add-to-list 'tramp-default-method-alist '("" "neil" "ssh"))
  ;; Set prompt so it doesn't hang
  (shell-prompt-pattern '"^[^#$%>\n]*~?[#$%>] *")
  (tramp-auto-save-directory "~/.config/emacs/tmp/")
  (remote-file-name-inhibit-locks t)
  (tramp-use-scp-direct-remote-copying t)
  (remote-file-name-inhibit-auto-save-visited t)
  (tramp-copy-size-limit (* 1024 1024)) ;; 1Mb
  ;; Set default usernames for different hosts and a global default.
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*ovh'" "arch") t)
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*openwrt" "admin") t)
  (add-to-list 'tramp-default-user-alist
	       '(nil nil "neil") t)
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*alarmpi-4b" "neil") t)
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*crow'" "neil") t))

#+END_SRC

* Terminals
<<sec:terminals>>

I don't use the shell/terminal in Emacs much as I quite like having clear separate usage and so use [[https://sw.kovidgoyal.net/kitty/][kitty]].
** vterm
<<sec:vterm>>

[[https://github.com/akermu/emacs-libvterm][vterm]] is a compiled terminal emulator, as such you need to have something like ~gcc~ installed (common on most GNU/Linux
systems, less so on M$-Win/OSX).

#+NAME: code-vterm
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package vterm
  :ensure t
  :defer 3
  :custom
  (vterm-always-compile-module t)
  (vterm-copy-exclude-prompt t)
  (vterm-kill-buffer-on-exit t))

#+END_SRC


** eat
<<sec:eat>>

[[https://codeberg.org/akib/emacs-eat/][eat]] is another terminal emulator that I may investigate in the future if I ever tire of using [[https://sw.kovidgoyal.net/kitty/][kitty]].

#+NAME: code-eat
#+BEGIN_SRC emacs-lisp :tangle no
(use-package eat
  :ensure t)

#+END_SRC

* Communication
** Email

Email is another area I'm yet to integrate into Emacs. Mainly as I've used the WebUI for many years but I should
consider switching. Might be a little tricky as its likely to involve the [[https://protonmail.me][Proton Mail]] Bridge. There seems to be two
options in Emacs Gnus or mu4e

*** General articles to refer to.

+ [[https://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and/][A Complete Guide to Email in Emacs using Mu and Mu4e]]

*** Getting email working with ProtonMail (I've mirrored some of the following to my own [[https://opengist.nshephard.dev/nshephard/c092d263b738444ea893fe2d59d11006][gist]]).

+ [[https://gist.github.com/alexispurslane/28be85797872fcc3fda80e2aa973903c][A complete and fully-working (including STARTTLS encryption and HTML emails) setup to use Proton Mail Bridge with
  emacs]] seems useful.
+ [[https://gist.github.com/A6GibKm/238b754a4a90051f60906b9efa3e8000][Connecting Emacs and Protonmail Bridge]].
+ [[https://shom.dev/posts/20220108_setting-up-protonmail-in-emacs/][Setting up Protonmail in Emacs | shom.dev]]

*** Organising Emails

+ [[https://cnoceda.com/tecnologia/posts/20251119T083113--searching-by-sender-in-notmuch__blog_emacs_email_notmuch_tecnologia.html][Searching by sender in notmuch]]


** Org Social
<<sec:org-social>>

[[https://github.com/tanrax/org-social][org-social]] "/is a decentralized social network that runs on an Org Mode file over HTTP/". I was looking for a
micro-blogging service that was federated as I've used [[https://quarto.org/][Quarto]] hosted on GitHub pages to write [[https://blog.nshephard.dev/][blog.nshephard.dev]] but
wanted something quick and easy to use and as I'm keen on letting Emacs and Org-mode subsume as many aspects of my
computing activities as possible it seemed the natural choice.

There are a few layers here, not all of which are relevant to Emacs configuration (e.g. configuring Nginx).

+ [[https://github.com/tanrax/org-social][org-social: Org Social is a decentralized social network that runs on an Org Mode file over HTTP.]]
+ [[https://github.com/tanrax/org-social.el][org-social.el: Emacs client for Org Social]]

Not currently tangled.

#+NAME: code-org-social
#+BEGIN_SRC emacs-lisp :tangle no
(use-package org-social
  :config
  ;; Option 1: Local file + your own hosting
  (setq org-social-file "~/work/git/codeberg/slackline/org-social/social.org")
  (setq org-social-relay "https://relay.org-social.org/")
  (setq org-social-my-public-url "https://org-social.nshephard.dev/")

  ;; Optional: Add global keybindings
  (keymap-global-set "C-c s t" #'org-social-timeline)
  (keymap-global-set "C-c s n" #'org-social-new-post))
#+END_SRC


** Mastodon
<<sec:mastodon>>

[[https://codeberg.org/martianh/mastodon.el][mastodon.el]] allows tooting and reading the [[https://fedi.tips/][Mastodon]] on the Fediverse. Not yet got into the habit of using Emacs to do
this. I should give it a go at some point, although ideally I would like to have access to several different accounts
simultaneously and avoid having to list my username here.

Not currently tangled.

#+NAME: code-mastodon
#+BEGIN_SRC emacs-lisp :tangle no
(use-package mastodon
  :ensure t
  :config
  (setq mastodon-instance-url "https://mastodon.social"
	mastodon-active-user "")
  )
#+END_SRC

** Element
<<sec:element>>

The [[https://element.io][Element]] messaging service can be accessed from with Emacs using the [[https://github.com/alphapapa/ement.el][ement]] package. It didn't used to support native
room encryption, which required a reverse proxy via https://github.com/matrix-org/pantalaimon/.


Not currently tangled.

#+NAME: code-element
#+BEGIN_SRC emacs-lisp :tangle no
(use-package ement
  :ensure t
  :defer 6)
#+END_SRC

** Slack

I use Slack for work (it's replacing email as the main interuptor of my concentration because why not ping someone a
message that could easily be sent by email?!?!?!) but I try not to look at work outside of work so haven't adopted using
Emacs to look at it. There is the [[https://github.com/isamert/emacs-slack][emacs-slack]] package if required but I doubt I'll use it.

** Deltachat

[[https://delta.chat/en/][Deltachat]] is in essence Encrypted Instant Messaging over email (it uses [[https://scarbrough.co.uk/post/autocrypt-deltachat/][Autocrypt and OpenPGP]]). There isn't an official
client for Emacs yet but some have asked for it and there are some related threads/themes.

+ [[https://support.delta.chat/t/request-deltachat-emacs/2458][Request: deltachat-emacs - Feature Proposal - Delta.Chat]]
+ [[https://thibaut.dev/blog/deltachat-inbox-bot.html][Deltachat inbox bot]]

* Miscellaneous
<<sec:misc>>

** citar
<<sec:citar>>

[[https://github.com/emacs-citar/citar][citar]] "/provides  a highly-configurable completing-read front-end to browse and act on BibTeX, BibLaTeX, and CSL JSON
bibliographic data, and LaTeX, markdown, and org-cite editing support./" which basically makes it easy to insert
references from your ~.bib~ file.

#+NAME: code-citar
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package citar
    :ensure t
    :defer 1
    :custom
    (citar-bibliography '("~/org/references.bib"))
    :hook
    (LaTeX-mode . citar-capf-setup)
    (markdown-mode . citar-capf-setup)
    (org-mode . citar-capf-setup))

#+END_SRC

** mpd

I use [[https://musicpd.org/][Music Player Daemon]] to run my music, these packages allow me to control ~mpd~ from Emacs.

*** mpdel
<<sec:mpdel>>

[[https://gitea.petton.fr/mpdel/mpdel][mpdel]] provides an interface to ~mpd~ its not working perfectly yet, for example I use a password and I can't see anyway
of configure a password.

Unfortunately the keybindings for multimedia keys aren't currently recognised.

#+NAME: code-mpdel
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package mpdel
    :ensure t
    :defer 1
    :custom
    (libmpdel-hostname "192.168.1.28")
    (libmpdel-port 6600)
    ;; :bind (("<XF86AudioPlay>" . libmpdel-playback-play-pause)
;;         ("<XF86AudioNext>" . libmpdel-playback-next)
    ;;               ("<XF86AudioPrev>" . libmpdel-pl;; ayback-previous))
    ;;         ;; ("<XF86AudioPlay>" ("MPDel Play" . libmpdel-playback-play-pause))
    ;;         ;; ("<XF86AudioNext>" ("MPDel Next" . libmpdel-playback-next))
    ;;               ;; ("<XF86AudioPrev>" ("MPDel Prev" . libmpdel-playback-previous))
    :bind-keymap (("C-x Z" . mpdel-core-map)))
  ;; (mpdel-mode)

#+END_SRC

*** ivy-mpdel
<<sec:ivy-mpdel>>

[[https://github.com/mpdel/ivy-mpdel][ivy-mpdel]] provides an Emacs' ivy interface to communicate with ~mpd~.

Not currently tangled

#+NAME: code-ivy-mpdel
#+BEGIN_SRC emacs-lisp :tangle no
(use-package ivy-mpdel
  :ensure t
  :defer 2)

#+END_SRC

*** mpdmacs
<<sec:mpdmacs>>

[[https://github.com/sp1ff/mpdmacs][mpdmacs]] is another client that I'm yet to investigate/get working.

#+NAME: code-mpdmacs
#+BEGIN_SRC emacs-lisp :tangle no
(use-package mpdmacs
  :ensure t
  :defer 2
  :custom
  (mpdmacs-host "192.168.1.28")
  (mpdmacs-port 6600)
  :bind
  ("C-c m" . 'mpdmacs-mode-keymap)
  :hook (mpdmacs-mode-hook . mpdmacs-mode-keymap))


#+END_SRC

** OSM
<<sec:osm>>

[[https://github.com/minad/osm][osm]] provides in Emacs [[https://openstreetmap.org][OpenStreetMap]] viewer. It includes the ability to add bookmarks and define
~geo:<lat>,<lon>;z=<zoom-int>~ org-links.

#+NAME: code-osm
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package osm
  :ensure t
  :defer 3
  :custom
  (osm-server 'default)
  (osm-home '(53.356116 -1.463397 15))
  :bind
  (("C-c o" . osm-prefix-map)))

#+END_SRC

** Pass
<<sec:pass>>

[[https://github.com/NicolasPetton/pass][pass]] provides access to [[https://www.passwordstore.org/][pass the standard unix password manager]]. I always want this available so I just ~:ensure
t~. Invoking ~pass~ brings up a transient-like menu and list of passwords that are stored on the system providing easy
and intuitive access to accessing and managing stored passwords.

Currently not included in config in favour of [[sec:password-store-menu][password-store-menu]]
#+NAME: code-pass
#+BEGIN_SRC emacs-lisp :tangle no
(use-package pass
  :ensure t)

#+END_SRC

*** password-store-menu
<<sec:password-store-menu>>

[[https://github.com/rjekker/password-store-menu][password-store-menu]] adds a transient menu to ~password-store.el~ which is part of  [[https://www.passwordstore.org/][pass the standard unix password
manager]]. Invoking ~password-store-menu~ brings up the transient menu from where you can navigate the actions you wish to
take. I prefer this over [[sec:pass][pass]].

#+NAME: code-password-store-menu
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package password-store-menu
  :ensure t
  :config (password-store-menu-enable)
  :custom (password-store-menu-key "C-c C-p"))

#+END_SRC

*** password-store-otp
<<sec:password-store-otp>>

[[https://github.com/volrath/password-store-otp.el][password-store-otp]] provides access to the [[https://github.com/tadfisher/pass-otp][pass-otp]] plugin from Emacs.

#+NAME: code-password-store-otp
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package password-store-otp
  :ensure t
  :after (password-store-menu))

#+END_SRC

** Scratch
<<sec:scratch>>

Scratch buffers are useful for testing code in playgrounds.

*** scratch.el
<<sec:scratch-el>>

[[https://codeberg.org/emacs-weirdware/scratch][scratch]] extends the basic ~*scratch*~ buffer and provides per-mode scratch buffers. These are opened using the bound
key. If you want a prompt for which buffer mode to invoke then use ~C-u M-x scratch~ and you'll be prompted.

#+NAME: code-scratch-el
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package scratch
  :ensure t
  :bind ("C-c s" . scratch))

#+END_SRC

*** scratch-plus
<<sec:scratch-plus>>

[[https://git.sr.ht/~swflint/scratch-plus][scratch-plus]] "/provides four major features: unkillable scratch buffers, persistent scratch buffers, per-major-mode
scratch buffers, and per-project scratch buffers./". Yet to work out if this is working as expected and how to enable
the per-major-mode scratch buffers.

#+NAME: code-scratch-plus
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package scratch-plus
  :ensure t
  :defer 0.5
  :hook
  (after-init-hook . scratch-plus-mode)
  :custom
  (scratch-plus-save-directory "~/.config/emacs/scratch")
  (scratch-plus-project-subdir ".scratch")
  (scratch-plus-idle-save 3))
#+END_SRC

** sicp
<<sec:sicp>>

Installs a [[https://github.com/webframp/sicp-info][info]] version of the second edition of [[https://mitp-content-server.mit.edu/books/content/sectbyfn/books_pres_0/6515/sicp.zip/index.html][Structure and Interpretation of Computer Programs (SICP)]] (see also
[[https://ocw.mit.edu/courses/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video_galleries/video-lectures/][video series]]).

#+NAME: code-sicp
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package sicp
  :ensure t)

#+END_SRC

** tmr
<<sec:tmr>>

[[https://github.com/protesilaos/tmr][tmr]] is another useful package from [[https://protesilaos.com/emacs/tmr][Prot]] which makes setting timers/reminders really simple.

#+NAME: code-tmr
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package tmr
  :ensure t
  :defer 0.5
  :bind-keymap (("C-c T" . tmr-prefix-map)))
#+END_SRC

** goto-addr
<<sec:goto-addr>>

#+NAME: code-goto-addr
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package goto-addr
  :hook ((compilation-mode . goto-address-mode)
         (prog-mode . goto-address-prog-mode)
         (text-mode . goto-address-mode)
         (shell-mode . goto-address-mode))
  :bind (:map goto-address-highlight-keymap
              ("<RET>" . goto-address-at-point)
              ("M-<RET>" . newline))
  :commands (goto-address-prog-mode
             goto-address-mode))

#+END_SRC

* Documentation

** DevDocs
<<sec:devdocs>>

[[https://github.com/astoff/devdocs.el][devdocs.el]] is an Emacs viewer for [[https://devdocs.io/][DevDocs]]. The docs need manually installing but after that they are available via ~C-h
D~.

+ kubernetes
+ markdown
+ matplotlib
+ nginx
+ numpy-2.2
+ pandas-2
+ python-3.14
+ rust
+ sqlite

#+NAME: code-devdocs
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package devdocs
    :ensure t
    :defer 4
    :bind ("C-h D" . devdocs-lookup))
#+END_SRC

* User Interface

Elements concerned with the User Interface which typically means how buffers, mini-buffers, modeline look.

** Themes
<<sec:themes>>

*** modus-themes

[[https://protesilaos.com/modus-themes/][modus-themes]] from Prot are really nice.

#+NAME: code-modus-themes
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package modus-themes
  :ensure t
  :defer 0.5
  :custom
  ;; Add all your customisation's prior to loading the themes
  (modus-themes-italic-constructs t
	(message "message" format-args)odus-themes-bold-constructs t
    modus-themes-org-blocks '(tinted-background)
    modus-themes-include-derivatives-mode 1)
  :bind
  ("C-c C-t m" . modus-themes-toggle))
#+END_SRC

*** ef-themes
<<sec:ef-themes>>

[[https://protesilaos.com/emacs/ef-themes][ef-themes]] also from [[https://protesilaos.com/][Prot]] are also very nice and my current favourite.

#+NAME: code-ef-themes
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ef-themes
  :ensure t
  :custom
  (ef-themes-disable-other-themes 'ef-themes-light-themes)
  (ef-themes-take-over-modus-themes-mode t)
  :bind
  (("<f5>" . modus-themes-rotate)
   ("C-<f5>" . modus-themes-select)
   ("M-<f5>" . modus-themes-load-random)
   ("C-c C-t d" . ef-themes-select-dark)
   ("C-c C-t e" . ef-themes-toggle)))
(load-theme 'ef-dark :no-confirm)

#+END_SRC

*** golden ratio
<<sec:golden-ratio>>

[[https://github.com/roman/golden-ratio.el][golden-ratio]]

#+NAME: code-golden-ratio
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package golden-ratio
  :ensure t
  :defer 0.5
  :custom
  (setq golden-ratio-auto-scale t))

#+END_SRC

*** Font

I use the [[https://github.com/source-foundry/Hack][Hack]] font in Emacs, it needs installing at the system level so it's available for Emacs.

#+NAME: code-font
#+BEGIN_SRC emacs-lisp :tangle init.el
(set-face-attribute 'default t :font "Hack")
#+END_SRC

*** Indent bars
<<sec:indent-bars>>

[[https://github.com/jdtsmith/indent-bars][indent-bars]] are a great visual indicator of where you are.

#+NAME: code-indent-bars
#+BEGIN_SRC emacs-lisp :tangle init.el
  (use-package indent-bars
    :ensure t
    :hook ((prog-mode) . indent-bars-mode))

#+END_SRC


** Modeline
<<sec:modeline>>

*** hide-mode-line
<<sec:hide-mode-line>>

[[https://github.com/hlissner/emacs-hide-mode-line][hide-mode-line]] is useful for hiding the mode-line in buffers where you don't want to see it such as completion-list or
org popup agendas.

#+NAME: code-hide-mode-line
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package hide-mode-line
  :ensure t
  :defer 3
  :hook
  (completion-list-mode-hook . hide-mode-line-mode))

#+END_SRC

*** mood-line
<<sec:moodline>>

[[https://git.tty.dog/hpet_dog/mood-line][mood-line]] is a minimalist configuration for the default [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Mode-Line.html][mode-line]], the bar at the bottom of a buffer showing information
about the buffer.

#+NAME: code-moodline
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package mood-line
  :ensure t
  :custom
  (mood-line-glyph-alist mood-line-glyphs-unicode)
  :config
  (mood-line-mode))

#+END_SRC

*** minions
<<sec:minions>>

[[https://github.com/tarsius/minions][minions]] is another neat little package from the author of [[sec:magit][Magit]] which adds a pop-up menu to the mode-line that shows the
minor modes that are enabled for the given buffer. Haven't quite got this working yet as I only see the major mode
listed and can't yet find where to click to get the menu but ~minions-minor-mode-menu~ can be called interactively to
access the same list.

#+NAME: code-minions
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package minions
  :ensure t)
#+END_SRC

*** Custom Modeline
<<sec:custom-modeline>>

Once tried implementing a [[https://protesilaos.com/codelog/2023-07-29-emacs-custom-modeline-tutorial/][custom modeline]] based on a tutorial by Prot.

Not currently tangled.

#+NAME: code-custom-modeline
#+BEGIN_SRC emacs-lisp :tangle no
Custom Modeline
(setq-default mode-line-format
  '("%e"
     prot-modeline-kbd-macro
     prot-modeline-narrow
     prot-modeline-input-method
     prot-modeline-buffer-status
     " "
     prot-modeline-buffer-identification
     "  "
     prot-modeline-major-mode
     prot-modeline-process
     "  "
     prot-modeline-vc-branch
     "  "
     prot-modeline-flymake
     "  "
     prot-modeline-align-right
     prot-modeline-misc-info))

#+END_SRC

** Buffers

Some customisations to make buffers nicer to work with/read.

*** highlight-indent-guides
<<sec:highlight-indent-guides>>

[[https://github.com/DarthFennec/highlight-indent-guides][highlight-indent-guides]] a minor mode that does what it says on the tin, vertical indent guides (lines between starting a
code block that is indented and ending it) are highlighted as you scroll.

#+NAME: code-highlight-indent-guides
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package highlight-indent-guides
  :ensure t
  :defer 1
  :custom
  (highlight-indent-guides-method 'bitmap)
  :hook
  (prog-mode . highlight-indent-guides-mode))

#+END_SRC

*** smartparens
<<sec:smartparens>>

[[https://github.com/Fuco1/smartparens][smartparens]] ensures parentheses (and quotes) are always paired. Handy as there are a lot of parentheses in Elisp! I
pretty much always want this enabled across multiple modes. There may be some redundancy here that can be removed!

#+NAME: code-smartparens
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package smartparens
  :ensure t
  :defer 1
  :custom
  (smartparens-global-mode t)
  :hook
  (prog-mode . smartparens-mode)
  (text-mode . smartparens-mode)
  (markdown-mode . smartparens-mode)
  (latex-mode . smartparents-mode)
  :config
  (progn
    (require 'smartparens-config)
    (smartparens-global-mode 1)
    (show-paren-mode t)))

#+END_SRC

*** rainbow-delimiters
<<sec:rainbow-delimiters>>

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] in conjunction with [[sec:smartparens][smartparens]] makes it easy to see which parentheses/brackets/braces pair up.

#+NAME: code-rainbow-delimiters
#+BEGIN_SRC emacs-lisp :tangle init.el

(use-package rainbow-delimiters
  :ensure t
  :hook
  (prog-mode . rainbow-delimiters-mode))

#+END_SRC

*** rainbow-mode
<<sec:rainbow-mode>>

[[https://github.com/emacsmirror/rainbow-mode][rainbow-mode]] is a minor mode that colourises colour names, whether they are hexadecimal or otherwise.

#+NAME: code-rainbow-mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package rainbow-mode
  :ensure t
  :defer 1
  :hook
  (prog-mode . rainbow-mode))

#+END_SRC

** Tabs
<<sec:tabs>>

*** Centaur Tabs
<<sec:centaur-tabs>>

[[https://github.com/ema2159/centaur-tabs][centaur tabs]] is a nice package for grouping buffers into tabs. I've a couple of custom functions that group them and
also hide certain buffers I don't need to see often.

+ [[https://themkat.net/2024/01/04/emacs_centaur_tabs.html][centaur-tabs-buffer-groups]]

#+NAME: code-centaur-tabs
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package centaur-tabs
  :ensure t
  :demand
  :config
  (centaur-tabs-mode t)
  (defun centaur-tabs-buffer-groups ()
    "Groups tabs based on which project root they are in if possible"
    (let ((get-closest-projectile-project
	   (lambda (path)
	     (let ((expanded-path (f-long path)))
	       (-first (lambda (proj)
			 (s-starts-with? proj
					 expanded-path))
		       (-map (lambda (proj)
			       (f-long proj))
			     projectile-known-projects))))))
      (list (cond
	     ;; Group as part of projectile project if directly part of it
	     ((condition-case _err
		  (projectile-project-root)
		(error nil))
	      (f-expand (projectile-project-root)))
	     ;; Try to group as part of projectile project if indirectly part of it (started from the same directory, not yet tracked, or maybe temporary buffer)
	     (get-closest-projectile-project default-directory)
	     ((string-equal "*" (substring (buffer-name) 0 1))
	      "proc-buffers")
	     ;; ... other groupings ...
	     (t
	       "Other")))))
  (defun centaur-tabs-hide-tab (x)
    "Do no to show buffer X in tabs."
    (let ((name (format "%s" x)))
      (or
        ;; Current window is not dedicated window.
        (window-dedicated-p (selected-window))
        ;; Buffer name not match below blacklist.
        (string-prefix-p "*epc" name)
        (string-prefix-p "*helm" name)
        (string-prefix-p "*Helm" name)
        (string-prefix-p "*Compile-Log*" name)
        (string-prefix-p "*lsp" name)
        (string-prefix-p "*company" name)
        (string-prefix-p "*Flycheck" name)
        (string-prefix-p "*tramp" name)
        (string-prefix-p " *Mini" name)
        (string-prefix-p "*help" name)
        (string-prefix-p "*straight" name)
        (string-prefix-p "*temp" name)
        (string-prefix-p "*Help" name)
        (string-prefix-p "*mybuf" name)
        ;; Is not magit buffer.
        (and (string-prefix-p "magit" name)
	  (not (file-name-extension name)))
        )))
  :custom
  (centaur-tabs-enable-key-bindings t)
  (centaur-tabs-style "wave")
  (centaur-tabs-set-icons t)
  (centaur-tabs-set-bar 'under)
  (x-underline-at-descent-line t)
  (centaur-tabs-cycle-scope 'default)
  (centaur-tabs-set-modified-marker t)
  (centaur-tabs-modified-marker "")
  :bind(
         ;; ("C-c t C-<right>" ("Move tab right" . centaur-tabs-move-current-tab-to-right))
         ;; ("C-c t C-<left>" ("Move tab left" . centaur-tabs-move-current-tab-to-left))
         ("C-<prior>" . centaur-tabs-backward)
         ("C-<next>"  . centaur-tabs-forward)))


#+END_SRC


*** Keybindings
<<sec:keybindings>>

#+NAME: code-keybindings
#+BEGIN_SRC emacs-lisp :tangle init.el
;; Function Keys
(global-set-key (kbd "<f1>") 'password-store-copy)
(global-set-key (kbd "<f2>") 'eval-buffer)
(global-set-key (kbd "<f3>") 'eval-region)
(global-set-key (kbd "<f4>") 'package-list-packages)
(global-set-key (kbd "<f5>") 'keychain-refresh-environment)
(global-set-key (kbd "<f6>") (lambda () (interactive) (find-file user-init-file)))
(global-set-key (kbd "<f7>") 'flyspell-toggle)
(global-set-key (kbd "<f8>") 'which-key-show-major-mode)
(global-set-key (kbd "<f9>") 'emacs-index-search)
(global-set-key (kbd "C-M-%") 'query-replace-regexp)
(if (system-name) "kimura" (global-set-key (kbd "<XF86HomePage>") 'osm-home))

;; Python
(global-set-key (kbd "C-c p v") 'pyvenv-workon)
(global-set-key (kbd "C-c p p") 'run-python)

;; Miscellaneous
(global-set-key (kbd "C-c C-k") 'keychain-refresh-environment)
(global-set-key (kbd "C-c u") 'rsync-html)
(global-set-key (kbd "C-c C-r") 'revert-buffer-no-confirm)

;; vundo
(global-set-key (kbd "C-c v") 'vundo)
#+END_SRC

* Footer
<<sec:footer>>

Library [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][conventions]] require a footer.

#+NAME: code-footer
#+begin_src emacs-lisp :tangle init.el
  (provide 'init.el)
  ;;; init.el ends here
#+end_src

* On Literate Configuration

** Development

During development I created the Org file at ~~/.config/emacs/config.org~ and set the header to tangle to ~init.el~
within that directory so that I didn't clobber my existing ~init.el~.

#+NAME: example-tangle-header
#+BEGIN_SRC org-mode :tangle no
,#+TITLE: Literate Emacs Configuration
,#+PROPERTY: header-args : tangle init.el
,#+OPTIONS: toc:2 num:nil
,#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+END_SRC

** Different target files

When writing code blocks in Org-mode they have the structure shown below which allows the global ~:tangle~ target to be
over-ridden. Useful for writing the ~early-init.el~

#+NAME: example-tangle-alt-target-file
#+BEGIN_SRC org-mode :tangle no
,#+NAME
,#+BEGIN_SRC emacs-lisp :tangle <target_file>
(setq some-custom-setting 1)
,#+END_SRC
#+END_SRC

** Exclude block

If there is a particular code block I _don't_ want to tangle and include it is possible to disable it.

#+NAME: example-tangle-exclude-code-block
#+BEGIN_SRC org-mode :tangle no
,#+BEGIN_SRC emacs-lisp :tangle no
(setq some-other-custom-setting nil)
,#+END_SRC
#+END_SRC

** Testing configuration

As I worked through developing this configuration I tangled the code using ~org-babel-tangle~ (bound to ~C-c C-v t~) and
then started Emacs with the ~--init-directory ~/.config/emacs/config~ so that it picked up the tangled configuration
files within this directory (i.e. ~early-init.el~ and ~init.el~).

** Rendering to HTML

As with much of my config its not original, I found someone else who had done what I want to do and have learnt/borrowed
(heavily) from them. In the case of this literate configuration and its conversion to HTML I have taken inspiration from
[[https://github.com/Panadestein/emacsd][Panadestein's emacsd]] repository.

Of particular use is the GitHub workflow which runs a Bash script ([[https://github.com/Panadestein/emacsd/blob/master/publi.sh][publi.sh]]) to use Emacs to [[https://github.com/Panadestein/emacsd/blob/master/build-site.el][build-site.el]]
 which I have copied in their entirety to build and deploy the site on GitHub pages (for now, I intend to migrate it to
 Codeberg Pages once I've sussed those out).


* Links

+ [[https://orgmode.org/worg/org-contrib/babel/][Babel: Active Code in Org]]
+ [[https://leanpub.com/lit-config/read][Literate Configuration | Diego Zamboni]]
+ [[https://org-babel.readthedocs.io/en/latest/][Org Babel reference card]]
+ [[https://www.masteringemacs.org/][Mastering Emacs]]
+ [[https://sachachua.com/blog/category/emacs-news/][Emacs News | Sacha Chua]]

** use-package

+ [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][Emacs Manual : use-package]]
+ [[https://ianyepan.github.io/posts/setting-up-use-package/][Setting up use-package]]
+ [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using use-package the right way - (think)]]

** Examples

+ [[https://panadestein.github.io/emacsd/][Emacs literate configuration]] by Panadestein
+ [[https://tkreuziger.com/posts/2023-11-24-setting_up_my_literate_config_for_emacs/][Setting up my literate config for Emacs | Tristan Kreuziger]]
+ [[https://www.mauromotion.com/posts/2026-01-01-emacs/][Entering the Church of Emacs - mauromotion.com]] (links to [[https://github.com/mauromotion/dotfiles/blob/main/common/emacs/config.org][configuration]] on GitHub)

** Assistance

I'm still learning and had to ask questions to get to where I am. Here are the helpful people who assisted me.

+ [[https://emacs.stackexchange.com/questions/85329/org-mode-blink-cursor-error/85332#85332][org-mode blink-cursor error]]
