#+TITLE: Literate Emacs Configuration
#+PROPERTY: header-args :tangle ./init.el
#+OPTIONS: toc:2 num:nil
#+SETUPFILE: ./theme-readtheorg.setup

This is my Emacs config, there are many like it but this one is mine.

I've used Emacs for getting on 25 years and am slightly ashamed to say that I still haven't sat down and properly "learnt"
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html][Emacs Lisp]] (one day I'll make time!). I have however learnt enough to cobble together my own custom configuration which
is based, in no small part, on countless others who have gracefully shared examples of their configuration and patiently
answered questions.

I found my configuration was growing as I have a habit of throwing all sorts into it then one day (<2025-10-17 Fri>)
after updating packages I found that [[sec:lsp-mode][LSP-mode]] was no longer working as it had been. At the same time I had some issues
using [[sec:magit][Magit]] and [[sec:transient][Transient]]. Whilst I fixed these it prompted me to pull my thumb out and re-write my configuration
[[https://leanpub.com/lit-config/read][literately]] and have used it as an opportunity to actually start learning Emacs Lisp a little (I find tutorials and
walk-throughs quite abstract and like to have a use-case of my own to help me learn aspects of computing).

I keep extensive [[https://org-roam.nshephard.dev][Org-roam]] notes and have separate sections on [[https://org-roam.nshephard.dev/#754f25a5-3429-4504-8a17-4efea1568eba][Emacs]], [[https://org-roam.nshephard.dev/#220d7ba9-d30e-4149-a25b-03796e098b0d][Magit]] and [[https://org-roam.nshephard.dev/#169b9c5f-df34-46ab-b64f-8ee98946ee69][Org-mode]], but have taken the opportunity
to augment this configuration not just with explanations of the configuration options themselves but a little more on
each package and how it works.

There are a lot of excellent resources to help guide Emacs users through configuring their browser to their own needs.

| Resource                                     | Access in Emacs with...                     |
|----------------------------------------------+---------------------------------------------|
| [[https://www.gnu.org/software/emacs/tour/][Emacs Tutorial]]                               | ~C-h t~                                     |
| [[https://www.gnu.org/software/emacs/manual/][Emacs Manual]]                                 | ~C-h r~                                     |
| Info pages for installed packages            | ~C-h i~                                     |
| Manuals for packages                         | ~C-h R~ and search for package              |
| [[https://www.gnu.org/software/emacs/manual/html_node/eintr/index.html][An Introduction to Programming in Emacs Lisp]] |                                             |
| [[https://www.gnu.org/software/emacs/documentation.html][Emacs Lisp Reference]]
| [[https://www.masteringemacs.org/][Mastering Emacs]]                              | N/A -website and book from Mickey Peterson. |

Feedback is welcome, please create an [[https://codeberg.org/slackline/emacs/issues][issue]] on the Codeberg repository and I'll pick it up.

* ToDo

Tasks I'm yet to complete in re-writing...

- [ ] Switch to using ~:custom~ over ~:config~ as described [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][here]].
- [ ] Test the ~compilation-finish-function~ hook will kill compilation buffers.
- [ ] Ensure ~(desc . command)~ is used for all custom key-bindings so that they are all shown by ~which-key~




* On Configuration with use-package
<<sec:conf-use-package>>

Currently I use the built-in [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][use-package]] and in re-writing this document have sought to adhere to the advice on [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using
use-package the right way]]. The following table is constructed from the archived [[https://github.com/jwiegley/use-package][use-package ~README.md~]] and the [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][Emacs
docs : use-package]] page since it is now a core component of Emacs. use-package provides the [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html#Basic-Concepts][~use-package~ macro]] which
simplifies configuration.

Packages are either loaded immediately, when the package is first used (via autoloading) or can be deferred using the
~:defer~ keyword. Some autoloading can be done in response to /triggers/ in response to certain events (i.e. ~:hook~)

| Option         | Description                                                                                                                                        | Example                                                                                                                                                                                |
|----------------+----------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [[https://github.com/jwiegley/use-package#getting-started][~:init~]]        | Execute code /before/ a package is loaded                                                                                                          | ~:init (setq foo-variable t)~                                                                                                                                                          |
| ~:defer~       | Delay loading of package. Can be ~t~ but is rarely used, typically an integer /n/ is specified to load the package after that period of idle time. | ~:defer t~ / ~:defer 30~                                                                                                                                                               |
| ~:after~       | Load after another package has been loaded.                                                                                                        | ~:after org~                                                                                                                                                                           |
| [[https://github.com/jwiegley/use-package#key-binding][~:bind~]]        | Key-bindings, plain or with a cons (~(desc . command)~)                                                                                            | ~:bind (("C-c k" . keychain-refresh-environment) ("C-c o h" . osm-home))~                                                                                                              |
|                | With a cons the description will be shown why ~which-key~                                                                                          | ~:bind ("C-c k" ("Refresh keychain" . keychain-refresh-environment) "C-c o h" ("Open OSM at home". osm-home))~                                                                         |
| [[https://github.com/jwiegley/use-package#binding-to-keymaps][~:bind-keymap~]] | Binds a keymap to the given key chord.                                                                                                             | ~:bind ("s-p" . projectile-command-map))~ / ~:bind ("s-p" ("Projectile" . projectile-command-map))~ (untested)                                                                         |
| ~:map~         | Within a ~:bind~ you can provide the mapping and modify key maps.                                                                                  | ~:bind (:map projectile-command-map ("s-p p" . projectile-switch-project))~ / ~:bind (:map projectile-command-map ("s-p p" ("Switch project" . projectile-switch-project))~ (untested) |
| [[https://github.com/jwiegley/use-package#getting-started][~:config~]]      | Executes code /after/ a package is loaded. Note that using this forces loading of the package.                                                     |                                                                                                                                                                                        |
| ~:commands~    | Creates autoloads for commands, deferring loading modules until they are used.                                                                     |                                                                                                                                                                                        |
| ~:custom~      | Alternative option for customising package, preferable over ~:config~.                                                                             |                                                                                                                                                                                        |
| [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html#Conditional-loading][~:if~]]          | Conditionally load packages.                                                                                                                       |                                                                                                                                                                                        |
| ~:hook~        | Define hooks associated with the package.                                                                                                          |                                                                                                                                                                                        |
| ~:ensure~      | Makes sure a package is loaded (eventually). Should be avoided with built-in packages as it may force downloading of newer version.                |                                                                                                                                                                                        |


Using either ~:config~ or ~:init~ will force a package to be loaded, regardless of whether you use ~:defer~ to delay
loading. Instead the alternative ~:custom~ and ~:hook~ commands should be used.

** ~:custom~

Avoids the need to ~setq~ within ~:config~ / ~:init~ sections

* Initial Setup

Library headers have specific [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][conventions]] which we setup for the ~init.el~ and all child documents. There is a header
and [[sec:footer][footer]].

#+NAME: code-init-header
#+BEGIN_SRC emacs-lisp :tangle yes
  ;;; init.el --- slackline's Emacs configuration -*- lexical-binding: t -*-
  ;; Author: N Shephard <nshephard@protonmail.com>
  ;; Keywords: configuration
  ;; URL: https://www.codeberg.org/slackline/emacs
  ;;; Commentary:
  ;; A literate and reproducible Emacs configuration

  ;;; Code:
#+END_SRC


** Package Manager Setup

The first thing we do is /disable/ ~package-enable-at-startup~ via an ~early-init.el~ because "/If non-nil, packages are
made available before reading the init file (but after reading the early init file)./" and we don't want to load
packages until we need them as it will dramatically slow down startup time.

#+NAME: code-early-init
#+BEGIN_SRC emacs-lisp :tangle early-init.el
;;; early-init.el --- Emacs early init file -*- lexical-binding: t; -*-
;;; early-init.el -- Emacs early init file -*- lexical-binding: t; -*-
;;; Commentary:
;; Runs before init.el is loaded.

;;; Code:

;; Disable package.el to prevent all packages being loaded on startup
(setq package-enable-at-startup nil)

(provide 'early-init)
;;; early-init.el ends here

#+END_SRC


The ~exec-path~ is important as it defines where programs are searched for when executing them, it is used by
~gnu-elpa-keyring-update~ to update certain things (what those are I'm not currently sure but without this first
~use-package gnu-elpa-keyring-update~ fails with ~Cannot open find file: No such file or directory,
exec-path-from-shell~).

#+NAME: code-exec-path
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package exec-path-from-shell
  :ensure t
  :custom
  (when (daemonp) (exec-path-from-shell-initialize))
  (exec-path-from-shell-copy-env "SSH_AGENT_PID")
  (exec-path-from-shell-copy-env "SSH_AGENT_SOCK")
  (exec-path (append '("~/bin"
                          "~/.local/bin"
                          "~/.cargo/bin/"
                          "~/.node/bin/"
                          )
			exec-path)))
#+END_SRC

** use-package

We now configure [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][use-package]].

Initially I used to use the example [[https://ianyepan.github.io/posts/setting-up-use-package/][here]] which made sure ~use-package~ was always installed, but since the ~use-package~
is now part of core this is no longer required. The configuration options remain though on the off-chance I have to use
a system with outdated versions of Emacs

*NB* the following code block is /not/ tangled to configuration.

#+NAME: code-use-package-install
#+BEGIN_SRC emacs-lisp :tangle no
  (require 'package)
  (add-to-list 'package-archives '("gnu"   . "https://elpa.gnu.org/packages/"))
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+END_SRC

We configure ~use-package~ below, not all of the values that are set (via ~setq~) are ~use-package~ variables but since
they pertain to downloading and installing packages I keep them here. Because there can be issues with GPG keys when
they are updated we first update the ~gnu-elpa-keyring~ using [[https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html][gnu-elpa-keyring-update]], although this itself requires


#+NAME: code-use-package-config
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package gnu-elpa-keyring-update
  :ensure t)

(use-package use-package
  :config
  (setq use-package-always-ensure t)
  (setq use-package-expand-minimally t)
  ;; On some systems we have problems communicating with ELPA (https://emacs.stackexchange.com/a/62210)
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
  ;; Adding repositories along with priority https://emacs.stackexchange.com/a/2989/10100
  (setq package-archives
      '(("GNU ELPA"	. "https://elpa.gnu.org/packages/")
        ("NonGNU ELPA"  . "https://elpa.nongnu.org/nongnu/")
        ("MELPA Stable" . "https://stable.melpa.org/packages/")
        ("MELPA"	. "https://melpa.org/packages/")
        ("jcs elpa" . "https://jcs-emacs.github.io/jcs-elpa/packages/"))
      package-archive-priorities
      '(("MELPA" . 10)
        ("GNU ELPA"	. 5)
        ("NonGNU ELPA"	. 5)
        ("MELPA Stable"	. 3)
        ("jcs elpa" . 0)
        )))

#+END_SRC

*** Emacs Package Archives

There are multiple sources of Emacs packages, including those who self-host serves such as ~jcs elpa~ listed below.

+ [[https://melpa.org/][MELPA]] for the latest versions of packages and [[https://stable.melpa.org/packages/][MELPA Stable]] when you don't want bleeding edge.
+ [[https://elpa.gnu.org/packages/][GNU ELPA]] for pure Free Open Source Software
+ [[https://elpa.nongnu.org/nongnu/][NonGNU ELPA Packages]] for not quite Free Open Source Software
+ [[https://jcs-emacs.github.io/jcs-elpa/packages/][jcs elpa]]

Because the same package can be hosted across these repositories, sometimes the same version, sometimes newer, it is
useful to be able to set the ~package-archive-priorities~ where each is assigned a priority value.

** Byte Compiling
<<sec:byte-compiling>>

Byte-compilation takes your ASCII plain-text configuration files saved in ~.el~ and turns them into computer code
(~.elc~) which can be loaded quicker. There are a couple of options available ~auto-compile~ and ~compile-angel~ being
two that I have explored before. I have a hook to [[https://emacs.stackexchange.com/a/110][hide the compilation buffer]] on completion of compiling as I got fed up
of these being thrust into the foreground (*NB* currently).

*** ~auto-compile~
<<sec:auto-compile>>

Not currently tangled.

#+NAME: code-auto-compile
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package auto-compile
    :custom
    (auto-compile-on-load-mode t)
    (auto-compile-on-save-mode t)
    (load-prefer-newer t)
    (native-comp-jit-compilation t)
    :hook
    (compilation-finish-functions (lambda (buf strg) (kill-buffer buf))))
#+END_SRC

*** ~compile-angle~

The [[https://github.com/jamescherti/compile-angel.el][~compile-angel~]] package seeks to improve on ~auto-compile~.

Not currently tangled.

#+NAME: code-compile-angel
#+BEGIN_SRC emacs-lisp :tangle no
(use-package compile-angel
  :ensure t
  :demand t
  :custom
  (compile-angel-verbose nil)
  :config
  (compile-angel-on-load-mode)
  (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode))
#+END_SRC


* Emacs Global Configuration

Before loading any packages we configure Emacs itself. This uses ~:config~ as we /always/ want to load and use this
configuration and we don't need to ~:defer~.

I typically use Emacs in its own GUI window but disable a lot of the graphical components such as scroll and tool
bars.

** Emacs
<<sec:emacs>>

#+NAME: code-emacs-config
#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package emacs
    :init
    (epa-file-enable)
    (tool-bar-mode -1)
    (scroll-bar-mode -1)
    (menu-bar-mode 1)
    (global-display-line-numbers-mode 1)
    (global-hl-line-mode 1)
    (savehist-mode 1)
    (recentf-mode 1)
    (global-auto-revert-mode 1)
    :config
    ;; Add local lisp for miscellaneous things
    (add-to-list 'load-path "~/.config/emacs/elpa/") ; Local LISP
    (add-to-list 'load-path "~/.config/emacs/lisp/") ; Local LISP
    (setq custom-file "~/.config/emacs/custom.el")
    (setq package-install-upgrade-built-in t) ; Upgrade built-in packages
    (setq enable-recursive-minibuffers t) ; Vertico - open new minibuffers from inside a minibuffer
    (setq inhibit-startup-message t) ; Hide the startup message
    (setq global-visual-line-mode t) ; Visual line wrap
    (setq inhibit-startup-screen t) ; Disable startup screen
    (setq initial-scratch-message "") ; Make *scratch* buffer blank
    (setq confirm-kill-processes nil) ; Stop confirming the killing of processes
    (setq ring-bell-function 'ignore)  ; Disable bell sound
    (setq global-auto-revert-non-file-buffers t) ; Update non-file buffers (Dired) when disk changes
    (setq use-dialog-box nil) ; No dialog pop-ups
    (setq history-length 1000) ; Mini-buffer history
    (setq-default fill-column 120) ; Reset line-length
    (setq undo-limit 320000) ; Increase the undo history limits
    (setq vc-follow-symlinks t) ; open source of symlink maintain vc (https://stackoverflow.com/a/30900018/1444043)
    (setq winner-mode t) ; toggling window configuration
    (setq initial-scratch-message nil)
    (setq pixel-scroll-precision-mode t)
    (setq lisp-indent-offset 2)
    (setq undo-strong-limit 640000)
    (setq mode-line-compact t)
    (setq dired-dwim-target t) ; move file to other pane as default destination
    (setq global-goto-address-mode t)
    ;; (setq browse-url-browser-function 'eww-browse-url) ; Set eww as the default browser
    (setq-default indent-tabs-mode nil)
    (setq-default tab-width 4)
    (setq-default sh-basic-offset 2)
    (setq-default sh-indentation 2)
    (setq-default cursor-type 'bar)     ; Line-style cursor similar to other text editors
    ;; (set-cursor-color "#62088A") ; Dark purple (not very visible)
    (set-cursor-color "#0AFF00") ; Bright Green (stands out better)
    (setq-default frame-title-format '("%f"))     ; Make window title the buffer name
    (setopt dictionary-server "dict.org")
    ;; Turn off package install warnings https://codeberg.org/jcastp/emacs.d/src/branch/main/emacs-config.org#headline-16
    ;; (when (and (fboundp 'native-comp-available-p)
    ;;         (native-comp-available-p))
    ;;   (setq native-comp-async-report-warnings-errors nil
    ;;     native-comp-deferred-compilation t))
    (set-frame-parameter nil 'alpha-background 85) ; Transparency
    (add-to-list 'default-frame-alist '(alpha-background . 85))
    ;; https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
    (add-to-list 'display-buffer-alist
      '("\\`\\*\\(Warnings\\|Compile-Log\\)\\*\\'"
	 (display-buffer-no-window)
	 (allow-no-window . t)))
    :bind (("C-c U" . revert-buffer)
	    ("C-c D" . toggle-debug-on-error)
	    ;; Org
	    ("\C-c l" . org-store-link)
	    ("\C-c c" . org-capture)
	    ("\C-c a" . org-agenda)
	    ("\C-c b" . org-iswitchb)
	    ("C-x p i" . org-org-cliplink) ;; From : https://github.com/rexim/org-cliplink
	    ;; Magit /code review
	    ("C-x g" . magit-status)
	    ("C-c R" . code-review-forge-pr-at-point)
	    ("s-SPC" . cycle-spacing))
    :hook
    ((latex-mode
       markdown-mode
       org-mode
       prog-mode
       text-mode) . auto-fill-mode)
    ((latex-mode
       prog-mode) . hs-minor-mode)
    (compilation-finish-functions . (lambda (buf strg) (kill-buffer buf))) ;; https://emacs.stackexchange.com/a/110
    (auto-fill-function . do-auto-fill)
    (before-save . delete-trailing-whitespace) ;; https://emacs.stackexchange.com/a/40773/10100
    (before-save . do-auto-fill)
    (dired-mode-hook . auto-revert-mode) ; auto refresh dired when files change
    ;; imenu http://yummymelon.com/devnull/til-imenu.html
    ((markdown-mode
       makefile-mode
       prog-mode) . imenu-add-menubar-index)
    ((markdown-mode
       makefile-mode
       prog-mode) . (lambda () (setq imenu-auto-rescan t))))
#+END_SRC

** SSH Agency
<<sec:ssh-agency>>

[[https://github.com/magit/ssh-agency][ssh-agency]] takes care of handling SSH keys for us so its useful to ensure it is loaded early.

#+NAME: code-ssh-agency
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ssh-agency
  :ensure t
  :custom (ssh-agency-keys '("~/.ssh/id_ed25519" "~/.ssh/haldane_ed25519")))
#+END_SRC

* Completion and Navigation
<<sec:completion-navigation>>

There are various frameworks and packages available to aid with (auto-)completion such [[https://company-mode.github.io/manual/][Company]], [[https://emacs-helm.github.io/helm/][Helm]] or [[https://github.com/abo-abo/swiper][Ivy]]. I've
explicitly gone with Company but in revising my configuration to write this literate version it looks like I may have
pulled the others in as dependencies of other packages but have opted to purge those from now on.

** Company Mode

[[https://company-mode.github.io/manual/][Company mode]] is a modular text completion framework.

#+NAME: code-company
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package company
  :ensure t
  :defer 0.5
  :hook
  (text-mode . company-mode)
  (prog-mode . company-mode)
  (org-src-mode . company-mode)
  ;; https://themagitian.github.io/posts/emacsconfig/
  :custom
  (company-minimum-prefix-length 3)
  (company-idle-delay 0.3)
  (company-selection-wrap-around t)
  (company-dabbrev-other-buffers t)
  (company-dabbrev-code-other-buffers t)
  (custom-set-faces
   '(company-tooltip ((t (:background "#3e4452"))))
   '(company-tooltip-selection ((t (:background "#454c59"))))
   '(company-tooltip-common ((t (:background "#3e4452"))))
   '(company-scrollbar-bg ((t (:background "#282c34"))))))

#+END_SRC

** Consult
<<sec:consult>>

[[https://github.com/minad/consult][Consult]] "/provides search and navigation commands/" it is compatible with [[sec:vertico][vertico]] and can be combined with [[sec:marginalia][marginalia]],
[[sec:embark][embark]] and [[sec:orderless][orderless]].

#+NAME: code-consult
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package consult
  ;; Replace bindings. Lazily loaded by `use-package'.
  :bind (;; C-c bindings in `mode-specific-map'
         ("C-c M-x" . consult-mode-command)
         ("C-c h" . consult-history)
         ("C-c k" . consult-kmacro)
         ("C-c m" . consult-man)
         ("C-c i" . consult-info)
         ([remap Info-search] . consult-info)
         ;; C-x bindings in `ctl-x-map'
         ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
         ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
         ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
         ;; Custom M-# bindings for fast register access
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
         ("C-M-#" . consult-register)
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ;; M-g bindings in `goto-map'
         ("M-g e" . consult-compile-error)
         ("M-g r" . consult-grep-match)
         ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ;; M-s bindings in `search-map'
         ("M-s d" . consult-find)                  ;; Alternative: consult-fd
         ("M-s c" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ;; Isearch integration
         ("M-s e" . consult-isearch-history)
         :map isearch-mode-map
         ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
         ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
         ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
         ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
         ;; Minibuffer history
         :map minibuffer-local-map
         ("M-s" . consult-history)                 ;; orig. next-matching-history-element
         ("M-r" . consult-history))                ;; orig. previous-matching-history-element

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :custom
  ;; Tweak the register preview for `consult-register-load',
  ;; `consult-register-store' and the built-in commands.  This improves the
  ;; register formatting, adds thin separator lines, register sorting and hides
  ;; the window mode line.
  (advice-add #'register-preview :override #'consult-register-window)
  (register-preview-delay 0.5)

  ;; Use Consult to select xref locations with preview
  (xref-show-xrefs-function #'consult-xref
   xref-show-definitions-function #'consult-xref))
#+END_SRC

** Embark
<<sec:embark>>

[[https://github.com/oantolin/embark/][Embark]] "/makes it easy to choose a command to run based on what is near point, both during a minibuffer completion
session (in a way familiar to Helm or Counsel users) and in normal buffers/". I've not yet setup [[https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt][which-key like menu
prompt]] but may do one day.

#+NAME: code-embark
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package embark
  :ensure t
  :defer 0.5
  :bind
  (("C-." . embark-act)         ;; pick some comfortable binding
   ("C-;" . embark-dwim)        ;; good alternative: M-.
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'
  :custom
  ;; Optionally replace the key help with a completing-read interface
  (prefix-help-command #'embark-prefix-help-command)
  ;; (add-to-list 'vertico-multiform-categories '(embark-keybinding grid))
  (embark-indicators
	'(embark-minimal-indicator  ; default is embark-mixed-indicator
	  embark-highlight-indicator
	  embark-isearch-highlight-indicator))
  ;; Show the Embark target at point via Eldoc. You may adjust the
  ;; Eldoc strategy, if you want to see the documentation from
  ;; multiple providers. Beware that using this can be a little
  ;; jarring since the message shown in the minibuffer can be more
  ;; than one line, causing the modeline to move up and down:
  ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
  ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)
  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))
;; Consider

#+END_SRC

** Marginalia
<<sec:marginalia>>

[[https://github.com/minad/marginalia/][Marginalia]] enables rich annotations. The ~marginalia-cycle~ command is mapped to ~M-A~ in both the
~minibuffer-local-map~ and the ~completion-list-mode-map~. As we always want to have Marginalia available we ~:init~ it
with the ~marginalia-mode~ rather than deferring.

#+NAME: code-marginalia
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package marginalia
  :ensure t
  ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
  ;; available in the *Completions* buffer, add it to the
  ;; `completion-list-mode-map'.
  :bind
  (:map minibuffer-local-map
	("M-A" . marginalia-cycle))
  (:map completion-list-mode-map
	("M-A" . marginalia-cycle))
  ;; The :init section is always executed.
  :init

  ;; Marginalia must be activated in the :init section of use-package such that
  ;; the mode gets enabled right away. Note that this forces loading the
  ;; package.
  (marginalia-mode))

#+END_SRC

** Movetext
<<sec:movetext>>

[[https://github.com/emacsfodder/move-text][move-text]] is a simple package makes it easy to move the current line or region up (~M-up~) or down (~M-down~).

#+NAME: code-movetext
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package move-text
  :ensure t
  :defer 0.5
  :config
  (move-text-default-bindings))

#+END_SRC

** Orderless
<<sec:orderless>>

[[https://github.com/oantolin/orderless][Orderless]]

#+NAME: code-orderless
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic)
	completion-category-defaults nil
	completion-category-overrides '((file (styles basic partial-completion)))))

#+END_SRC

** Savehist

Savehist (can't find package homepage) persists history over Emacs restarts and helps with [[sec:vertico][Vertico]].

#+NAME: code-savehist
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package savehist
  :ensure t
  :init
  (savehist-mode))

#+END_SRC

** Vertico
<<sec:vertico>>

[[https://github.com/minad/vertico][Vertico]]

#+NAME: code-vertico
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package vertico
  :ensure t
  :init
  (vertico-mode)
  :config
  ;; Different scroll margin
  ;; (setq vertico-scroll-margin 0)

  ;; Show more candidates
  ;; (setq vertico-count 20)

  ;; Grow and shrink the Vertico minibuffer
  ;; (setq vertico-resize t)

  ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
  ;; (setq vertico-cycle t)

  ;; TAB completion - completes path selection rather than selecting current point
  ;; (keymap-set vertico-map "TAB" #'minibuffer-complete)
  )

#+END_SRC

** Vundo
<<sec:vundo>>

[[https://github.com/casouri/vundo][Vundo]] provides a Visual insight into the Undo history of a buffer, I find it really useful and the [[https://archive.casouri.cc/note/2021/visual-undo-tree/index.html][authors overview of
undo buffer history]] was insightful too.

#+NAME: code-vundo
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package vundo
  :ensure t
  :defer 2
  :hook
  (prog-mode . vundo-popup-mode)
  (text-mode . vundo-popup-mode))

#+END_SRC


** Which-key
<<sec:which-key>>

*TODO* Sort this section out!

[[https://github.com/justbur/emacs-which-key][which-key]] (now part of Emacs core) is a minor mode which pops up a buffer to show what "which key", if pressed next,
will do. Its incredibly useful and should be enabled by default on all systems. However, as noted above on [[sec:conf-use-package][configuring
use-package]] keys should be bound with ~(desc . command)~ to include a description as to what they do, otherwise you end
up with a lot of ~prefix~ and its value disappears.

#+NAME: code-which-key
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package which-key
  :ensure t
  :defer 0.5
  :config (which-key-mode)
  (global-set-key (kbd "<f8>") 'which-key-show-major-mode)
  ;; +prefix isn't helpful, lets sort that out via...
  ;; https://gist.github.com/mmarshall540/a12f95ab25b1941244c759b1da24296d)
  (which-key-add-key-based-replacements
   "<f1> 4"        "help-other-win"
   "<f1>"          "help"
   "<f2>"          "2-column"
   "C-c"           "mode-and-user"
   "C-h 4"         "help-other-win"
   "C-h"           "help"
   "C-x 4"         "other-window"
   "C-x 5"         "other-frame"
   "C-x 6"         "2-column"
   "C-x 8"         "insert-special"
   "C-x C-k C-q"   "kmacro-counters"
   "C-x C-k C-r a" "kmacro-add"
   "C-x C-k C-r"   "kmacro-register"
   "C-x C-k"       "keyboard-macros"
   "C-x RET"       "encoding/input"
   "C-x a i"       "abbrevs-inverse-add"
   "C-x a"         "abbrevs"
   "C-x n"         "narrowing"
   "C-x p"         "projects"
   "C-x r"         "reg/rect/bkmks"
   "C-x t ^"       "tab-bar-detach"
   "C-x t"         "tab-bar"
   "C-x v M"       "vc-mergebase"
   "C-x v b"       "vc-branch"
   "C-x v"         "version-control"
   "C-x w ^"       "window-detach"
   "C-x w"         "window-extras"
   "C-x x"         "buffer-extras"
   "C-x"           "extra-commands"
   "M-g"           "goto-map"
   "M-s h"         "search-highlight"
   "M-s"           "search-map")
  (with-eval-after-load 'page-ext
    (which-key-add-key-based-replacements
     "C-x C-p" "page-extras"))
  ;; Org-mode provides some additional prefix-keys in `org-mode-map'.
  (with-eval-after-load 'org
    (which-key-add-keymap-based-replacements org-mode-map
      "C-c \""      "org-plot"
      "C-c C-v"     "org-babel"
      "C-c C-x"     "org-extra-commands")))

#+END_SRC

** helpful
<<sec:helpful>>

[[https://github.com/Wilfred/helpful][helpful]] makes it simple to find out what keys, functions, modes etc. do.

*TODO* Improve key-bindings here.

#+NAME: code-helpful
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package helpful
  :ensure t
  :defer 0.5
  :bind
  ;; Note that the built-in `describe-function' includes both functions
  ;; and macros. `helpful-function' is functions only, so we provide
  ;; `helpful-callable' as a drop-in replacement.
  (global-set-key (kbd "C-h f") #'helpful-callable)
  (global-set-key (kbd "C-h v") #'helpful-variable)
  (global-set-key (kbd "C-h k") #'helpful-key)
  ;; Lookup the current symbol at point. C-c C-d is a common keybinding
  ;; for this in lisp modes.
  (global-set-key (kbd "C-c C-d") #'helpful-at-point)

  ;; Look up *F*unctions (excludes macros).
  ;;
  ;; By default, C-h F is bound to `Info-goto-emacs-command-node'. Helpful
  ;; already links to the manual, if a function is referenced there.
  (global-set-key (kbd "C-h F") #'helpful-function)

  ;; Look up *C*ommands.
  ;;
  ;; By default, C-h C is bound to describe `describe-coding-system'. I
  ;; don't find this very useful, but it's frequently useful to only
  ;; look at interactive functions.
  (global-set-key (kbd "C-h C") #'helpful-command))

#+END_SRC

* Version Control
<<sec:version-control>>

** Magit
<<sec:magit>>

[[https://magit.vc/][Magit]] is amazing! Hands down the package I use the most in Emacs for my daily work, note taking and more as I have
literally everything under Git version control.

+ [[https://www.reddit.com/r/emacs/comments/17af1q5/opening_magit_fullframe_then_restoring_windows_on/][Opening Magit full-frame then restoring windows]]
+ [[https://mbork.pl/2025-05-12_Coloring_Git_output_in_Magit][Coloring Git output in Magit]]

#+NAME: magit
#+BEGIN_SRC emacs-lisp :tangle yes
;;
(use-package magit
  :ensure t
  :custom
  (magit-repository-directories
	`(("~/dotfiles" . 1)
	  ("~/.config/emacs/" . 1)
	  ("~/org/" . 1)
	  ("~/work/git/" . 2)
	  ("~/work/python/tcx2gpx/" . 1)
	  ("~/work/python/wpweather/" . 1)
	  ))
  (auth-sources '("~/.authinfo.gpg"))
  ;;
  (magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)
  (magit-bury-buffer-function 'magit-restore-window-configuration)
  (magit-pull-or-fetch t)
  (magit-log-margin '(t "%F %R" magit-log-margin-width t 18))
  (magit-process-finish-apply-ansi-colors t)
  ;; Don't want auto-fill-mode enabled for the following modes, probably a smarter way of doing this under :hooks
  ;; perhaps?
  (remove-hook 'git-commit-mode #'turn-on-auto-fill)
  (remove-hook 'forge-post-mode #'turn-on-auto-fill)
  :hook
  (add-hook 'after-save-hook 'magit-after-save-refresh-status t)
  :bind
  (global-set-key (kbd "C-c m C") 'magit-clone)
  (global-set-key (kbd "C-c m F") 'magit-pull-from-upstream)
  (global-set-key (kbd "C-c m P") 'magit-push-current-to-upstream)
  (global-set-key (kbd "C-c m R") 'magit-file-rename)
  (global-set-key (kbd "C-c m f") 'forge-pull)
  (global-set-key (kbd "C-c m d d") 'nds:magit-show-with-difftastic)
  (global-set-key (kbd "C-c m d r") 'magit-diff-range)
  (global-set-key (kbd "C-c m d s") 'magit-diff-staged)
  (global-set-key (kbd "C-c m l l") 'magit-log)
  (global-set-key (kbd "C-c m l f") 'magit-log-buffer-file)
  (global-set-key (kbd "C-c m l o") 'magit-log-other))

#+END_SRC

** code-review
<<sec:code-review>>

[[https://github.com/wandersoncferreira/code-review/][code-review]]

#+NAME: code-code-review
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package code-review
  :ensure t
  :custom
  (code-review-fill-column 120)
  (code-review-new-buffer-window-strategy #'switch-to-buffer)
  :hook
  (code-review-mode . emojify-mode))

#+END_SRC

** consult-gh
<<sec:consult-gh>>


[[https://github.com/armindarvish/consult-gh][consult-gh]] is a [[https://cli.github.com/][GitHub CLI]] client inside Emacs that uses [[sec:consult][Consult]].

Not currently tangled.

#+NAME: code-consult-gh
#+BEGIN_SRC emacs-lisp :tangle no

(use-package consult-gh
  :ensure t
  :after consult
  :custom
  (consult-gh-default-clone-directory "~/projects")
  (consult-gh-show-preview t)
  (consult-gh-preview-key "C-o")
  (consult-gh-repo-action #'consult-gh--repo-browse-files-action)
  (consult-gh-issue-action #'consult-gh--issue-view-action)
  (consult-gh-pr-action #'consult-gh--pr-view-action)
  (consult-gh-code-action #'consult-gh--code-view-action)
  (consult-gh-file-action #'consult-gh--files-view-action)
  (consult-gh-notifications-action #'consult-gh--notifications-action)
  (consult-gh-dashboard-action #'consult-gh--dashboard-action)
  (consult-gh-large-file-warning-threshold 2500000)
  (consult-gh-prioritize-local-folder 'suggest)
  (consult-gh-default-orgs-list (consult-gh--get-current-orgs t))
  :hook
  ;; Add a hook to change default organizations when the account is switched
  (add-hook 'consult-gh-auth-post-switch-hook (lambda (&rest args) (setq consult-gh-default-orgs-list (consult-gh--get-current-orgs t))))

  ;; Remember visited orgs and repos across sessions
  (add-to-list 'savehist-additional-variables 'consult-gh--known-orgs-list)
  (add-to-list 'savehist-additional-variables 'consult-gh--known-repos-list))

#+END_SRC

** consult-gh-forge
<<sec:consult-gh-forge>>

Works in conjunction with [[sec:consult-gh][consult-gh]].

Not currently tangled.

#+NAME: code-consult-gh-forge
#+BEGIN_SRC emacs-lisp :tangle no
;; ;; Install `consult-gh-forge' for forge actions
(use-package consult-gh-forge
  :ensure t
  :defer 3
  :after (consult-gh)
  :custom
  (consult-gh-forge-mode +1)
  (consult-gh-forge-timeout-seconds 20))
#+END_SRC

** difftastic
<<sec:difftastic>>

[[https://github.com/pkryger/difftastic.el][difftastic.el]] brings the brilliant code aware [[https://difftastic.wilfred.me.uk/][difftastic]] ([[https://github.com/Wilfred/difftastic][GitHub]]) to Emacs. This package replaces an earlier [[https://tsdh.org/posts/2022-08-01-difftastic-diffing-with-magit.html][custom configuration]]
that I found and had happily used for a while.
#+NAME: code-difftastic
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package difftastic
  :ensure t
  :demand t
  :bind (:map magit-blame-read-only-mode-map
              ("D" . difftastic-magit-show)
              ("S" . difftastic-magit-show))
  :custom
  (eval-after-load 'magit-diff
    '(transient-append-suffix 'magit-diff '(-1 -1)
       [("D" "Difftastic diff (dwim)" difftastic-magit-diff)
        ("S" "Difftastic show" difftastic-magit-show)])))

#+END_SRC

** Forge
<<sec:forge>>

#+NAME: forge
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package forge
  :ensure t
  :defer 0.5
  :after magit
  :config
  (push '("forgejo.nshephard.dev"
          "forgejo.nshephard.dev/api/v1"
          "forgejo.nshephard.dev"
          forge-forgejo-repository)
	forge-alist))

#+END_SRC

** ghub
<<sec:ghub>>

#+NAME: code-ghub
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ghub
  :ensure t
  :defer 0.5
  :after (magit))
#+END_SRC

** glab
<<sec:glab>>

#+NAME: code-glab
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package glab
  :ensure t
  :defer 0.5
  :after (magit))
#+END_SRC

** git-cliff
<<sec:git-cliff>>

[[https://github.com/liuyinz/git-cliff.el][git-cliff]]

#+NAME: code-git-cliff
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package git-cliff
  :ensure t)

#+END_SRC

** git-modes
<<sec:git-modes>>

[[https://github.com/magit/git-modes][git-modes]] provides major modes for Git configuration files.

#+NAME: code-git-modes
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package git-modes
  :ensure t
  :defer 3
  :after (magit))

#+END_SRC

** gh-notify
<<sec:gh-notify>>

[[https://github.com/anticomputer/gh-notify][gh-notify]] a "/thin UI veneer on top of Magit/Forge porcelain for juggling large amounts of GitHub notifications at
speed.".

#+NAME: code-gh-notify
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package gh-notify
  :ensure t
  :after (magit))

#+END_SRC

** gitlab-ci-mode
<<sec:gitlab-ci-mode>>

[[https://gitlab.com/joewreschnig/gitlab-ci-mode/][gitlab-ci-mode]]

Currently not tangled.

#+NAME: code-gitlab-ci-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package gitlab-ci-mode
  :ensure t)

#+END_SRC

** gitlab-ci-mode-flycheck
<<sec:gitlab-ci-mode-flycheck>>

[[https://gitlab.com/joewreschnig/gitlab-ci-mode-flycheck/][gitlab-ci-mode-flycheck]]

Currently not tangled.

#+NAME: code-gitlab-ci-mode-flycheck
#+BEGIN_SRC emacs-lisp :tangle no
(use-package gitlab-ci-mode-flycheck
  :ensure t)

#+END_SRC

** git-link
<<sec:git-link>>

[[https://github.com/sshaw/git-link][git-link]]

#+NAME: code-git-link
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package git-link
  :ensure t
  :after (magit)
  :bind
  (global-set-key (kbd "C-c m g g") 'git-link-dispatch)
  (global-set-key (kbd "C-c m g l") 'git-link)
  (global-set-key (kbd "C-c m g c") 'git-link-commit)
  (global-set-key (kbd "C-c m g h") 'git-link-homepage)
  :config
  (require 'git-link-transient))

#+END_SRC

** git-timemachine
<<sec:git-timemachine>>

[[https://codeberg.org/pidu/git-timemachine][git-timemachine]]

#+NAME: code-git-timemachine
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package git-timemachine
  :ensure t
  :defer 3
  :after (magit)
)

#+END_SRC

** gtea
<<sec:gtea>>

#+NAME: code-gtea
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package gtea
  :ensure t
  :defer 0.5
  :after (magit))
#+END_SRC


** magit-delta
<<sec:magit-delta>>

[[https://github.com/dandavison/magit-delta][magit-delta]]

#+NAME: code-magit-delta
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package magit-delta
  :ensure t
  :after magit
  :hook (magit-mode . magit-delta-mode))

#+END_SRC

** magit-gitlab
<<sec:magit-gitlab>>

[[https://gitlab.com/arvidnl/magit-gitlab][magit-gitlab]]

#+NAME: code-magit-gitlab
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package magit-gitlab
  :ensure t
  :defer 3
  :after (magit))

#+END_SRC


** magit-imerge
<<sec:magit-imerge>>

[[https://github.com/magit/magit-imerge][magit-imerge]] is a Magit interface to [[https://github.com/mhagger/git-imerge][git-imerge]]

#+NAME: code-magit-imerge
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package magit-imerge
  :ensure t
  :after (magit))

#+END_SRC

** magit-stats
<<sec:magit-stats>>

#+NAME: code-magit-stats
#+BEGIN_SRC emacs-lisp :tangle yes
;; https://github.com/LionyxML/magit-stats
(use-package magit-stats
  :ensure t
  :after (magit))

#+END_SRC

** orgit
<<sec:orgit>>

[[https://github.com/magit/orgit][orgit]]

#+NAME: code-orgit
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package orgit
  :after (magit))

#+END_SRC

** orgit-forge
<<sec:orgit-forge>>

[[https://github.com/magit/orgit-forge][orgit-forge]]

#+NAME: code-orgit-forge
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package orgit-forge
  :after magit
  :bind (:map magit-mode-map
	      ("C-c m c" . orgit-store-link))
  (:map org-mode-map
	("C-c m v" . org-insert-last-stored-link)))

#+END_SRC

** pr-review
<<sec:pr-review>>

[[https://github.com/blahgeek/emacs-pr-review][pr-review]]
#+NAME: code-pr-review
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package pr-review
  :ensure t
  :after ghub)

#+END_SRC

** treemacs-magit
<<sec:treemacs-magit>>

#+NAME: code-treemacs-magit
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package treemacs-magit
  :ensure t)

#+END_SRC

* Transient
<<sec:transient>>

** Transient Custom Prefixes
<<sec:transient-custom-prefixes>>

#+NAME: code-magit-aux-commands
#+BEGIN_SRC emacs-lisp :tangle yes
(transient-define-prefix nds:magit-aux-commands ()
			 "My personal auxiliary magit commands."
			 ["Auxiliary commands"
			  ("o" "Orgit Link" orgit-store-link)
			  ])

#+END_SRC

* Org mode
<<sec:org-mode>>

[[https://orgmode.org/][Orgmode]] is "/A GNU Emacs major mode for keeping notes, authoring documents, computational notebooks, literate
programming, maintaining to-do lists, planning projects, and more - in a fast and effective plain-tests system./"

Sources of some of the options are linked below.

+ [[https://mahmoodsh.com/efficiently_parsing_org_files.html][efficiently parsing org files]] shows how to speed up loading big Org files.
+ [[https://anonimno.codeberg.page/tracking%20worktime.html][org-clock-persist 'history]]
+ [[https://stackoverflow.com/a/38477233/1444043][org-image-actual-width]]
+ [[https://emacs.stackexchange.com/a/21267/10100][org-startup-with-inline-images]]
+ [[https://emacs.stackexchange.com/a/3570/10100][org-confirm-babel-evaluate]]
+ [[https://github.com/erikriverson/org-mode-R-tutorial/blob/master/org-mode-R-tutorial.org#inserting-r-graphical-output][org-format-latex-options]]
+ [[https://hachyderm.io/@al3x/112186172832809202][after-focus-change-function]]
+ [[https://github.com/james-stoup/emacs-org-mode-tutorial#orga87f491=][org-todo-keywords]] set additional keywords (and colours).

#+NAME: code-org-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package org
  :ensure t
  :defer 0.5
  :bind
  (("C-x p i" . 'org-cliplink))
  :config
  (add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
  (global-font-lock-mode 1)
  (org-babel-do-load-languages 'org-babel-load-languages '((emacs-lisp . t)
							   (python . t)
							   (shell . t)
							   (R . t)
							   (latex .t)))
  (org-directory        "~/org/")
  (org-agenda-files '("~/org/agenda.org"
 			   "~/org/gtd/admin.org"
 			   "~/org/gtd/carpentries.org"
 			   "~/org/gtd/clarity.org"
 			   "~/org/gtd/computing.org"
 			   "~/org/gtd/cured.org"
 			   "~/org/gtd/emacs.org"
 			   "~/org/gtd/isoslam.org"
 			   "~/org/gtd/joss.org"
 			   "~/org/gtd/openfest2024.org"
 			   "~/org/gtd/osc.org"
 			   "~/org/gtd/pgfinder.org"
			   "~/org/gtd/reproducibilitea.org"
			   "~/org/gtd/rse.org"
			   "~/org/gtd/rse-competencies.org"
			   "~/org/grd/sheffieldr.org"
 			   "~/org/gtd/tcx2gpx.org"
			   "~/org/gtd/thyroid.org"
			   "~/org/gtd/topostats.org"))
	;; org-tags-alist '()
	(org-startup-indented 0)
	(org-agenda-include-diary t)
	(org-agenda-skip-deadline-if-done t)
	(org-agenda-skip-scheduled-if-done t)
	(org-clock-persist 'history)
	(org-log-done 'time)
	(org-image-actual-width nil)
	(org-export-backends '(beamer html latex md odt))
	(org-startup-with-inline-images t)
	(org-confirm-babel-evaluate nil)
	(org-babel-python-command "~/.virtualenvs/default/bin/python")
	(org-format-latex-options '(:foreground default
		                    :background "rgb 1 1 1"
		                    :scale 1.5
		                    :html-foreground "Black"
		                    :html-background "Transparent"
		                    :html-scale 1.0
		                     :matchers ("begin" "$1" "$" "$$" "\\(" "\\[")))
      (org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(i@/!)" "BLOCKED(b@)"  "|" "DONE(d!)" "WONT-DO(w@/!)" )))
      (org-todo-keyword-faces
        '(("TODO" . (:foreground "GoldenRod" :weight bold))
           ("IN-PROGRESS" . (:foreground "Cyan" :weight bold))
           ("BLOCKED" . (:foreground "Red" :weight bold))
           ("DONE" . (:foreground "LimeGreen" :weight bold))
           ("WONT-DO" . (:foreground "DarkViolet" :weight bold))))

  ;; Disable electric-indent-mode in org buffers
  :hook
  (org-mode . (lambda () (electric-indent-local-mode 0)))
  (org-mode . (lambda () (org-rainbow-tags-mode 1)))
  (after-focus-change-function . (org-save-all-org-buffers)))
  ;; (with-eval-after-load 'org (global-org-modern-mode))

#+END_SRC

There are a lot of org-based packages and extensions, those that are minor tweaks are in sub-sections below, major
things such as [[sec:org-roam][org-roam]] and [[sec:org-gtd][org-gtd]] have their own sections which follow.

*** Org Analyzer
<<sec:org-analyzer>>

[[https://github.com/rksm/clj-org-analyzer/][org-analyzer]] provides a set of functions that parse and summarise your [[sec:org-agenda][org-agenda]] and fires up a web-page to visualise
the results. Very neat and powerful...if you stick to the habit of logging your time on tasks!

#+NAME: code-org-analyzer
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package org-analyzer
  :ensure t
  :defer 2)

#+END_SRC

*** Org Links
<<sec:org-links>>

[[https://codeberg.org/Anoncheg/emacs-org-links][org-links]]

#+NAME: code-org-links
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package org-links
  :ensure t
  :defer 0.5
  :after org-mode)

#+END_SRC

*** Org Modern
<<sec:org-modern>>

[[https://github.com/minad/org-modern][org-modern]] is "/a modern style for Org buffers using font locking and text properties/".

#+NAME: code-org-modern
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package org-modern
  :ensure t
  :defer 0.5
  :after org-mode
  :config (setq
	   ;; Edit settings
	   org-auto-align-tags nil
	   org-tags-column 0
	   org-catch-invisible-edits 'show-and-error
	   org-special-ctrl-a/e t
	   org-insert-heading-respect-content t
	   ;; Org styling, hide markup etc.
	   org-hide-emphasis-markers t
	   org-pretty-entities t
	   org-ellipsis ""
	   ;; Agenda styling
	   org-agenda-tags-column 0
	   org-agenda-block-separator ?
	   org-agenda-time-grid
	   '((daily today require-timed)
	     (800 1000 1200 1400 1600 1800 2000)
	     "  " "")
	   org-agenda-current-time-string
	   " now " ))

#+END_SRC

*** Org Note
<<sec:org-note>>

[[https://github.com/Artawower/orgnote.el][orgnote]] synchronises [[sec:org-roam][org-roam]] notes with the Android application [[https://org-note.com/][orgnote]]. I'm yet to fully adopt using Org on my mobile
device, mainly as I hate typing on mobile, but also I'm yet to settle on an application for working with org files on
mobile.

Not tangled for now.

#+NAME: code-org-note
#+BEGIN_SRC emacs-lisp :tangle no
(use-package orgnote
  :ensure t)

#+END_SRC

*** Org Raindow Tags
<<sec:org-rainbow-tags>>

[[https://github.com/KaratasFurkan/org-rainbow-tags][org-rainbow-tags]] adds random colours to Org tags based on the hash of the tag name, which keeps things consistent.

#+NAME: code-org-rainbow-tags
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package org-rainbow-tags
  :ensure t
  :defer 0.5)

#+END_SRC

*** Org Ref
<<sec:org-ref>>

[[https://github.com/jkitchin/org-ref][org-ref]]

#+NAME: code-org-ref
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package org-ref
  :ensure t
  :after (org-roam))

#+END_SRC

*** Org Tidy
<<sec:org-tidy>>

[[https://github.com/jxq0/org-tidy][org-tidy]] automatically tidies (hides) [[sec:org-mode][org-mode]] property draws.

Not currently tangled.

#+NAME: code-org-tidy
#+BEGIN_SRC emacs-lisp :tangle no
(use-package org-tidy
  :ensure t
  :after (org-mode)
  :hook
  (org-mode . org-tidy-mode))

#+END_SRC

** Org Agenda
<<sec:org-agenda>>

** Org Babel
<<sec:org-babel>>

[[https://orgmode.org/worg/org-contrib/babel/][Org-babel]] started life as Babel but has been integrated into Org core since version 7.0. It provides a literate
programming environment where text and code (from many languages) can be inter-weaved to give reproducible and literate
documents that can be rendered to a range of formats via [[https://orgmode.org/manual/Exporting.html][org-export]].

#+NAME: code-org-babel
#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC

** Org Roam
<<sec:org-roam>>

[[https://www.orgroam.com/][Org-roam]] helps you build a "second brain" of notes using the Zettelkasten method.

#+NAME: code-org-roam
#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC

** Org Capture
<<sec:org-capture>>

[[https://orgmode.org/manual/Capture.html#Capture][Org-capture]] is a useful method of opening transient like nested menus to capture notes in predefined files. It allows
you to specify sections and tables to which entries should be added with pre-defined templates.

#+NAME: code-org-capture
#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC

** Org GTD
<<sec:org-gtd>>

#+NAME: code-org-gtd
#+BEGIN_SRC emacs-lisp :tangle yes

#+END_SRC

* IDE and LSP

Emacs is my Integrated Development Environment when programming and writing documents. I use a number of language
specific modes but also leverage the power of Language Server Protocol (LSP) to help with navigation, function
arguments, refactoring and so forth.

** envdir
<<sec:envdir>>

#+NAME: code-envdir
#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC

** Programming Modes

*** Python Mode
<<sec:python>>

[[https://gitlab.com/python-mode-devs/python-mode][Python mode]] is a major mode for editing Python files. I don't do much to customise this, the following is loaded _after_
[[sec:pyvenv][pyvenv]]...

+ Disable a guess indent message.
+ Enables [[https://ipython.org/][IPython]] as the ~python-shell-interpreter~ and sets some arguments.
+ Defines two custom skeletons, the first to insert a ~print()~ statement with an f-string to show the value of a
  parameters (useful for debugging code). The second to insert a ~@pytest.mark.parametrize()~ test function (which is
  ultimately redundant since I have a [[sec:yasnippet][YASnippet]] template to do the same thing).
+ Maps some keybindings to make it easy to run some short-cuts such as ~python-test-dispatch~, ~pylint~,
  ~blacken-buffer~ and insert some of the common ~python-skeleton~'s.

#+NAME: code-python
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package python
  :after (pyvenv)
  :ensure t
  :defer 1
  :config
  ;; Remove guess indent python message
  (setq python-indent-guess-indent-offset-verbose nil
	python-shell-interpreter "ipython"
	python-shell-interpreter-args "-i --simple-prompt"
	python-environment-directory venv-location)
  (add-to-list 'python-shell-completion-native-disabled-interpreters "ipython")
  ;; Define a skeleton for printing https://emacs.stackexchange.com/questions/80320/defining-custom-python-skeletons
  (python-skeleton-define print
			  "Insert a print statement that will show the value of the argument."
			  "Enter the variable/object name: "
			  "print(f'\\n{" str "=}\\n')")
  (python-skeleton-define parameterized-test
			  "Insert a test with @pytest.mark.parametrize() fixture."
			  "Enter the parameters: "
			  "@pytest.mark.parametrize(\n    (" str "),\n    [\n        pytest.param(,id=\"\"),\n    ]\n)\ndef test_()
-> None:")
  :bind (:map python-mode-map
	      ("C-c p t" . python-pytest-dispatch)
	      ("C-c p l" . pylint)
	      ("C-c p y" . pylint-insert-ignore-comment)
	      ("C-c p n" . numpydoc-generate)
	      ("C-c p b" . blacken-buffer)
	      ("C-c p r" . ruff-format-buffer)
	      ("C-c p v" . pyvenv-workon)
	      ("C-c p T c" . python-skeleton-class)
	      ("C-c p T d" . python-skeleton-def)
	      ("C-c p T f" . python-skeleton-for)
	      ("C-c p T i" . python-skeleton-if)
	      ("C-c p T m" . python-skeleton-import)
	      ("C-c P" . python-skeleton-print)
	      ("C-c p T t" . python-skeleton-try)
	      ("C-c p T T" . python-skeleton-parameterized-test)
	      ("C-c p T w" . python-skeleton-while)))

#+END_SRC

**** Virtual Environments

I use two packages to manage virtual environments in conjunction with [[sec:envdir][~envdir~]]. For general Python virtual environments
I use [[https://github.com/jorgenschaefer/pyvenv][pyvenv]] which allows me to define on a per-host basis the location of virtual environments which are defined
globally, typically I use ~~/.virtualenvs~ which I will activate via a project/repository specific ~.envrc~ file which
[[sec:envdir][envdir]] takes care of activating when I switch to the project directory. Recently I've started using [[https://docs.astral.sh/uv/][uv]] to manage
packages and projects and so have also added [[https://github.com/z80dev/uv-mode][uv-mode]] to my configuration to take care of activating project specific
virtual environments which reside in the ~.venv~ directory created by ~uv~ within the project directory itself.

***** pyvenv
<<sec:pyvenv>>

#+NAME: code-pyvenv
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package pyvenv
  :ensure t
  :defer 1
  :config
  ;; Setting work on to easily switch between environments
  (setenv "WORKON_HOME" (expand-file-name "~/.virtualenvs/"))
  (pyvenv-mode 1)
  ;; Display virtual envs in the menu bar
  (setq pyvenv-menu t
	venv-byhost
	'(("kimura" . "~/.virtualenvs/")
	  ("fisher" . "~/.virtualenvs/")
	  ("haldane" . "~/.virtualenvs/")
	  ("ovh" . "~/.virtualenvs/")
	  ("alarmpi" . "~/.virtualenvs/")
	  ("alarmpi-4b" . "~/.virtualenvs/"))
	venv-location (cdr
		       (assoc system-name venv-byhost))
	default-venv-byhost
	'(("kimura" . "~/.virtualenvs/default")
	  ("fisher" . "~/.virtualenvs/python3_9")
	  ("haldane" . "~/.virtualenvs/default")
	  ("ovh" . "~/.virtualenvs/default")
	  ("alarmpi" . "~/.virtualenvs/default")
	  ("alarmpi-4b" . "~/.virtualenvs/default"))
	default-venv (cdr
		      (assoc system-name default-venv-byhost))
	python-environment-directory venv-location)
  ;; Restart the python process when switching environments
  (add-hook 'pyvenv-post-activate-hooks (lambda ()
					  (pyvenv-restart-python)))
  :hook (python-mode . pyvenv-mode)
  (after-init-hook . (pyvenv-workon default-env))
  )
#+END_SRC

***** pyvenv-auto
<<sec:pyvenv-auto>>

#+NAME: code-pyvenv
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package pyvenv-auto
  :ensure t
  :hook ((python-mode . pyvenv-auto-run)))

#+END_SRC

***** uv-mode
<<sec:uv-mode>>

[[https://github.com/z80dev/uv-mode][uv-mode]] "/provides seamless integration between [[https://docs.astral.sh/uv][uv]] and Emacs ~python-mode~/".

#+NAME: code-uv-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package uv-mode
  :ensure t
  :hook (python-mode . uv-mode-auto-activate-hook))

#+END_SRC

**** Additional packages

***** Blacken
<<sec:blacken>>

[[https://black.readthedocs.io/en/stable/][Black]] is "/the uncompromising code formatter/" and Emacs has the [[https://github.com/pythonic-emacs/blacken][blacken]] package which allows applying Black formatting
to a buffer via keybinding (see above configuration option under [[sec:python][Python]]) or automatically on saving.

#+NAME: code-blacken
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package blacken
  :ensure t
  :after (python-mode)
  :custom
  (blacken-line-length 120)
  :hook (python-mode . blacken-mode))
#+END_SRC

***** Pylint
<<sec:pylint>>

There is an orphaned [[https://github.com/emacsorphanage/pylint][pylint]] package which is referenced for completeness. Typically I defer running [[https://pylint.org][Pylint]] to a
[[https://pre-commit.com][Pre-commit]] hook.

#+NAME: code-pylint
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package pylint
  :hook (python-mode . pylint-add-menu)
  (python-mode . add-key-bindings))

#+END_SRC

***** Pytest
<<sec:pytest>>

[[https://pytest.org][Pytest]] is well supported via [[https://github.com/wbolster/emacs-python-pytest][emacs-python-pytest]]. I've bound ~python-pytest-dispatch~ to ~C-c p t~ which brings up a
transient buffer with options for running ~pytest~ on a given file or function at the cursor location. This transient
buffer is highly configurable and I add some options for running regression tests (both [[https://pytest-regtest.readthedocs.io/en/latest/][pytest-regtest]] and [[https://syrupy-project.github.io/syrupy/][syrupy]] as
well as profiling).

#+NAME: code-pytest
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package python-pytest
  :after (pyvenv)
  :ensure t
  :config
  (transient-append-suffix
    'python-pytest-dispatch
    '(0)
    ["Regression Tests"
     ("-r" "Reset regression tests" "--regtest-reset")
     ("--su" "Reset Syrupy snapshot" "--snapshot-update")
     ("--tee" "Print results" "--regtest-tee")
     ("--nodiff" "Suppress output" "--regtest-nodiff")
     ("--endings" "Do not strip whitespaces at end of recorded lines" "--regtest-consider-line-endings")])
  (transient-append-suffix
    'python-pytest-dispatch
    '(0)
    ["Profiling"
     ("-P" "Generate profiling information" "--profile")
     ("--profile-svg" "Generate profiling graph" "--profile-svg")
     ("--pstats-dir" "Configure the dump directory of profile data files" "--pstats-dir")
     ("--element-number" "Defines how many elements will display in a result" "--element-number")
     ("--strip-dirs" "Configure to show/hide the leading path information from file names" "--strip-dirs")])
  )
#+END_SRC

***** Ruff
<<sec:ruff>>

[[https://docs.astral.sh/ruff][Ruff]] is a fast Python linter that is subsuming Black, Flake8, Yapf and Pylint.

+ [[https://github.com/scop/emacs-ruff-format][emacs-ruff-format]]
+ [[https://github.com/christophermadsen/emacs-lazy-ruff][emacs-lazy-ruff]]
+ [[https://github.com/erickgnavar/flymake-ruff][flymake-ruff]]

#+NAME: code-ruff
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ruff-format
  :ensure t
  :after (python-mode)
  :hook (python-mode . ruff-format-on-save-mode))

(use-package lazy-ruff
  :ensure t
  :after (python-mode)
  :bind (("C-c p l" . lazy-ruff-lint-format-dwim)) ;; keybinding
  :config
  (lazy-ruff-mode-global-toggle t)) ;; Enable the lazy-ruff minor mode globally

(use-package flymake-ruff
  :ensure t
  :after (python-mode)
  ;; :hook (python-mode . flymake-ruff-load))
  :hook (lsp-managed-mode . flymake-ruff-load))

#+END_SRC

***** Yapf
<<sec:yapf>>

[[https://github.com/JorisE/yapfify][Yapfify]] can be used to apply Googles [[https://github.com/google/yapf][yapf]] formatting. I don't use this so the following section is not tangled to my
config but is included on the off-chance I change my mind or someone else finds it useful.

#+NAME: code-yapf
#+BEGIN_SRC emacs-lisp :tangle no
(use-package yapfify
  :ensure t
  :defer t
  :after (python-mode)
  :hook (python-mode . yapf-mode))

#+END_SRC

**** Virtual Environments

I use two packages to manage virtual environments in conjunction with [[sec:envdir][~envdir~]]. For general Python virtual environments
I use [[https://github.com/jorgenschaefer/pyvenv][pyvenv]] which allows me to define on a per-host basis the location of virtual environments which are defined
globally, typically I use ~~/.virtualenvs~ which I will activate via a project/repository specific ~.envrc~ file which
[[sec:envdir][envdir]] takes care of activating when I switch to the project directory. Recently I've started using [[https://docs.astral.sh/uv/][uv]] to manage
packages and projects and so have also added [[https://github.com/z80dev/uv-mode][uv-mode]] to my configuration to take care of activating project specific
virtual environments which reside in the ~.venv~ directory created by ~uv~ within the project directory itself.

#+NAME: code-python-pyvenv
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package pyvenv
  :ensure t
  :defer 1
  :config
  ;; Setting work on to easily switch between environments
  (setenv "WORKON_HOME" (expand-file-name "~/.virtualenvs/"))
  (pyvenv-mode 1)
  ;; Display virtual envs in the menu bar
  (setq pyvenv-menu t
	venv-byhost
	'(("kimura" . "~/.virtualenvs/")
	  ("fisher" . "~/.virtualenvs/")
	  ("haldane" . "~/.virtualenvs/")
	  ("ovh" . "~/.virtualenvs/")
	  ("alarmpi" . "~/.virtualenvs/")
	  ("alarmpi-4b" . "~/.virtualenvs/"))
	venv-location (cdr
		       (assoc system-name venv-byhost))
	default-venv-byhost
	'(("kimura" . "~/.virtualenvs/default")
	  ("fisher" . "~/.virtualenvs/python3_9")
	  ("haldane" . "~/.virtualenvs/default")
	  ("ovh" . "~/.virtualenvs/default")
	  ("alarmpi" . "~/.virtualenvs/default")
	  ("alarmpi-4b" . "~/.virtualenvs/default"))
	default-venv (cdr
		      (assoc system-name default-venv-byhost))
	python-environment-directory venv-location)
  ;; Restart the python process when switching environments
  (add-hook 'pyvenv-post-activate-hooks (lambda ()
					  (pyvenv-restart-python)))
  :hook (python-mode . pyvenv-mode)
  (after-init-hook . (pyvenv-workon default-env))
  )

(use-package pyvenv-auto
  :ensure t
  :hook ((python-mode . pyvenv-auto-run)))

#+END_SRC

#+NAME: code-python-uv-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package uv-mode
  :ensure t
  :hook (python-mode . uv-mode-auto-activate-hook))

#+END_SRC

**** Additional packages

***** Blacken
<<sec:blacken>>

[[https://black.readthedocs.io/en/stable/][Black]] is "/the uncompromising code formatter/" and Emacs has the [[https://github.com/pythonic-emacs/blacken][blacken]] package which allows applying Black formatting
to a buffer via keybinding (see above configuration option under [[sec:python][Python]]) or automatically on saving.

#+NAME: code-blacken
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package blacken
  :ensure t
  :after (python-mode)
  :custom
  (blacken-line-length 120)
  :hook (python-mode . blacken-mode))
#+END_SRC

***** Pylint
<<sec:pylint>>

There is an orphaned [[https://github.com/emacsorphanage/pylint][pylint]] package which is referenced for completeness. Typically I defer running [[https://pylint.org][Pylint]] to a
[[https://pre-commit.com][Pre-commit]] hook.

#+NAME: code-pylint
#+BEGIN_SRC emacs-lisp :tangle no

  (use-package pylint
  :hook (python-mode . pylint-add-menu)
  (python-mode . add-key-bindings))

#+END_SRC

***** Pytest
<<sec:pytest>>

[[https://pytest.org][Pytest]] is well supported via [[https://github.com/wbolster/emacs-python-pytest][emacs-python-pytest]]. I've bound ~python-pytest-dispatch~ to ~C-c p t~ which brings up a
transient buffer with options for running ~pytest~ on a given file or function at the cursor location. This transient
buffer is highly configurable and I add some options for running regression tests (both [[https://pytest-regtest.readthedocs.io/en/latest/][pytest-regtest]] and [[https://syrupy-project.github.io/syrupy/][syrupy]]
although I'm tending towards the later these days).

#+NAME: code-pytest
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package python-pytest
  :after (pyvenv)
  :ensure t
  :config
  (transient-append-suffix
    'python-pytest-dispatch
    '(0)
    ["Regression Tests"
     ("-r" "Reset regression tests" "--regtest-reset")
     ("--su" "Reset Syrupy snapshot" "--snapshot-update")
     ("--tee" "Print results" "--regtest-tee")
     ("--nodiff" "Suppress output" "--regtest-nodiff")
     ("--endings" "Do not strip whitespaces at end of recorded lines" "--regtest-consider-line-endings")])
  (transient-append-suffix
    'python-pytest-dispatch
    '(0)
    ["Profiling"
     ("-P" "Generate profiling information" "--profile")
     ("--profile-svg" "Generate profiling graph" "--profile-svg")
     ("--pstats-dir" "Configure the dump directory of profile data files" "--pstats-dir")
     ("--element-number" "Defines how many elements will display in a result" "--element-number")
     ("--strip-dirs" "Configure to show/hide the leading path information from file names" "--strip-dirs")])
  )
#+END_SRC

***** Ruff
<<sec:ruff>>

[[https://docs.astral.sh/ruff][Ruff]] is a fast Python linter that is subsuming Black, Flake8, Yapf and Pylint.

+ [[https://github.com/scop/emacs-ruff-format][emacs-ruff-format]]
+ [[https://github.com/christophermadsen/emacs-lazy-ruff][emacs-lazy-ruff]]
+ [[https://github.com/erickgnavar/flymake-ruff][flymake-ruff]]

#+NAME: code-ruff
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ruff-format
  :ensure t
  :after (python-mode)
  :hook (python-mode . ruff-format-on-save-mode))

(use-package lazy-ruff
  :ensure t
  :after (python-mode)
  :bind (("C-c p l" . lazy-ruff-lint-format-dwim)) ;; keybinding
  :config
  (lazy-ruff-mode-global-toggle t)) ;; Enable the lazy-ruff minor mode globally

(use-package flymake-ruff
  :ensure t
  :after (python-mode)
  ;; :hook (python-mode . flymake-ruff-load))
  :hook (lsp-managed-mode . flymake-ruff-load))

#+END_SRC

*** ESS Mode
<<sec:ess>>

#+NAME: code-ess
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ess
  :ensure t
  ;;     :requires ess-r-mode
  ;;     ess-r-package
  :init
  :mode (("/R/.*\\.q\\'"       . R-mode)
	 ("\\.[rR]\\'"         . R-mode)
	 ("\\.[rR]profile\\'"  . R-mode)
	 ("NAMESPACE\\'"       . R-mode)
	 ("CITATION\\'"        . R-mode)
	 ("\\.[Rr]out"         . R-transcript-mode)
	 ("\\.Rmd\\'"          . Rd-mode)
	 ("\\.Rd\\'"           . Rd-mode))
  :interpreter (("R" . R-mode)
		("R" . R-transcript-mode)
		("R" . Rd-mode))
  :config
  (require 'ess-r-mode)
  (require 'ess-r-package)
  (setq ess-r-backend 'lsp)
  (setq comint-input-ring-size 1000)
  (setq ess-indent-offset 2)
  (setq ess-eval-visibly-p nil)
  (setq ess-startup-directory nil)
  (setq ess-ask-for-ess-directory nil)
  (setq ess-togggle-underscore nil)
  (setq ess-eval-visibly 'nowait)
  (setq ess-use-tracebug nil)
  :hook
  (ess-mode . company-mode)
  (inferior-ess-mode . company-mode)
  :bind
  (:map ess-r-mode-map
	("_" . 'ess-insert-assign)  ;;
	("C-q" . 'ess-eval-region-or-line-and-step)
	("C-|" . " |>\n"))
  (:map inferior-ess-r-mode-map
	("_" . 'ess-insert-assign)
	("C-|" . " |>\n")))

#+END_SRC

**** ess-smart-underscore
<<sec:ess-smart-underscore>>

#+NAME: code-ess-smart-underscore
#+BEGIN_SRC emacs-lisp :tangle yes
;;; http://github.com/mlf176f2/ess-smart-underscore.el
(use-package ess-smart-underscore
  :ensure t
  :after (ess))

#+END_SRC

**** ess-gd
<<sec:ess-gd>>

#+NAME: code-ess-gd
#+BEGIN_SRC emacs-lisp :tangle yes
;; https://github.com/sje30/essgd
(use-package essgd
  :ensure t)

#+END_SRC

**** quarto-mode
<<sec:quarto-mode>>

#+NAME: code-quarto-mode
#+BEGIN_SRC emacs-lisp :tangle yes
;; Quarto mode https://github.com/quarto-dev/quarto-emacs
;; By default associated with .qmd files
;; (use-package quarto-mode
;;   :ensure t
;;   :mode (("\\.Rmd" . poly-quarto-mode))
;;   :bind (("C-c q" . quarto-preview)))
;; Following requires that polymode, markdown and python are all loaded/configured first
(load "~/.config/emacs/site-lisp/quarto-mode.el")

#+END_SRC

**** r-autoyas
<<sec:r-autoyas>>

[[https://github.com/mattfidler/r-autoyas.el][r-autoyas]] is something I appear to have used at some point in the past but I've noted I disabled it in 2023-01-28 along
with a link to [[https://github.com/emacs-ess/ESS/issues/967#issuecomment-541276597][this issue]]. For now it is /not/ included when tangling my configuration.

#+NAME: code-r-autoyas
#+BEGIN_SRC emacs-lisp :tangle no
(use-package r-autoyas
  :ensure t
  :hook
  (ess-mode . r-autoyas-ess-activate))

#+END_SRC

*** JS Mode
<<sec:js>>

I (thankfully) don't write much JavaScript but add the file extensions below to the appropriate modes.

#+NAME: code-js
#+BEGIN_SRC emacs-lisp :tangle yes
(add-to-list 'auto-mode-alist '("\\.js" . js-mode))
(add-to-list 'auto-mode-alist '("\\.json" . json-mode))
(add-to-list 'auto-mode-alist '("\\.svelte" . js-ts-mode))
#+END_SRC

*** Just Mode
<<sec:just>>

[[https://github.com/leon-barrett/just-mode.el][just-mode]] is for editing [[https://just.systems/man/en/][just]] files.

#+NAME: code-just
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package just-mode
  :ensure t
  :defer 0.5)

#+END_SRC

*** Latex Mode
<<sec:latex>>

#+NAME: code-latex
#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC

*** Markdown Mode
<<sec:markdown>>

[[https://github.com/jrblevin/markdown-mode][markdown-mode]] is for editing Markdown files.

#+NAME: code-markdown
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package markdown-mode
  :ensure t
  :mode ("\\.md\\'" . gfm-mode)
  :hook (markdown-mode . auto-fill-mode)
  :init (setq markdown-command "pandoc")
  :config
  :bind (:map markdown-mode-map
              ("C-c C-m" . markdown-do)))

#+END_SRC

**** markdown-ts-mode
<<sec:markdown-ts-mode>>

[[https://github.com/LionyxML/markdown-ts-mode][markdown-ts-mode]] provides [[sec:treesitter][Tree Sitter]] support for ~.md~ files.

The following /isn't/ tangled and needs checking
#+NAME: code-markdown-ts-mode
#+BEGIN_SRC emacs-lisp :tangle no
(use-package markdown-ts-mode
  :ensure t
  :after (markdown-mode)
  :mode ("\\.md\\'" . markdown-ts-mode)
  :custom
  (add-to-list 'treesit-language-source-alist '(markdown "https://github.com/ikatyang/tree-sitter-markdown" "master"
"src")))

#+END_SRC

*** Mermaid Mode
<<sec:mermaid>>

[[https://github.com/abrochard/mermaid-mode/][mermaid-mode]] provides support for [[https://mermaid.js.org/][Mermaid.js]] a code-based, declarative diagramming system.

#+NAME: code-mermaid
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package mermaid-mode
  :ensure t
  :defer 10)

#+END_SRC

**** ob-mermaid
<<sec:ob-mermaid>>

[[https://github.com/arnm/ob-mermaid][ob-mermaid]] provides org-babel exporting of mermaid diagrams using [[https://github.com/mermaid-js/mermaid-cli][mermaid-cli]].

#+NAME: code-ob-mermaid
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ob-mermaid
  :ensure t
  :after (mermaid-mode))

#+END_SRC

**** mermaid-ts-mode
<<sec:mermaid-ts-mode>>

[[https://github.com/JonathanHope/mermaid-ts-mode][mermaid-ts-mode]] provides [[sec:treesitter][Tree Sitter]] support for Mermaid.

#+NAME: code-mermaid-ts-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package mermaid-ts-mode
  :ensure t
  :after (mermaid-mode))

#+END_SRC

*** Nix Mode
<<sec:nix>>

I dabbled with [[https://nixos.org/][NixOS]] in the past and used these packages to help with writing nix packages and code.

**** nixfmt
<<sec:nixfmt>>

[[https://github.com/purcell/emacs-nixfmt][nixfmt]]

#+NAME: code-nixfmt
#+BEGIN_SRC emacs-lisp :tangle no
(use-package nixfmt
  :ensure t
  :defer 3
)

#+END_SRC

**** nix-ts-mode
<<sec:nix-ts-mode>>

[[https://github.com/nix-community/nix-ts-mode][nix-ts-mode]] provides [[sec:treesitter][Tree Sitter]] support for ~.nix~ files.

#+NAME: code-nix-ts-mode
#+BEGIN_SRC emacs-lisp :tangle no

(use-package nix-ts-mode
  :ensure t
  :mode "\\.nix\\'")

#+END_SRC

**** agenix
<<sec:agenix>>

[[https://github.com/t4ccer/agenix.el][agenix]] is for working with secrets.

#+NAME: code-agenix
#+BEGIN_SRC emacs-lisp :tangle no
(use-package agenix
  :ensure t
  :mode "\\.age\\'")

#+END_SRC

*** Rust Mode
<<sec:rust>>

Rust is something I intend to learn at some point (right after I've learnt Elisp!). The various packages here integrate
with [[sec:lsp-mode][lsp-mode]].

**** rust-mode
<<sec:rust-mode>>

[[https://github.com/rust-lang/rust-mode][rust-mode]] for editing [[https://rust-lang.org/][Rust]] source files (~.rs~).

#+NAME: code-rust
#+BEGIN_SRC emacs-lisp :tangle no
;; https://github.com/rust-lang/rust-mode
(use-package rust-mode
  :ensure t
  :defer 0.5
  :custom
  (add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-mode))
  (rust-mode-treesitter-derive t)
  ;; :hook
  ;; (rust-mode . (lambda () (prettify-symbols-mode)))
  )

#+END_SRC

**** rustic
<<sec:rustic>>

[[https://github.com/emacs-rustic/rustic][rustic]] is based on [[sec:rust-mode][rust-mode]] and provides additional features such as automatic LSP configuration, [[sec:cargo][Cargo]] popups, async
with [[sec:org-babel][Org Babel]] and more.

#+NAME: code-rustic
#+BEGIN_SRC emacs-lisp :tangle no
(use-package rustic
  :ensure t
  :defer 3
  :custom
  (rustic-format-on-save t)
  (rustic-cargo-use-last-stored-arguments t))
#+END_SRC

**** Cargo
<<sec:cargo>>

 [[https://doc.rust-lang.org/cargo/][Cargo]] is the Rust package manager.

***** cargo.el
<<sec:cargo-el>>

[[https://github.com/kwrooijen/cargo.el][cargo.el]] is in maintenance mode but provides a set of key combinations to perform various tasks.
#+NAME: code-cargo-el
#+BEGIN_SRC emacs-lisp :tangle no
body
#+END_SRC

***** cargo-mode
<<sec:cargo-mode>>

[[https://github.com/ayrat555/cargo-mode][cargo-mode]] is a minor mode for dynamically selecting commands from the Rust package manager.

#+NAME: code-cargo-mode
#+BEGIN_SRC emacs-lisp :tangle no
;; https://github.com/ayrat555/cargo-mode
(use-package cargo-mode
  :ensure t
  :defer 0.5
  :hook
  (rust-mode . cargo-minor-mode)
  :config
  (setq compulation-scroll-output t))

#+END_SRC

*** Sqlite Mode
<<sec:sqlite>>

Emacs can be compiled with [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Database.html][built-in support for SQLite databases]]. I have picked up one [[https://christiantietze.de/posts/2024/01/emacs-sqlite-mode-open-sqlite-files-automatically/][custom function]] along the way.

#+NAME: code-sqlite
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package sqlite-mode
  :custom
  (defun ns/sqlite-view-file-magically ()
    "Runs `sqlite-mode-open-file' on the file name visited by the
current buffer, killing it."
    (require 'sqlite-mode)
    (let ((file-name buffer-file-name))
      (kill-current-buffer)
      (sqlite-mode-open-file file-name)))
    (add-to-list 'magic-mode-alist '("SQLite format 3\x00" . ns/sqlite-view-file-magically)))

#+END_SRC

**** sqlite-mode-extras
<<sec:sqlite-mode-extras>>

[[https://github.com/xenodium/sqlite-mode-extras][sqlite-mode-extras]] provides a suite of extra functions which extend the built-in.

#+NAME: code-sqlite-mode-extras
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package sqlite-mode-extras
  :bind (:map
          sqlite-mode-map
          ("n" . next-line)
          ("p" . previous-line)
          ("b" . sqlite-mode-extras-backtab-dwim)
          ("f" . sqlite-mode-extras-tab-dwim)
          ("+" . sqlite-mode-extras-add-row)
          ("D" . sqlite-mode-extras-delete-row-dwim)
          ("C" . sqlite-mode-extras-compose-and-execute)
          ("E" . sqlite-mode-extras-execute)
          ("S" . sqlite-mode-extras-execute-and-display-select-query)
          ("DEL" . sqlite-mode-extras-delete-row-dwim)
          ("g" . sqlite-mode-extras-refresh)
          ("<backtab>" . sqlite-mode-extras-backtab-dwim)
          ("<tab>" . sqlite-mode-extras-tab-dwim)
          ("RET" . sqlite-mode-extras-ret-dwim)))

#+END_SRC

*** Yaml Mode
<<sec:yaml>>

[[https://github.com/yoshiki/yaml-mode][yaml-mode]] is a bit dated but works ok. I think a lot of the functionality I get when working with YAML files comes from
the LSP protocol but I retain this in my configuration for now.

#+NAME: code-yaml
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package yaml-mode
  :init
  (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode))
  (add-to-list 'auto-mode-alist '("\\.cff\\'" . yaml-mode)))
#+END_SRC

*** Polymode Mode
<<sec:polymode>>

#+NAME: code-polymode
#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC

** LSP Mode
<<sec:lsp-mode>>

Whilst Eglot is built-in to Emacs since v30-ish I started using [[https://emacs-lsp.github.io/lsp-mode/][LSP Mode]] before this and have for now stuck with it.

** Projectile
<<sec:projectile>>

[[https://github.com/bbatsov/projectile/][projectile]] ([[https://docs.projectile.mx/][docs]]) is a neat package for managing and navigating projects.

#+NAME: code-projectile
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package projectile
  :ensure t
  :bind
  (:map projectile-mode-map
        ("s-p" . projectile-command-map))
  :custom
  (projectile-project-search-path '("~/org/" "~/org-roam" "~/.config/emacs" ("~/work/git/" . 3)))
  (projectile-enable-caching t)
  (projectile-switch-project-action #'projectile-commander)
  :init
  (projectile-mode +1))

#+END_SRC

*** consult-projectile
<<sec:consult-projectile>>

[[https://gitlab.com/OlMon/consult-projectile][consult-projectile]] incorporates [[sec:projectile][projectile]] into [[sec:consult][consult]].

#+NAME: code-consult-projectile
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package consult-projectile
  :ensure t
  :after projectile)

#+END_SRC

** Tree Sitter
<<sec:TreeSitter>>

[[https://tree-sitter.github.io/tree-sitter/][Tree-sitter]] is a "magic" tool that performs incremental parsing to build concrete syntax trees as files are edited.

+ [[https://emacs-tree-sitter.github.io/][emacs-tree-sitter]] - mostly obsolete since it [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Language-Grammar.html][treesit.el]] is built-in now.
+ [[https://archive.casouri.cc/note/2023/tree-sitter-in-emacs-29/index.html][Tree-sitter in Emacs 29]]
+ [[https://takeonrules.com/2023/03/08/coloring-regular-expression-via-modus-themes-for-treesit-faces/][Coloring regular expression via modus themes for treesit faces]]
+ [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][Mastering Emacs - How to get Started with Tree-sitter]]

*** treesit
<<sec:treesit>>

[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Language-Grammar.html][treesit.el]] is built-in to Emacs since 29.1, older versions required [[https://github.com/emacs-tree-sitter/elisp-tree-sitter][tree-sitter.el]].

#+NAME: code-tree-sitter
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package tree-sitter
  :ensure t
  :init
  (global-tree-sitter-mode))

#+END_SRC

*** treesit-fold
<<sec:tree-sitter-fold>>

[[https://github.com/emacs-tree-sitter/treesit-fold][treesit-fold]] provides tree-folding for the built-in

#+NAME: code-tree-sitter-fold
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package treesit-fold
  :ensure t
  :init
  (global-treesit-fold-mode))

#+END_SRC

*** tree-sitter-ispell
<<sec:tree-sitter-ispell>>

[[https://github.com/erickgnavar/tree-sitter-ispell.el][tree-sitter-ispell]]

#+NAME: code-tree-sitter-ispell
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package tree0sitter-spell
  :ensure t
  :defer 0.5
  :after (tree-sitter))
#+END_SRC

*** treesit-auto
<<sec:treesit-auto>>

[[https://github.com/renzmann/treesit-auto][treesit-auto]]

*LEGACY* - Not tangled
#+NAME: code-treesit-auto
#+BEGIN_SRC emacs-lisp :tangle no

(use-package treesit-auto
  :ensure t
  :config
  (treesit-auto-apply-remap))
#+END_SRC

** YASnippet
<<sec:yasnippet>>

[[https://joaotavora.github.io/yasnippet/][YASnippet]] (Yet another snippet extension) is a brilliant templating system that allows you to define code-chunks that
are inserted with a few keystrokes, and then prompting you for specific fields, saving you considerable time in writing
boiler-plate code. We enable the templates via hooks for ~prog-mode~, ~org-mode~ and ~r-mode~ and load a bunch of
pre-defined snippets from the [[https://github.com/AndreaCrotti/yasnippet-snippets][yasnippet-snippets]] package.

#+NAME: code-yasnippet
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package yasnippet
  :ensure t
  :config
  (yas-reload-all)
  (add-hook 'prog-mode-hook #'yas-minor-mode)
  (add-hook 'org-mode-hook #'yas-minor-mode)
  (add-hook 'ess-r-mode-hook #'yas-minor-mode))
#+END_SRC

#+NAME: code-yasnippet
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package yasnippet-snippets
  :ensure t)

#+END_SRC

The snippets I have written/customised are not included here. They are loaded from the ~snippet/~ directory. If you are
interested in my snippets see the [[https://codeberg.org/slackline/emacs/src/branch/master/snippets][snippets]] in my configuration repository.

** direnv
<<sec:direnv>>

[[https://direnv.net/][direnv]] allows easy activation of virtual environment, setting custom variables or running other actions conditional on
entering a directory. Naturally there is [[https://github.com/wbolster/emacs-direnv][emacs-direnv]] which provides integration with Emacs. Pretty much always want
this available so sticking with `:config` to ensure the package is always loaded.

#+NAME: code-direnv
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package direnv
  :ensure t
  :config
  (direnv-mode))
#+END_SRC

* Dired
<<sec:dired>>

I like the [[https://github.com/alexluigit/dirvish][dirvish]] package for extending the basic [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][built-in Dired]].

Some useful resources on ~dired~ can also be found in

+ [[https://pragmaticemacs.wordpress.com/category/dired/][dired | Pragmatic Emacs]]
+ [[https://www.masteringemacs.org/article/working-multiple-files-dired][Working with multiple files in dired - Mastering Emacs]]
+ [[https://github.com/Fuco1/dired-hacks][Fuco1/dired-hacks: Collection of useful dired additions]]

#+NAME: code-dirvish
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package dirvish
  :ensure t
  :init
  (dirvish-override-dired-mode)
  :config
  (setq dirvish-attributes
	'(vc-state subtree-state all-the-icons collapse git-msg file-time file-size))
  ;; Placement
  ;; (setq dirvish-use-header-line nil)     ; hide header line (show the classic dired header)
  ;; (setq dirvish-use-mode-line nil)       ; hide mode line
  (setq dirvish-use-header-line 'global)    ; make header line span all panes

  ;; Hide the parent directory
  (setq dirvish-default-layout '(0 0.4 0.6))
  ;; Height
  ;;; '(25 . 35) means
  ;;;   - height in single window sessions is 25
  ;;;   - height in full-frame sessions is 35
  (setq dirvish-header-line-height '(25 . 35))
  (setq dirvish-mode-line-height 25) ; shorthand for '(25 . 25)

  ;; Segments
  ;;; 1. the order of segments *matters* here
  ;;; 2. it's ok to place raw string inside
  (setq dirvish-header-line-format
	'(:left (path) :right (free-space))
	dirvish-mode-line-format
	'(:left (sort file-time " " file-size symlink) :right (omit yank index))))
#+END_SRC

** All the Icons
<<sec:all-the-icons>>

To make Dired/Dirvish look nice we also need icons.

#+NAME: code-all-the-icons
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package all-the-icons
  :ensure t
  :after dirvish)

(use-package all-the-icons-dired
  :ensure t
  :after all-the-icons)

(use-package all-the-icons-ibuffer
  :ensure t
  :after all-the-icons)
#+END_SRC

** Dired Extensions
<<sec::dired-extensions>>

There are a bunch of useful extensions to ~dired~ and [[https://github.com/Fuco1/dired-hacks][Fuco1/dired-hacks: Collection of useful dired additions]] has most
of them listed. I currently use the following

+ dired-quick-sort
+ [[https://github.com/stsquad/dired-rsync][dired-rsync]] (also the source for ~dired-rsync-transient~)
+ [[https://codeberg.org/danrobi/dired-multi-copy][dired-multi-copy]] (installed via ~:vc~ option to ~use-package~ as not yet on [[https://melpa.org/][MELPA]])
+ [[https://github.com/punassuming/ranger.el][dired-ranger]]
+ dired-subtree

#+NAME: code-dired-extensions
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package dired-quick-sort
  :ensure t
  :defer 0.5
  :after dirvish
  :config
  (dired-quick-sort-setup))

;;
(use-package dired-rsync
  :ensure t
  :defer 0.5
  :after dirvish)

(use-package dired-rsync-transient
  :ensure t
  :defer 0.5
  :after dirvish)

;; https://codeberg.org/danrobi/dired-multi-copy (not on MELPA yet)
;; (use-package dired-multi-copy
;;   :ensure t)

;; https://github.com/punassuming/ranger.el
(use-package dired-ranger
  :ensure t
  :defer 0.5
  :bind (:map dired-mode-map
              ("W" . dired-ranger-copy)
              ("X" . dired-ranger-move)
              ("Y" . dired-ranger-paste)))


(use-package dired-subtree
  :ensure t
  :config
  (bind-keys :map dired-mode-map
             ("i" . dired-subtree-insert)
             (";" . dired-subtree-remove)))
#+END_SRC

* TRAMP
<<sec:tramp>>

[[TRAMP]] (Transparent Remote (file) Access, Multiple Protocol) "/ provides an easy, convenient, and consistent interface to
editing remote files transparently, just as if they are local files. This extends to editing, version control, dired,
and more./". The "more" part includes files under ~su~ both locally and remotely. It is one of the amazing packages in
Emacs that makes people's lives considerably easier. I don't use it nearly enough, the first time I tried it out I had
major issues which were down to the prompts on the remote machine. Took a while to find a [[https://emacs.stackexchange.com/questions/47969/trouble-connecting-gnu-emacs-to-work-machine-through-ssh-tramp][thread]] with a simple way to
disable the ~PS1~ prompt [[https://emacs.stackexchange.com/a/48089][if ~$TERM == "dumb"~]].

+ [[https://coredumped.dev/2025/06/18/making-tramp-go-brrrr./][Making TRAMP go Brrrr...]] is a useful article on speeding things up which is where most of my customisations came from
  (not implemented them all yet though!)

#+NAME: code-tramp
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package tramp
  :ensure t
  :custom
  (tramp-default-method "ssh")
  (add-to-list 'tramp-default-method-alist '("" "neil" "ssh"))
  ;; Set prompt so it doesn't hang
  (shell-prompt-pattern '"^[^#$%>\n]*~?[#$%>] *")
  (tramp-auto-save-directory "~/.config/emacs/tmp/")
  (remote-file-name-inhibit-locks t)
  (tramp-use-scp-direct-remote-copying t)
  (remote-file-name-inhibit-auto-save-visited t)
  (tramp-copy-size-limit (* 1024 1024)) ;; 1Mb
  ;; Set default usernames for different hosts and a global default.
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*ovh'" "arch") t)
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*openwrt" "admin") t)
  (add-to-list 'tramp-default-user-alist
	       '(nil nil "neil") t)
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*alarmpi-4b" "neil") t)
  (add-to-list 'tramp-default-user-alist
	       '("ssh" ".*crow'" "neil") t))

#+END_SRC

* Terminals
<<sec:terminals>>

I don't use the shell/terminal in Emacs much as I quite like having clear separate usage and so use [[https://sw.kovidgoyal.net/kitty/][kitty]].
** vterm
<<sec:vterm>>

[[https://github.com/akermu/emacs-libvterm][vterm]] is a compiled terminal emulator, as such you need to have something like ~gcc~ installed (common on most GNU/Linux
systems, less so on M$-Win/OSX).

#+NAME: code-vterm
#+BEGIN_SRC emacs-lisp :tangle yes
;;
(use-package vterm
  :ensure t
  :defer 3
  :custom
  (vterm-always-compile-module t)
  (vterm-copy-exclude-prompt t)
  (vterm-kill-buffer-on-exit t))

#+END_SRC


** eat
<<sec:eat>>

[[https://codeberg.org/akib/emacs-eat/][eat]] is another terminal emulator that I may investigate in the future if I ever tire of using [[https://sw.kovidgoyal.net/kitty/][kitty]].

#+NAME: code-eat
#+BEGIN_SRC emacs-lisp :tangle no
(use-package eat
  :ensure t)

#+END_SRC

* Miscellaneous
<<sec:misc>>

** mpd

I use [[https://musicpd.org/][Music Player Daemon]] to run my music, these packages allow me to control ~mpd~ from Emacs.

*** mpdel
<<sec:mpdel>>

[[https://gitea.petton.fr/mpdel/mpdel][mpdel]] provides an interface to ~mpd~ its not working perfectly yet, for example I use a password and I can't see anyway
of configur f

#+NAME: code-mpdel
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package mpdel
  :ensure t
  :custom
  (libmpdel-hostname "192.168.1.28")
  (libmpdel-port 6600))
;; (mpdel-mode)

#+END_SRC

*** ivy-mpdel
<<sec:ivy-mpdel>>

[[https://github.com/mpdel/ivy-mpdel][ivy-mpdel]] provides an Emacs' ivy interface to communicate with ~mpd~.

#+NAME: code-ivy-mpdel
#+BEGIN_SRC emacs-lisp :tangle no
(use-package ivy-mpdel
  :ensure t
  :defer 2)

#+END_SRC

*** mpdmacs
<<sec:mpdmacs>>

[[https://github.com/sp1ff/mpdmacs][mpdmacs]] is another client that I'm yet to investigate/get working.

#+NAME: code-mpdmacs
#+BEGIN_SRC emacs-lisp :tangle no
(use-package mpdmacs
  :ensure t
  :defer 2
  :custom
  (mpdmacs-host "192.168.1.28")
  (mpdmacs-port 6600)
  :bind
  ("C-c m" . 'mpdmacs-mode-keymap)
  :hook (mpdmacs-mode-hook . mpdmacs-mode-keymap))


#+END_SRC

** OSM
<<sec:osm>>

[[https://github.com/minad/osm][osm]] provides in Emacs [[https://openstreetmap.org][OpenStreetMap]] viewer. It includes the ability to add bookmarks and define
~geo:<lat>,<lon>;z=<zoom-int>~ org-links.

#+NAME: code-osm
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package osm
  :ensure t
  :defer 3
  :custom
  (osm-server 'default)
  (osm-home '(53.356116 -1.463397 15))
  :bind
  (("C-c o" . osm-prefix-map)))

#+END_SRC

** Pass
<<sec:pass>>

[[https://github.com/NicolasPetton/pass][pass]] provides access to [[https://www.passwordstore.org/][pass the standard unix password manager]]. I always want this available so I just ~:ensure
t~. Invoking ~pass~ brings up a transient-like menu and list of passwords that are stored on the system providing easy
and intuitive access to accessing and managing stored passwords.

Currently not included in config in favour of [[sec:password-store-menu][password-store-menu]]
#+NAME: code-pass
#+BEGIN_SRC emacs-lisp :tangle no
(use-package pass
  :ensure t)

#+END_SRC

*** password-store-menu
<<sec:password-store-menu>>

[[https://github.com/rjekker/password-store-menu][password-store-menu]] adds a transient menu to ~password-store.el~ which is part of  [[https://www.passwordstore.org/][pass the standard unix password
manager]]. Invoking ~password-store-menu~ brings up the transient menu from where you can navigate the actions you wish to
take. I prefer this over [[sec:pass][pass]].

#+NAME: code-password-store-menu
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package password-store-menu
  :ensure t
  :config (password-store-menu-enable)
  :custom (password-store-menu-key "C-c C-p"))

#+END_SRC

*** password-store-otp
<<sec:password-store-otp>>

[[https://github.com/volrath/password-store-otp.el][password-store-otp]] provides access to the [[https://github.com/tadfisher/pass-otp][pass-otp]] plugin from Emacs.

#+NAME: code-password-store-otp
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package password-store-otp
  :ensure t
  :after (password-store-menu))

#+END_SRC

** Scratch
<<sec:scratch>>

Scratch buffers are useful for testing code in playgrounds.

*** scratch.el
<<sec:scratch-el>>

[[https://codeberg.org/emacs-weirdware/scratch][scratch]] extends the basic ~*scratch*~ buffer and provides per-mode scratch buffers. These are opened using the bound
key. If you want a prompt for which buffer mode to invoke then use ~C-u M-x scratch~ and you'll be prompted.

#+NAME: code-scratch-el
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package scratch
  :ensure t
  :bind ("C-c s" . scratch))

#+END_SRC

*** scratch-plus
<<sec:scratch-plus>>

[[https://git.sr.ht/~swflint/scratch-plus][scratch-plus]] "/provides four major features: unkillable scratch buffers, persistent scratch buffers, per-major-mode
scratch buffers, and per-project scratch buffers./". Yet to work out if this is working as expected and how to enable
the per-major-mode scratch buffers.

#+NAME: code-scratch-plus
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package scratch-plus
  :ensure t
  :defer 0.5
  :hook
  (add-hook 'after-init-hook #'scratch-plus-mode)
  :custom
  (scratch-plus-save-directory "~/.config/emacs/scratch")
  (scratch-plus-project-subdir ".scratch")
  (scratch-plus-idle-save 3))
#+END_SRC

** tmr
<<sec:tmr>>


* User Interface

Elements concerned with the User Interface which typically means how buffers, mini-buffers, modeline look.

** Themes
<<sec:themes>>

*** modus-themes

[[https://protesilaos.com/modus-themes/][modus-themes]] from Prot are really nice.

#+NAME: code-modus-themes
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package modus-themes
  :ensure t
  :defer 0.5
  :custom
  ;; Add all your customisation's prior to loading the themes
  (modus-themes-italic-constructs t
	(message "message" format-args)odus-themes-bold-constructs t
    modus-themes-org-blocks '(tinted-background)
    modus-themes-include-derivatives-mode 1)
  :bind
  ("C-c C-t m" . modus-themes-toggle))
#+END_SRC

*** ef-themes
<<sec:ef-themes>>

[[https://protesilaos.com/emacs/ef-themes][ef-themes]] also from [[https://protesilaos.com/][Prot]] are also very nice and my current favourite.

#+NAME: code-ef-themes
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ef-themes
  :ensure t
  :defer 0.5
  :custom
  (ef-themes-disable-other-themes 'ef-themes-light-themes)
  (ef-themes-take-over-modus-themes-mode 0)
  :bind
  ("C-c C-t d" . ef-themes-select-dark)
  ("C-c C-t e" . ef-themes-toggle))
(load-theme 'ef-dark :no-confirm)

#+END_SRC

*** golden ratio
<<sec:golden-ratio>>

[[https://github.com/roman/golden-ratio.el][golden-ratio]]

#+NAME: code-golden-ratio
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package golden-ratio
  :ensure t
  :defer 0.5
  :custom
  (setq golden-ratio-auto-scale t))

#+END_SRC

*** Font

I use the [[https://github.com/source-foundry/Hack][Hack]] font in Emacs, it needs installing at the system level so it's available for Emacs.

#+NAME: code-font
#+BEGIN_SRC emacs-lisp :tangle yes
(set-face-attribute 'default t :font "Hack")
#+END_SRC

** Modeline
<<sec:modeline>>

*** mood-line
<<sec:moodline>>

[[https://git.tty.dog/hpet_dog/mood-line][mood-line]] is a minimalist configuration for the default [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Mode-Line.html][mode-line]], the bar at the bottom of a buffer showing information
about the buffer.

#+NAME: code-moodline
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package mood-line
  :ensure t
  :custom
  (mood-line-glyph-alist mood-line-glyphs-unicode)
  :config
  (mood-line-mode))

#+END_SRC

*** minions
<<sec:minions>>

[[https://github.com/tarsius/minions][minions]] is another neat little package from the author of [[sec:magit][Magit]] which adds a pop-up menu to the mode-line that shows the
minor modes that are enabled for the given buffer. Haven't quite got this working yet as I only see the major mode
listed and can't yet find where to click to get the menu but ~minions-minor-mode-menu~ can be called interactively to
access the same list.

#+NAME: code-minions
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package minions
  :ensure t)
#+END_SRC

*** Custom Modeline
<<sec:custom-modeline>>

Once tried implementing a [[https://protesilaos.com/codelog/2023-07-29-emacs-custom-modeline-tutorial/][custom modeline]] based on a tutorial by Prot.

Not currently tangled.

#+NAME: code-custom-modeline
#+BEGIN_SRC emacs-lisp :tangle no
Custom Modeline
(setq-default mode-line-format
  '("%e"
     prot-modeline-kbd-macro
     prot-modeline-narrow
     prot-modeline-input-method
     prot-modeline-buffer-status
     " "
     prot-modeline-buffer-identification
     "  "
     prot-modeline-major-mode
     prot-modeline-process
     "  "
     prot-modeline-vc-branch
     "  "
     prot-modeline-flymake
     "  "
     prot-modeline-align-right
     prot-modeline-misc-info))

#+END_SRC

** Buffers

Some customisations to make buffers nicer to work with/read.

*** highlight-indent-guides
<<sec:highlight-indent-guides>>

[[https://github.com/DarthFennec/highlight-indent-guides][highlight-indent-guides]] a minor mode that does what it says on the tin, vertical indent guides (lines between starting a
code block that is indented and ending it) are highlighted as you scroll.

#+NAME: code-highlight-indent-guides
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package highlight-indent-guides
  :ensure t
  :defer 1
  :custom
  (highlight-indent-guides-method 'bitmap)
  :hook
  (prog-mode . highlight-indent-guides-mode))

#+END_SRC

*** smartparens
<<sec:smartparens>>

[[https://github.com/Fuco1/smartparens][smartparens]] ensures parentheses (and quotes) are always paired. Handy as there are a lot of parentheses in Elisp! I
pretty much always want this enabled across multiple modes. There may be some redundancy here that can be removed!

#+NAME: code-smartparens
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package smartparens
  :ensure t
  :defer 1
  :custom
  (smartparens-global-mode t)
  :hook
  (prog-mode . smartparens-mode)
  (text-mode . smartparens-mode)
  (markdown-mode . smartparens-mode)
  (latex-mode . smartparents-mode)
  :config
  (progn
    (require 'smartparens-config)
    (smartparens-global-mode 1)
    (show-paren-mode t)))

#+END_SRC

*** rainbow-delimiters
<<sec:rainbow-delimiters>>

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] in conjunction with [[sec:smartparens][smartparens]] makes it easy to see which parentheses/brackets/braces pair up.

#+NAME: code-rainbow-delimiters
#+BEGIN_SRC emacs-lisp :tangle yes

(use-package rainbow-delimiters
  :ensure t
  :hook
  (prog-mode . rainbow-delimiters-mode))

#+END_SRC

*** rainbow-mode
<<sec:rainbow-mode>>

[[https://github.com/emacsmirror/rainbow-mode][rainbow-mode]] is a minor mode that colourises colour names, whether they are hexadecimal or otherwise.

#+NAME: code-rainbow-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package rainbow-mode
  :ensure t
  :defer 1
  :hook
  (prog-mode . rainbow-mode))

#+END_SRC

** Tabs
<<sec:tabs>>

*** Centaur Tabs
<<sec:centaur-tabs>>

[[https://github.com/ema2159/centaur-tabs][centaur tabs]] is a nice package for grouping buffers into tabs. I've a couple of custom functions that group them and
also hide certain buffers I don't need to see often.

+ [[https://themkat.net/2024/01/04/emacs_centaur_tabs.html][centaur-tabs-buffer-groups]]

#+NAME: code-centaur-tabs
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package centaur-tabs
  :ensure t
  :demand
  :config
  (centaur-tabs-mode t)
  (defun centaur-tabs-buffer-groups ()
    "Groups tabs based on which project root they are in if possible"
    (let ((get-closest-projectile-project
	   (lambda (path)
	     (let ((expanded-path (f-long path)))
	       (-first (lambda (proj)
			 (s-starts-with? proj
					 expanded-path))
		       (-map (lambda (proj)
			       (f-long proj))
			     projectile-known-projects))))))
      (list (cond
	     ;; Group as part of projectile project if directly part of it
	     ((condition-case _err
		  (projectile-project-root)
		(error nil))
	      (f-expand (projectile-project-root)))
	     ;; Try to group as part of projectile project if indirectly part of it (started from the same directory, not yet tracked, or maybe temporary buffer)
	     (get-closest-projectile-project default-directory)
	     ((string-equal "*" (substring (buffer-name) 0 1))
	      "proc-buffers")
	     ;; ... other groupings ...
	     (t
	       "Other")))))
  (defun centaur-tabs-hide-tab (x)
    "Do no to show buffer X in tabs."
    (let ((name (format "%s" x)))
      (or
        ;; Current window is not dedicated window.
        (window-dedicated-p (selected-window))
        ;; Buffer name not match below blacklist.
        (string-prefix-p "*epc" name)
        (string-prefix-p "*helm" name)
        (string-prefix-p "*Helm" name)
        (string-prefix-p "*Compile-Log*" name)
        (string-prefix-p "*lsp" name)
        (string-prefix-p "*company" name)
        (string-prefix-p "*Flycheck" name)
        (string-prefix-p "*tramp" name)
        (string-prefix-p " *Mini" name)
        (string-prefix-p "*help" name)
        (string-prefix-p "*straight" name)
        (string-prefix-p "*temp" name)
        (string-prefix-p "*Help" name)
        (string-prefix-p "*mybuf" name)
        ;; Is not magit buffer.
        (and (string-prefix-p "magit" name)
	  (not (file-name-extension name)))
        )))

  :custom
  (centaur-tabs-enable-key-bindings t)
  (centaur-tabs-style "wave")
  (centaur-tabs-set-icons t)
  (centaur-tabs-set-bar 'under)
  (x-underline-at-descent-line t)
  (centaur-tabs-cycle-scope 'default)
  (centaur-tabs-set-modified-marker t)
  (centaur-tabs-modified-marker "")
  :bind
  ;; ("C-c t C-<right>" . centaur-tabs-move-current-tab-to-right)
  ;; ("C-c t C-<left>" . centaur-tabs-move-current-tab-to-left)
  ("C-<prior>" . centaur-tabs-backward)
  ("C-<next>" . centaur-tabs-forward))


#+END_SRC


*** Keybindings
<<sec:keybindings>>

* Custom Functions
<<sec:custom_functions>>


I've come across a bunch of functions that others generously share and include them here.

** Reinstall Package

A handy way to [[https://emacsredux.com/blog/2020/09/12/reinstalling-emacs-packages/][reinstall a package]].

#+NAME: code-reinstall-package
#+BEGIN_SRC emacs-lisp :tangle yes
(defun ns/reinstall-package (pkg)
  (interactive (list (intern (completing-read "Reinstall package: " (mapcar #'car package-alist)))))
  (unload-feature pkg)
  (package-reinstall pkg)
  (require pkg))
#+END_SRC


* Footer
<<sec:footer>>

Library [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][conventions]] require a footer.

#+NAME: code-footer
#+begin_src emacs-lisp :tangle yes
  (provide 'init.el)
  ;;; init.el ends here
#+end_src

* On Literate Configuration

** Development

During development I created the Org file at ~~/.config/emacs/config.org~ and set the header to tangle to ~init.el~
within that directory so that I didn't clobber my existing ~init.el~.

#+NAME: example-tangle-header
#+BEGIN_SRC org-mode :tangle no
,#+TITLE: Literate Emacs Configuration
,#+PROPERTY: header-args : tangle init.el
,#+OPTIONS: toc:2 num:nil
,#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+END_SRC

** Different target files

When writing code blocks in Org-mode they have the structure shown below which allows the global ~:tangle~ target to be
over-ridden. Useful for writing the ~early-init.el~

#+NAME: example-tangle-alt-target-file
#+BEGIN_SRC org-mode :tangle no
,#+NAME
,#+BEGIN_SRC emacs-lisp :tangle <target_file>
(setq some-custom-setting 1)
,#+END_SRC
#+END_SRC

** Exclude block

If there is a particular code block I _don't_ want to tangle and include it is possible to disable it.

#+NAME: example-tangle-exclude-code-block
#+BEGIN_SRC org-mode :tangle no
,#+BEGIN_SRC emacs-lisp :tangle no
(setq some-other-custom-setting nil)
,#+END_SRC
#+END_SRC

** Testing configuration

As I worked through developing this configuration I tangled the code using ~org-babel-tangle~ (bound to ~C-c C-v t~) and
then started Emacs with the ~--init-directory ~/.config/emacs/config~ so that it picked up the tangled configuration
files within this directory (i.e. ~early-init.el~ and ~init.el~).

** Rendering to HTML

As with much of my config its not original, I found someone else who had done what I want to do and have learnt/borrowed
(heavily) from them. In the case of this literate configuration and its conversion to HTML I have taken inspiration from
[[https://github.com/Panadestein/emacsd][Panadestein's emacsd]] repository.

Of particular use is the GitHub workflow which runs a Bash script ([[https://github.com/Panadestein/emacsd/blob/master/publi.sh][publi.sh]]) to use Emacs to [[https://github.com/Panadestein/emacsd/blob/master/build-site.el][build-site.el]]
 which I have copied in their entirety to build and deploy the site on GitHub pages (for now, I intend to migrate it to
 Codeberg Pages once I've sussed those out).


* Links

+ [[https://orgmode.org/worg/org-contrib/babel/][Babel: Active Code in Org]]
+ [[https://leanpub.com/lit-config/read][Literate Configuration | Diego Zamboni]]
+ [[https://org-babel.readthedocs.io/en/latest/][Org Babel reference card]]
+ [[https://www.masteringemacs.org/][Mastering Emacs]]

** use-package

+ [[https://www.gnu.org/software/emacs/manual/html_mono/use-package.html][Emacs Manual : use-package]]
+ [[https://ianyepan.github.io/posts/setting-up-use-package/][Setting up use-package]]
+ [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using use-package the right way - (think)]]

** Examples

+ [[https://panadestein.github.io/emacsd/][Emacs literate configuration]] by Panadestein
+ [[https://tkreuziger.com/posts/2023-11-24-setting_up_my_literate_config_for_emacs/][Setting up my literate config for Emacs | Tristan Kreuziger]]
